* Description

#  The VR Solution
The early days of Virtual Reality have revealed a fundamental flaw in the user experience, and it's among the core reasons why this budding technology is not yet widespread. Much like a computer without a mouse, Virtual Reality without the Tours can be a clumsy and indirect experience for the user. 


# Making Nature Virtual

As VR is a fully immersive technology, we developed the Torus based on the natural flow of energy experienced by the human body in the physical world, making the transition into VR as intuitive as possible. The Torus embodies the balanced energy flow found in sustainable systems of all scales throughout our planet. This natural energy flow is the primary component that allows each living entity to thrive on its own while also existing in unison with all other live organisms. 

The Torus is based on a central axis - the equilibrium. Depending on how you choose to build your customized Torus, varying parts of the human body can occupy the centerpoint - eyes, feet, midsection, etc. The body can also be placed at the outside of the Torus sphere or even at the bottom or top. The variations can be as simple or complex as you wish. 


# Information in VR

Once the Torus emerges around the user, they’ll notice information in two separate locations. By glancing above eye level, they’ll find content delivered similarly to the way information is displayed on the top bar of the computer screen. By looking down they’ll find the bottom bar. Depending on how you choose to build your content, the user may scroll through with eye movement, controller commands, or by adjusting the positioning of a virtual band around their wrist. Once the desired information is selected, the featured content appears at a comfortable viewing angle in front of the user.

The Torus is a foundational tool within which we'll construct customized content. 


[Download 2-Page PDF](Documents/website-text-/Pages/1Solutions/1Products/Jan Launch/Torus)
