
*** Aus
**** situation  

- Not everyone thinks to visit the Northern Territory when they plan their trip Downunder.  

- The destination can be relatively expensive and people do not realize that the experience here is superior.

**** solution

- Work with an opinion leader to position the destination properly.

- Use the platform of this loyal audience to target the right market, at the right time, and with a message that is going to get them up and move.  

- Generate leads and capture contact information to follow up with continued dialogue

**** execution

- Pauline Frommer to visit the Outback and record webisodes
 
- While in destination and upon return, push out social media and radio “live-cuts” sharing the experience in real time

- Upon return, run testimonials on-air, run pre-rolls of the video in iHeartRadio

- Contest to win a trip have as similar experience

**** results

- Over delivered more than 800,000 impressions. 

- The experience became natural conversation for Pauline at events, travel shows and in her online/on-air conversations with the audience 

- An over-delivery of contest entries and a 40% opt-in rate to receive more information!

*** Ital
-situation
-solution
-execution
-results


*** Hawaiian Airlines
-situation
-solution
-execution
-results


*** Kelly Vision
**** Situation
**** Solution
**** Execution
**** Results

*** Live Nation
**** Situation
**** Solution
**** Execution
**** Results

*** Prom Peru
**** Situation
**** Solution
**** Execution
**** Results

*** Taiwan
**** Situation

Taiwan is of the lesser known Asia destinations but has an amazing culture to share. We needed to stand apart from the rest of Asia. Knowing we will not brand bigger than China or Japan in the short-term, we complimented them.
**** Strategy: 
(1) Bring a credible message about culture, food, beauty and other features of the destination. 
(2) Transfer the earned trust and credibility of a known personality to highlight “Why Taiwan”. 
(3) Share from a first person perspective. 
(4) Develop PR exposure through creative engagement

**** Execution
Travel expert, Pauline Frommer, brought the travel show to Taiwan. We created an array of content to share across multiple distribution channels. Integrate with entertainment darlings and showcase the culture through event partnerships in Bryant Park.

**** Results
- 7% increase in US visits year over year. 
- Renewed production program at a 45% increase in investment. 
- 12% over-delivery of media commercials. 
- 10 million media impressions through “earned media”. 
- Evergreen content to re-purpose indefinitely.

*** HR
**** situation
Hard Rock Riviera Maya had a PR objective to earn big media. They had access to top music talent and a badass resort in Mexico.   

**** solution

Elvis Rocks Mexico -  Riviera Maya

Throw a massive party
400 attendees 
Match Top music Talent
Strategically promoted
Earn coverage

**** execution
Live From Mexico we broadcasted a weekend of dysfunctional family fun to 63 million.   Live music performances from Nick Jonas and Brett Michaels, all the beach, spa and partying anyone person could handle... 

**** results
- 201,008,806 Gross Impressions
- 280,000 contest entries
- $2.59 million media/PR value (15cpm)
- 86 million social media impressions
- 400 attendees
- $97,000 avg HHI
73% Earned Media

**** Want to know more?  
****** Expand story here, or 
It was the dead cold of winter. Those endlessly numb days. It was still dark but half the city was on their way to work. At 7:29AM while inching through traffic, Elvis Duran in his jolly voice announced to the country his plans for vacation.   His words riverbed live to 75 cities and  was giving away vacations to 5 million people.  This May he and his family would be flying to the Hard Rock Riviera Maya Resort in Mexico.
​
Hyped as the vacation of the year, 400x people purchased packages to join the parties.
​
We recruited Nick Jonas and Brett Michaels to join.
​
Over the weekend hundreds lived life to the fullest via Hard Rock's all inclusive, while millions enjoyed vicariously.   The program earned more than 85 million impressions on social media, alone.  

Media outlets across the country picked up the fun, earning more than 200 million impressions and more than $2.5 million in media value.
​
The vacation has now become a tradition.

****** Submit request
submit a request and we will reply within 48 hours.

[text box: name]
[text box: email]
[text box: What would you like to know more about?]
=== request



Contacta Dana Barasi

