* header

Productions

* Second 

Australia's Northern Territory
/You haven't been down-under until you've been out-back/

* Abstract

**** Situation  

- Not everyone thinks to visit the Northern Territory when they plan their trip Downunder.  

- The destination can be relatively expensive and people do not realize that the experience here is superior

**** Solution

- Work with an opinion leader to position the destination properly

- Use the platform of this loyal audience to target the right market, at the right time, and with a message that is going to get them up and move.  

- Generate leads and capture contact information to follow up with continued dialogue

**** Execution

- Pauline Frommer to visit the Outback and record webisodes
 
- While in destination and upon return, push out social media and radio “live-cuts” sharing the experience in real time

- Upon return, run testimonials on-air, run pre-rolls of the video in iHeartRadio

- Contest to win a trip have as similar experience

**** Results

- Over delivered  more than 800,000 impressions. 

- The experience became natural conversation for Pauline at events, travel shows and in her online/on-air conversations with the audience 

- An over-delivery of contest entries and a 40% opt-in rate to receive more information!


