* Header

Productions

* Second

Taiwan

* Abstract

**** Situation

Taiwan is of the lesser known Asia destinations but has an amazing culture to share. We needed to stand apart from the rest of Asia. Knowing we will not brand bigger than China or Japan in the short-term, we complimented them.
**** Strategy: 
(1) Bring a credible message about culture, food, beauty and other features of the destination. 
(2) Transfer the earned trust and credibility of a known personality to highlight “Why Taiwan”. 
(3) Share from a first person perspective. 
(4) Develop PR exposure through creative engagement

**** Execution
 Travel expert, Pauline Frommer, brought the travel show to Taiwan. We created an array of content to share across multiple distribution channels. Integrate with entertainment darlings and showcase the culture through event partnerships in Bryant Park.

**** Results
- 7% increase in US visits year over year. 
- Renewed production program at a 45% increase in investment. 
   s
- 10 million media impressions through “earned media”. 
- Evergreen content to re-purpose indefinitely.

