
* Facematch 

** Tagline 
Ad Viewer Verification

** Abstract
Explicitly know when an ad-viewer visits your location

** Intro
The age-old challenge: how do you really know if your ad worked? Generally, you don’t. You have insights, clues, and stats but are missing a key metric: "viewer-visit verification."

By analyzing Facebook user login info and profile photos, we'll create, encrypt, and database a library of photos, cross reference it against the photos taken of visitors when they arrive at customs, and produce a number that represents your ad's success rate. 


** Features 
Refer to visual on  page 17 of same ID file as directed to above 

** Benefits
We will Implement a software that will verify  ad-viewers who visit Cayman through face recognition technology.   This metric will allow Cayman to increase advertising by  an estimated 40% effectiveness, dollar per dollar.      

This turn-key solution will hold media partners accountable to quantifiably increase visits.

** Production

1	Custom design Cayman's face-matching software
2	Integrate software into current IT Infrastructure
3	Verify ad viewers who visit Cayman
4	Analayze data
5	Improve creative and distribution choices
6	Hold media partners accountable for delivering tourism

*** Software Production	

Phase 1, Design 	[6 weeks] 	$48,000
Technological architecture and preliminary design. You'll be able to see a non-functioning example of the software 

Phase 2, Create 	[16 weeks] 	$186,000
Develop, test, and deploy

Phase 3, Refine 	 [4 weeks]	$93,000 							     	     
Quality Assurance, user test, and deploy

** Technology 
Refer to "system architecture" in Dropbox 
Location: Team activity Refer to "system architecture" in Dropbox 
Location: Team activity --> client props --> Cayman Facematch --> Software Folder Sept 17 --> In Design File

We will Implement a software that will verify  ad-viewers who visit Cayman through face recognition technology.   This metric will allow Cayman to increase advertising by  an estimated 40% effectiveness, dollar per dollar.      

This turn-key solution will hold media partners accountable to quantifiably increase visits.
 t and decipher patterns and correlations). 
-Training an image classifier (neural net or support vector machine based depending on the available data)


*** Prerequisites to implement facial recognition technology: 

-Advanced understanding of Linear Algebra
-Advanced understanding of Convolutional Neural Networks
-Advanced understanding Tensorflow or frameworks alike

** Deliverables
Based on our six months of consultancy and development, we will deliver
 a ~50 pages specification defining:

-The integration with the existing system
-The integration with Facebook facial data
-The database structure 
-The application UI 
-The application documentation

** Evolution of Development

*** Year 1

For the remained of this year we can review IT infrastructure  and ad buying data to get ahead on developing your specification.  We will design both the preliminary stages of the facial recognition software and the ad strategy to populate our  face matching database. The real work begins next year.

			
*** Year 2

During the first 16 weeks of 2018 we will develop Cayman's Face Matching software.  This includes a full specification, production and implementation.   A  May launch will conclude the work budgeted in this document. Future work will take place outside the scope of this proposal. You software will improve with data.

				
*** Year 3

Using results obtained in 2018, you'll now be able to grow your application and enlarge your Face Matching database to gather more pertinent analytics. This could include integrating biometric software across other media content, increasing user base, and, allowing you to better-target the right audience and increase heads in beds.
