* Game Engine


*** What is the technology

A *game engine* is a software framework used to create interactive 3D media (XR).  We build XR in game engines.  Game engines enable us to provide you with all the features of the internet from social sharing to payment.  
*** How the tech is used for VR

Game engines equip developers to custom design virtual environments, program rules and netowrk experiences to be shared on personal computers, mobile dvices and gaming consules. Game engine framework's core functions are to render 3D graphics, engineer physics/collision (and response systems) manage memoreym shread, and graph scenes.   

Nova economizes the process of virtual reality (XR) development by adapting game engine builds (software executable) to create new VR expereinces. 

*** Why this matters (makes you money)

By developing a project with this frame work, producers save time and money.   

- This frame work is *Programmable* you can re-program your you content easily and often.  Year over year you will save 40% of development costs compared to producing video content.  

- media will be *interactive*.  Visitors will engage their environment, chage the world around them, and be a part of the story.  This engagement drastically increases impact

![Dale's Cone of Learning] (/Users/joemecca/Documents/website-text-/Pages/1Solutions/2Services/2Production/Develope/1Game Engine)

- The experience is *netowrked* meaning it is connected to other real people. You and your friends will travel the customized worlds you design /together/.

- The visitor will have a *visceral* expereince, because game engines can create life-like simulations.

![Your Brain on VR] /Users/joemecca/Documents/website-text-/Pages/1Solutions/2Services/2Production/Develope/1Game Engine

Game Engines enable comprehensive developmenwith all the features of the internet from collaboration to payment, in 3D.


*** Program examples:
 
**** Virtual World Build

text descrion (Technical, metaphysical, benefit)

**** Infinte Walker

**** XR Color

**** XR Music

***** KK 1 sentence description 
- for all four programs
- 10 work max
- text descrion (Technical, metaphysical, benefit)



* Artificial Intelligence

Artificial Intelligence is intelligence demonstrated by a machine.   The branch of computer sciences that studies AI research studies and developes machines to perceive the environment and make adjustments to influence the likelihood of success at achieving goals.  Machines are designed to mimic "cognitive" functions associated with human minds, like "comprehension", or "deductive reasoning".


Artificial Agents enhances VR through 
- Personalization 
- Generative design
- Contextual awerness
- Data indexing
- character engines


*** Personaliztion

**** What it is


**** how is used in vr
**** why thats good (makes them money)

*** Generative design

**** What it is
**** how is used in vr
**** why thats good (makes them money)

*** Contextual awerness

*Contextual awareness* allows the machine to compare the query to known information.  For example, google maps knows your location.   If you press the blue dot (ask where you are) it compares this request to its knowledge of the map.  The computer has a small degree of contextual awerness.   

In Virtual reality When a AI character knows it's surroundings it will play more thoughtfully, making for better competition/collaboration and game play.  AI characters train through trial and error.  They record the context of the successes and failures and adjust to optimize likelihood for success.   

***** BS   how can we use this information in VR? :SS:
---- You can use this information for 3D shopping. remote focus groups for shopping.



We synch with the player's cell phone and they post their experience to social media.


**** BS AI with VR an Social? :SS:





*** Data indxing

**** What it is

The process of deploying machiens designed to track, collate, distill and visualize, data relating to VR players.   Processing this data and indexing it for you together wholistically understand the user's experience. The AI creates visuals of comple data in 3D, so you can move around and scale the data in real-size.

**** JB 3d data geaphic
     SCHEDULED: <2018-02-21 Wed>

For more, we reccomend the Stanford 100 Year Study on AI https://ai100.stanford.edu/

AN open, non-profit projected aimed to “facilitate an informed conversation about AI that is grounded in data... comprehensive resource of data and analysis" for the community at large so everyone from academics, businesses, government, media, and all to better understand the complex field of Artificial Intelligence.


*** Character engines


In Virtual Reality (XR) develops "character engines" into the experience.  These engine the characters behavior and desicion making.   By programming learning algorythms your characters can remember information about you, your game play, and whatever else we teach it to... within reason.  They can be your virtual friends.

Intelligent characters make for better game play.  The user's experience is familiar and personalized.   When you allow visitors to customize their environment, feel ownership.  Intelligent characters increase experience affinity and replay-value.


*** Programs of Interest

- Live forever audio capture
- Professional Services
-

Financial strategy (password protect)


*** What the technology is


*** How it is integrated in VR
*** Why they care (it maks them money)



Anything Siri or Alexa can do now they will do better in VR, because VR gather 


 to Paris for the evening of the 17th from New York"  "Call me a   The machine simply needs to know to teleport to that 360 video content.   "Bring me to wherever Kelly is"  or "Tell my wife I am going to be thirty minutes late"  The system needs to be smart enough not only to understand the intent, but also to know who the wife is and the best way to contact her. No extraneous information is necessary, no option list, no follow-up questions. We call this Minimum Viable Interaction (MVI).




We will talk with the concierge — not with commands, menus and quirky key combinations —but using our own human language.   This is Natural Language Processing, a foremost technique for human-to-machine discussions.   

## Index Data
artificial intelligent algorthms to better index user data.   If information is better categorized it will be better read.  Better read and understood data will be better processed by humans to more fully udnerstand broad swaths of the VR information displayed to them.

## Characters:     
Imagine a virtual character with behaviors that were "smart", as in it learned from past mistakes.   You already know this from referral automation on the web especially within services you tow which subscribe.  Example: /Netflix reccomends.../

 In virtual reality, these "AI Characters" will improve their suggestions and improvisation with generative design.  These will be non-player characters (NPCs) but simulating human behavior.   As Turing tested, If you cannot distinguish the difference between another player and a NPC, what’s the difference?    

Household examples like Siri, Alexis, or Cortana remind us AI has a long way to go, and we shouldn't hold our breath.   In virtual realitythese assistants will be present in physical form.   You can of course customize your virtual companion not just by appearance but by personality, attitude, relationship and onward.   With vast personalization settings available for the user to adjust we give control to the user instead of guessing what they want.  we can adjust the algorithms to our own preference, and then they learn on their own.    

## Self Learning 
AIs will teach itself to interact with avatars by practicing on the hundreds of avatars.   Everyone’s funded participation goes to the build of a single AI who’s job is to interact with real people


## Generative Design  
 
/coming soon/

## Personalizations

/coming soon/



* Biometric Software

Biometrics refers to metrics related to human biological characteristics, including physiology nd neurology. In virtual reality biometrics are used to measure interest, entertainment and intent.   

By monitoring physiological cues such as skin galvenization, eye dialation, heart and breathing rate, computers infer and escrapolate further details about the player and their experience.

This enables us to remove the many errors and barriors that stand the user and creator regarding how and why content is effective.   My connecting our development tools to biometrical sensors and indexing activity we determine which scenes, scenarios and situations are of most interest. 

The process is based on seven primary emotions: happiness, sadness, anger, contempt, fear, disgust, and suprise. 

# Blockchain

## How is Blockchain relavent to VR?
- secure transactions
- general stability of the platform
- allowance of microtransactions
- Fair rewards for publishers, no payment cuts


A "block"-"chain" is a distributed database (or ledger) that maintains a continuously growing list of ordered records.  This continously growing ordered list is called a "block".  It is connecting linearly to the other blocks, and making it a "chain" of blocks.  Features, such as "smart contracts" allow us to host concerts in VR with secure micro-transactions and affirmed security.

## Imutable
Blocks are designed to be inherently resistant to modification of the data — once recorded the data in a block cannot be altered retroactively. 

## Distributed
Records are spread evenly throughout all participants.  In virtual reality, collaborative

## Smart contract 
An agreement fascilitated by a computer protocol, enforcing the delivery of agreed terms without a third party (human).  Transactions are secure, trackable and irreversible.


## automated
Through peer-to-peer networks and a distributed timestamping server, a blockchain database is managed autonomously.

A VR on blockchain can form the ultimate democracy with an independent economy and freedom from the regulation of any governing body outside of itself.   We can build new life, economy and power-structure with the combination of these techonlogies.  In fact, we already have.


*** What the technology is
*** How it is integrated in VR
*** Why they care (it maks them money)
* Iot

*** What the technology is
*** How it is integrated in VR
*** Why they care (it maks them money)
* Haptics


*** What the technology is
*** How it is integrated in VR
*** Why they care (it maks them money)
* Photogrammetry:
	⁃	
	⁃	-- create 3d detailed vr spaces an d environemnts
	⁃	-- create models
	⁃	-- 3d scan expert (software
	⁃	-- Hardware - DSLR camera + lighting rings
	⁃	-- converying real space in VR - realism
	⁃	-- and integrating real locations into vitual worlds
	⁃	
	⁃	
	⁃	** SS downlaod phtogrammtery app and use 123D capture
	⁃	
	⁃	** Blockchain in VR
	⁃	—  CEEK is a vr blacken, uses smart contracts to have live vr concerts and other events.  works with ether
	⁃	— mana coin and decentraland
	⁃	— gaze coin. uses a custom engine to track a views eye movements and how much they are paying attention to certain information.
	⁃	— ad chain
	⁃	— make a vr creation, general stability of the platform is assured through blockchain.  
	⁃	— creative rights and credits
	⁃	—  vibe hub.- compineing crypto/blockchain/vr, buy and sell celebrity sessions, meet and greet with favorite artist or professional to learn a new skill — allowance of micro transactions with vive currency will usher in a new paradigm of social interactions and transactions .  more immersive than a live chat or phone call.   features, unique social experiences.  ERC20 token.   fair rewards for publishers, no payment cuts.  secure transactions
	⁃	— star citizen, funding on the blockchain
	⁃	
	⁃	
	⁃	


*** What the technology is
*** How it is integrated in VR
*** Why they care (it maks them money)
* VR Cryptocurrencies

*** What the technology is
*** How it is integrated in VR
*** Why they care (it maks them money)

	⁃	— make payments with crypto- more secure. micro transactions
	⁃	— lower tax rates
	⁃	— less moderation in the purchasing
	⁃	— more open market, no one telling you what you can and can’t sell.   
	⁃	— increases cost of graphics cards
	⁃	
	⁃	
* Cloud computing


*** What the technology is
*** How it is integrated in VR
*** Why they care (it maks them money)
	⁃	
	⁃	— Allows for remote storage
	⁃	— networked gaming
	⁃	— stream the VR game from someone else computer to yours
	⁃	— games are putting them all in the cloud, will run more smoothly
	⁃	— try an app before you download it
	⁃	— 
	⁃	
	⁃	

* The Web XR:

*** What the technology is
*** How it is integrated in VR
*** Why they care (it maks them money)

	⁃	— open and free platform
	⁃	— allows for more lightweight experiences
	⁃	— web XR framework, and can build anything in it
	⁃	— in unity you need to build from nothing.
	⁃	—
	⁃	
	⁃	


* Finite state machines

*** What the technology is
*** How it is integrated in VR
*** Why they care (it maks them money)


	⁃	— characters to engage 
	⁃	— used for implementing AI.
	⁃	— limitations of engagement - 
	⁃	— transition period
	⁃	— not in unreal for engine 4. (because it has stuff it can emulated, but someone else made a plug-in) it is not needed r useful until you use it or need it
	⁃	
* AI

	⁃	—  virtual assistant
	⁃	— store front navigation, there are 5 store fronts and they don’t all telly ou what you want to know.  you see all the same apps on al of them.   they are 
	⁃	— personalized information, know what you’ve seen and haven’t seen nd what you would be most interest in and receptive to buying.  
	⁃	— generative design.  based on your prefrences    
	⁃	
* Haptics
	⁃	— omni-tredmil  - have movement without the sensors.  you are not limited in space.  small foot space.   
	⁃	      —— safe action
	⁃	      ——  more physical movement and interaction
	⁃	      — — more immersive game play
	⁃	      — — 
	⁃	
	⁃	— subpack 
	⁃	   — — real time feedback, more immersion, 
	⁃	   — — elicits deeps emotions
	⁃	   — — stronger brand connection
	⁃	   — — experience things you could not feel in real life
	⁃	   — — raises the interest and intrigue
	⁃	        —— >   more play time more sales, increased sharing, better usability, retain a market for the product, better monetizati
	⁃	— controller feedback
	⁃	    — better relate to it.  better learn, better understand.  —   more you know, the better decisions you can make, the more you care,— passive subtle learning.   speak to them subconsciously.   gamification.   all he needs to win is pepsi (soda drinker pro)
	⁃	
	⁃	


* optical tracking 

*** What the technology is
*** How it is integrated in VR
*** Why they care (it maks them money)


	⁃	— tracks the person in the room and 
	⁃	—  more immersion.
	⁃	— less accidents, safety
	⁃	— enables spatial cognition
	⁃	— enables mixed reality
	⁃	— assists with proper movement
	⁃	— can gage your interest level 
	⁃	— computer vision integrates the surrounding area.   opens up to new methods.   
	⁃	if you are teleporting you cannot do anything that is balanced bath, and by tracking he movement
	⁃	—  
	⁃	
	⁃	
	⁃	Eye-tracking
	⁃	  — gage interest
	⁃	  — match attention with intention
	⁃	  — measure awareness, interest, focus, potentially intent
	⁃	  — measure effectiveness 
	⁃	
	⁃	
	⁃	AI Engine
	⁃	
	⁃	
	⁃	give them the versatility to chose a pasificis or a more aggressive route we can gage a lot about a person, their intereste, their demographic, 
	⁃	Bio-metric feedback
	⁃	
	⁃	
	⁃	
	⁃	
	⁃	** PRODUCT:
	⁃	
* motion tracking 



*** What the technology is
*** How it is integrated in VR
*** Why they care (it maks them money)

	⁃	— capture a real persona and put them as a NPC
	⁃	— enables real human movement for a npc.  
	⁃	— make a more realistic environment , more immersive, (not someones interpretations- -  looking at something you recognitive not just a bunch of polygons
	⁃	
	⁃	Projection mapping - 
	⁃	** the inverse of virtual reality
	⁃	
	⁃	— a strong connection to physical world objects like a building.  people work in it, see it everyday , grandfather helped build it
	⁃	— it is the art canvas
	⁃	— inverse a game engine vr/ar experience as a promotion
	⁃	— interactive tool, lets people engage
	⁃	— education tool.   
	⁃	
	⁃	
	⁃	
 -  - - Token sale of Vibe hub
	⁃	
	⁃	
	⁃	
	⁃	
	⁃	
	⁃	PRODUCTS:
	⁃	
	⁃	Why would someone want an anonymous company 
	⁃	— t protect their crypto
	⁃	— avoid paying unwanted third parties
	⁃	— benefits of anonymity,  security and safety from malicious players
	⁃	
	⁃	AR Branding 
	⁃	 — points for 
	⁃	— receive information (sponsored by brand content) and it will provide you with convenience and education and —> 



* Gaming industry:

- mobile 

platform membershare and size?

Which can we push VR games to.

Profile of the gamers.

Testimony on the future of XR by gamers

use gamers gate

Videogame junkies is a big game reviewer.

List of game industry influences.

In the likes of the gaming indsutry, we are indy


- made for competition
-- team based, co-=operation, communication and planning
-- strategy
-- social
-- unchartered experiences
-- communication
-- ranking/tiers 
-- playability
  + mechanics that work (unique mechanics) 
  + differnet 
-- balance
  + 

** spin off culture of the games
*** Community

*** Fan Art

*** Lore / Theories

*** Music


** Replay value
 - the dungeons are randomly generated. 
 - different endings
 - differnet gae play
 - variety of characters
 - variety of characters 
 - 


** 
