* Game Engine

*** What is the technology

A *game engine* is a software framework used to create interactive 3D media (XR).  We build XR in game engines.  Game engines enable us to provide you with all the features of the internet from social sharing to payment.  
*** How the tech is used for VR

Game engines equip developers to custom design virtual environments, program rules and netowrk experiences to be shared on personal computers, mobile dvices and gaming consules. Game engine framework's core functions are to render 3D graphics, engineer physics/collision (and response systems) manage memoreym shread, and graph scenes.   

Nova economizes the process of virtual reality (XR) development by adapting game engine builds (software executable) to create new VR expereinces. 

*** Why this matters (makes you money)

By developing a project with this frame work, producers save time and money.   

- This frame work is *Programmable* you can re-program your you content easily and often.  Year over year you will save 40% of development costs compared to producing video content.  

- media will be *interactive*.  Visitors will engage their environment, chage the world around them, and be a part of the story.  Thiiss engagement drastically increases impact

![Dale's Cone of Learning] (/Users/joemecca/Documents/website-text-/Pages/1Solutions/2Services/2Production/Develope/1Game Engine)

- The experience is *netowrked* meaning it is connected to other real people. You and your friends will travel the customized worlds you design /together/.

- The visitor will have a *visceral* expereince, because game engines can create life-like simulations.

![Your Brain on VR] /Users/joemecca/Documents/website-text-/Pages/1Solutions/2Services/2Production/Develope/1Game Engine

Game Engines enable comprehensive developmenwith all the features of the internet from collaboration to payment, in 3D.

*** Program examples:
**** Virtual World Build
text descrion (Technical, metaphysical, benefit)
**** Infinte Walker
**** XR Color
**** XR Music

***** KK 1 sentence description 
- for all four programs
- 10 work max
- text descrion (Technical, metaphysical, benefit)


* Artificial Intelligence

Artificial Intelligence is intelligence demonstrated by a machine.   The branch of computer sciences that studies AI research studies and developes machines to perceive the environment and make adjustments to influence the likelihood of success at achieving goals.  Machines are designed to mimic "cognitive" functions associated with human minds, like "comprehension", or "deductive reasoning".


Artificial Agents enhances VR through 
- Personalization 
- Generative design
- Contextual awerness
- Data indexing
- character engines


*** Personaliztion
**** What it is
**** how is used in vr
**** why thats good (makes them money)

*** Generative design
**** What it is
**** how is used in vr
**** why thats good (makes them money)

*** Contextual awerness

*Contextual awareness* allows the machine to compare the query to known information.  For example, google maps knows your location.   If you press the blue dot (ask where you are) it compares this request to its knowledge of the map.  The computer has a small degree of contextual awerness.   

In Virtual reality When a AI character knows it's surroundings it will play more thoughtfully, making for better competition/collaboration and game play.  AI characters train through trial and error.  They record the context of the successes and failures and adjust to optimize likelihood for success.   

***** BS   how can we use this information in VR? :SS:
---- You can use this information for 3D shopping. remote focus groups for shopping.



We synch with the player's cell phone and they post their experience to social media.


**** BS AI with VR an Social? :SS:

*** Data indxing

Artificial intelligent algorthms to better index user data.   If information is better categorized it will be better read and understood.  We'll comprehend larger and large sums of data, especially very intimate information VR can fascilitate, such as body movements and emotional states.  

A semi-technical explanaition of the process is to track, collate, distill and visualize.

By visualizng the data of VR players through   indexing you wholistically understand the user's experience. The AI creates visuals of comple data in 3D, so you can move around and scale the data in real-size.  This engagement significantl increases comprehension.  

*** Character engines

In Virtual Reality (XR) develops "character engines" into the experience.  These engine the characters behavior and desicion making.   By programming learning algorythms your characters can remember information about you, your game play, and whatever else we teach it to... within reason.  They can be your virtual friends.

Intelligent characters make for better game play.  The user's experience is familiar and personalized.   When you allow visitors to customize their environment, feel ownership.  Intelligent characters increase experience affinity and replay-value.


**** Programs of Interest

- Live forever audio capture
- Professional Services

** Natural Language Processing

*** What the technology is
*** How it is integrated in VR

We will talk with the concierge — not with commands, menus and quirky key combinations —but using our own human language.   This is Natural Language Processing, a foremost technique for human-to-machine discussions.   


* Biometric Software

Biometrics refers to metrics related to human biological characteristics, including physiology nd neurology. In virtual reality biometrics are used to measure interest, entertainment and intent.   

By monitoring physiological cues such as skin galvenization, eye dialation, heart and breathing rate, computers infer and escrapolate further details about the player and their experience.

This enables us to remove the many errors and barriors that stand between user and feedback.By using bio-measurements we improve the storyline and pin point player's interest, displeasure, fatigue, excitement and much more.  

The seven primary emotions monitored in traditional commercial software is happiness, sadness, anger, contempt, fear, disgust, and suprise.


***** KK lab Live on biometric applications
- hwo do we use these physiological cues to improve expereinces
- quantifiably, why does this information matter?

* Blockchain 

A "block"-"chain" is a distributed database (or ledger) that maintains a continuously growing list of ordered records.  Some major blockchain features include: 

- Secure, private transactions
- Microtransactions
- Public, imutable record keeping
- Democratized administrative control 
- General platform stability


Features, such as "smart contracts" allow us to host concerts in VR with secure micro-transactions.  An inumeral amount of people can attend concerts and experiences live with musicians and artists.  On a blockchain, you can charge them based on network contribution.  

Blockchain tech allows the users to exclusively own and control them content and platform the build.  


***** KK lab live blockchain and vr- very high level (elemenatary words and concepts) 
- highly technical
- describe the tech archeteure in paragraph form on a VR on the block chain

* Iot

The Internet of things (IoT) is the network of digitally conntected devices,such as home appliances and vehicles, that are conntected to the internet.  These devices are equipped with sensors and operating software, enabling remote access and managment.  For example, adjusting your beach house thermastat from upstate, or  recieving a text message notifying you the plants need watering (because your botany sensors noticed drought.  

Simulations of physical tasks allow for us to practice, minimize risks and scale profit margins.   Imagine remotely controlling construction machinerary.  By being in the simulation, apprentices can train without the risk of hurting themselves.   Experts can control machines remotely, cutting down on transportation costs.   Through the VR simulation one can navigate the controls to operate an actual piece of machinerary just as effectively as if he were int he machine itself, but from the other side of the world.  This is the "internet of things", which will quickly evolving into the "Internet of Everything" (IoE) and then the "Internet of Humans" (IoH).


***** JB internet of things graphics 
-- see example here; https://en.wikipedia.org/wiki/Internet_of_things#/media/File:Internet_of_Things.jpg


***** KK lab live on simulations connected to physical world shit
- focus on how simulations save time and money

* Haptics

the communication of devices thhrough touch and feel, as a reaction to an action.  This is the science of applying tactule sensations to controllers to interact with computer applications.   


Add a visceral dimension to virtual expeirences and 3D environments, most frequently by applying vibration, or electrostatic shock.  By using ex-devices, like gloves, vests, shoes and so on, the player receives non-verbal, non-visual feedback from the computer. 

Virtual experiences that train seurgeons and athletes rely on haptic technology to train muscles to maneuver with better presicion.  Our hands determine hardness, shape, tempertaure, texture weight and more.  There is a lot to be undetstood through touch and haptics development is a major contributor to immersion.  


***** KK Lab Live on how haptics engage senses  
- and how those senses influence perception, desicion making, retention (learning)
- write as if it is all currently happening, not as if it soon will
- shout out companies doing awesome stuff

* Photogrammetry:	

Is the scanning, computing and rendering of 3D models through 2D photographs and distance differentiators.   By taking several hundred photos of an object from strategic angles we redesign and texture photorealistic objects and environments.

Photogrammetry conveys real spaces as digital simulations,  Think "immersive realism".

Re-creating real environments in virtual reality enables us to simulate travel and fascilitate training.  By maping locations 

**** Related Products:	
- Bloomaway
- 




*** What the technology is
*** How it is integrated in VR








***** KK Lab Live - how phtogram is being used in XR
- objective: communicate photogram's best applications in XR
- 1-4 examples of industry uses, max
- intro half technical half metaphysical
- body 75% technical, 25% creative charm
- conclusion metaphysical
--  ^^ test this approach o



related blog




* Cryptocurrencies

Cryptocurrency is a a digital asset, secured by cryptography and designed to serve as monetary currency.   "cryptos" are renown for fast, secure, peer-to-peer transactions, developed on "blockchain" technologey.  

As a digital medium of exchange cryptourrencies are a convenient solution to buy or sell digital property. Cryptocurrencies empower virtual worlds with stable economic measures.

Virtual worlds might be bigger than your realize.  Nearly twenty years ago SeconfLife, a popular 2D virtual world, had a population greater than Australia's.   

In 2001 economist Edward Castronova estimated virtual world EverQuest's gross national product (GNP) at $135 million.  Per capita, richer than India, Bulgaria or China.  Today virtual gods amrket is estimated well over $15 billion. More than 430,000 players logged more than two hours per day at that time. 

The benefits of using crypto-currencies beyond secure and fast transacting without a third party is the anonyminity of holdings and fertile ground-work for more open markets.  It doesn't require


* Cloud computing



*** What the technology is
*** How it is integrated in VR
*** Why they care (it maks them money)
	⁃	
	⁃	— Allows for remote storage
	⁃	— networked gaming
	⁃	— stream the VR game from someone else computer to yours
	⁃	— games are putting them all in the cloud, will run more smoothly
	⁃	— try an app before you download it
	⁃	— 
	⁃	
	⁃	

* The Web XR:

*** What the technology is
*** How it is integrated in VR
*** Why they care (it maks them money)

	⁃	— open and free platform
	⁃	— allows for more lightweight experiences
	⁃	— web XR framework, and can build anything in it
	⁃	— in unity you need to build from nothing.
	⁃	—
	⁃	
	⁃	

* Finite state machines

*** What the technology is
*** How it is integrated in VR
*** Why they care (it maks them money)


	⁃	— characters to engage 
	⁃	— used for implementing AI.
	⁃	— limitations of engagement - 
	⁃	— transition period
	⁃	— not in unreal for engine 4. (because it has stuff it can emulated, but someone else made a plug-in) it is not needed r useful until you use it or need it
	⁃	
* AI

	⁃	—  virtual assistant
	⁃	— store front navigation, there are 5 store fronts and they don’t all telly ou what you want to know.  you see all the same apps on al of them.   they are 
	⁃	— personalized information, know what you’ve seen and haven’t seen nd what you would be most interest in and receptive to buying.  
	⁃	— generative design.  based on your prefrences    
	⁃	
* Haptics
	⁃	— omni-tredmil  - have movement without the sensors.  you are not limited in space.  small foot space.   
	⁃	      —— safe action
	⁃	      ——  more physical movement and interaction
	⁃	      — — more immersive game play
	⁃	      — — 
	⁃	
	⁃	— subpack 
	⁃	   — — real time feedback, more immersion, 
	⁃	   — — elicits deeps emotions
	⁃	   — — stronger brand connection
	⁃	   — — experience things you could not feel in real life
	⁃	   — — raises the interest and intrigue
	⁃	        —— >   more play time more sales, increased sharing, better usability, retain a market for the product, better monetizati
	⁃	— controller feedback
	⁃	    — better relate to it.  better learn, better understand.  —   more you know, the better decisions you can make, the more you care,— passive subtle learning.   speak to them subconsciously.   gamification.   all he needs to win is pepsi (soda drinker pro)
	⁃	
	⁃	

* optical tracking 

*** What the technology is
*** How it is integrated in VR
*** Why they care (it maks them money)


	⁃	— tracks the person in the room and 
	⁃	—  more immersion.
	⁃	— less accidents, safety
	⁃	— enables spatial cognition
	⁃	— enables mixed reality
	⁃	— assists with proper movement
	⁃	— can gage your interest level 
	⁃	— computer vision integrates the surrounding area.   opens up to new methods.   
	⁃	if you are teleporting you cannot do anything that is balanced bath, and by tracking he movement
	⁃	—  
	⁃	
	⁃	
	⁃	Eye-tracking
	⁃	  — gage interest
	⁃	  — match attention with intention
	⁃	  — measure awareness, interest, focus, potentially intent
	⁃	  — measure effectiveness 
	⁃	
	⁃	
	⁃	AI Engine
	⁃	
	⁃	
	⁃	give them the versatility to chose a pasificis or a more aggressive route we can gage a lot about a person, their intereste, their demographic, 
	⁃	Bio-metric feedback
	⁃	
	⁃	
	⁃	
	⁃	
	⁃	** PRODUCT:
	⁃	
* motion tracking 



*** What the technology is
*** How it is integrated in VR
*** Why they care (it maks them money)

	⁃	— capture a real persona and put them as a NPC
	⁃	— enables real human movement for a npc.  
	⁃	— make a more realistic environment , more immersive, (not someones interpretations- -  looking at something you recognitive not just a bunch of polygons
	⁃	
	⁃	Projection mapping - 
	⁃	** the inverse of virtual reality
	⁃	
	⁃	— a strong connection to physical world objects like a building.  people work in it, see it everyday , grandfather helped build it
	⁃	— it is the art canvas
	⁃	— inverse a game engine vr/ar experience as a promotion
	⁃	— interactive tool, lets people engage
	⁃	— education tool.   
	⁃	
	⁃	
	⁃	
 -  - - Token sale of Vibe hub
	⁃	
	⁃	
	⁃	
	⁃	
	⁃	
	⁃	PRODUCTS:
	⁃	
	⁃	Why would someone want an anonymous company 
	⁃	— t protect their crypto
	⁃	— avoid paying unwanted third parties
	⁃	— benefits of anonymity,  security and safety from malicious players
	⁃	
	⁃	AR Branding 
	⁃	 — points for 
	⁃	— receive information (sponsored by brand content) and it will provide you with convenience and education and —> 


* Gaming industry:

- mobile 

platform membershare and size?

Which can we push VR games to.

Profile of the gamers.

Testimony on the future of XR by gamers

use gamers gate

Videogame junkies is a big game reviewer.

List of game industry influences.

In the likes of the gaming indsutry, we are indy


- made for competition
-- team based, co-=operation, communication and planning
-- strategy
-- social
-- unchartered experiences
-- communication
-- ranking/tiers 
-- playability
  + mechanics that work (unique mechanics) 
  + differnet 
-- balance
  + 

** spin off culture of the games
*** Community

*** Fan Art

*** Lore / Theories

*** Music


** Replay value
 - the dungeons are randomly generated. 
 - different endings
 - differnet gae play
 - variety of characters
 - variety of characters 
 - 


** 




** KK research sources
- Find 10 research documents PDFs from credible sources
- save them in a single folder.
- they will be linekd to on our "resource center"

 
