
**** Resource Center
Through academic relationships and our own study of the industry and its history, we'll periodically deliver presentations and supporting documents to assist your understanding of XR and better assist your clients. For example, Dale's Cone of Learning was an innovative study in the mid 20th century supporting the notion that within two weeks humans retain 90% of what they do and say - a breakthrough realization compared to the 50% retention of what we see and hear. Credible studies like this one are proving applicable again as the immersive XR worlds continue to grow.

***** Increase Profits
When you want Extended Reality to act as a marketing tool it helps connect the message you wish to deliver to the people you wish to reach. When the right people learn about the solutions you offer, you'll scale and increase profits. 

***** Reduce Internal Costs
Once you become fluent in Extended Reality, it'll shore up loose ends within your operations structure - automating some forms of internal training and offering a higher caliber solution to video chats and messenger platforms. 

