* Abstract: 

With thousands of people gathering at a major outdoor event, it’s crucial that a brand understands how to gain and maintain the attention of a significant number of attendees. With this in mind, we’ve created an original and comprehensive Extended Reality (XR) marketing strategy that begins spreading awareness of your product weeks before the event begins. By facilitating unique content for your brand in Augmented and then Virtual Reality, we help you market your product to one of the strongest buying demographics in the United States. From pre-production to content creation all the way through the financial strategy, we’re inviting you into the future of on-site marketing. 

* AR Features: 
This three-part XR marketing strategy begins by partnering with well known restaurant establishments throughout the country. By first offering a Pepsi beverage at a discount, the restaurant prompts the guest to take a photo inclusive of the discounted drink. By adding an AR image (Snapchat Geofilter) to the photo and sharing it on social media, the guest is entered into a chance to win tickets to the music festival. 

** Benefits: 
- Partner with well-known restaurant brand
- Increased sales of Pepsi beverages
- Promote social media sharing that highlights your product

* Pre-Release VR Features:
Offer a pre-release on the VR app store to a limited number of participants, so users can interact with your unique VR content in advance of the festival date. By downloading and then participating in your VR experience, the user earns a promotional code which they are able to bring to participating vendors and earn a discount on a Pepsi beverage. 

** Benefits: 
- Encourage interaction with your product as pre-promotion
- Generate excitement about your product and your VR experience
- Build association between your brand and the upcoming festival 
- Sell more products around the country

* On-Site VR Features:

This VR experience is designed to distinguish your brand from others that attempt to gain the attention of thousands of on-site festival-goers. In this experience, the user enters VR and arrives on the planet of Pepsi. Surrounded by a desert-like environment, the user then watches a Pepsi Can Band emerge from behind stage curtains. The Can Band is lacking a guitarist, and the user is conveniently there to fill the void. Receiving a ready-for-game guitar from an attendant, the user then selects the song they wish to play and hears the music in their headphones. Using a device similar to the famous guitar hero instrument, the user plays along with the song, matching as many notes as they can to the music they’re hearing in their headphones. Of all the users who interact with this VR experience across the 12 hours it’s on display, the one who matches up with the most notes achieves the high score and wins the opportunity to go backstage with the featured band. Additionally, each participant receives a promotional code via email or text message with which they’re able to purchase a discounted Pepsi beverage at any point throughout that day. 

** Benefits: 
- Draw attention to your brand at one of the most highly-attended festivals of the year
- Create truly unique content and become associated with this advanced technology 
- Merge your brand with the festival’s brand 
- Sell more products. 
