* XR Color

** Tagline 
Live in Color 

** Abstract
Currently, designers and developers create immersive worlds by working off a 2D screen. There lies a natural incoherence between tool and product. XR Color immerses human consciousness in a 3D color object and grants interaction with any color on the spectrum. 

** Choosing color 

Users can move three-dimensionally. Vertical movement alters lightness (polar north representing pure white and south pure black). Rotation around the polar axis adjusts hue. Altering horizontal depth changes saturation. Complementary colors are available at the reciprocal distance and angle from center. Any of the interactive options (optical focus, controller click, or a virtual wristband) may initiate interaction. As more designers and developers interact with color in 3D, richer and more color-coordinated content will result. Eventually, we'll experience a Virtual world resembling the color and texture of the physical world.

** Understanding Color: 

Although color is a foundational component of human sight, how and why our eyes perceive it is often misunderstood. Integrating this Virtual object with academic programs adds a tangible element to the relationship between student and study. Making XR Color available to the general public through VR app stores democratizes this form of immersive education and enhances our understanding of the human sense of sight. 

** Pleasure & Wellness

For close to a millennium, humans have practiced various forms of chromotherapy. In some cases, colors are portrayed onto varying body parts to increase blood flow and cleanse anatomical systems. Other methods of chromotherapy work by exposing the eye to specific colors for specific time intervals. XR Color is a new form of accessing chromotherapy.

The health benefits of XR Color span widely, elevating the computer programmer and graphic designer out of their chair - initiating movement, blood flow, and precise access to their paint.
 
