* XR Color
** Tagline 
Virtual Color Palet

** Abstract
Immerse digital artists inside a 3D color object and allow them active selection of any color on the spectrum

** Description

This program can be divided into three categories:

**** Choosing color 

Inside XR Color there are three dimensions in which the user can move. Vertical movement changes the lightness - the polar north of the sphere representing pure white and the polar south representing pure black. Through rotation around the polar axis, the user is able to adjust the hue. Altering depth through the center point changes saturation. Complementary colors are available at the reciprocal distance and angle from centerpoint. By reaching out and selecting a given color within the sphere, any color and it's complimentary form will instantly be within reach. A change in color may also take place based on the user's visual focus. 

***** Benefits: 

A tool for designers, artists, teachers, schools, architects to access color in the most complete way. 

**** Understanding Color: 

Color is embedded in every visual, yet most people have not had the opportunity to understand why or how our eyes perceive it. By presenting this 3D spectrum as an immersive and interactive experience, the average user innately becomes more educated about color and thus about their own sense of sight.

***** Benefits: 

More designers and developers will gain a deeper understanding of color, creating richer and more color-coordinated content for all technology users to experience. Eventually, this will lead to a Virtual World that can more closely resemble the color and texture of the physical world. 

**** Pleasure & Wellness of Color

For close to a millenium, chromotherapy has been practiced in various forms at various points throughout the world. In some cases colors are portrayed onto certain parts of the body to increase blood flow and cleanse the anatomical system. Other methods of chromotherapy are best received when the human eye perceives certain colors as a form of visual treatment. 

***** Benefits: 

As we step into XR color, we access an entirely new component of chromotherapy, as the user is now /surrounded/ by various colors from different hues, saturations, and forms of light. This opens the door for a new version of exploring chromotherapy in a way that hasn't previously been available. 

The 3D element of XR color also means designers and developers are up out of their chair, standing and moving around to select and experiment with color. The wellness and creative benefits of this energy exertion positively influence the health of people whose careers are based in computer-generated design and development. 
 
