* XR Color
** Tagline 
Live in Color 

** Abstract
Currently, designers and developers create immersive worlds off a 2D screen, a barrier between process and product. XR color immerses the human consciousness in a 3D color object and grants interaction with any color on the spectrum. 

**** Choosing color 

Users can move three-dimensionally. Vertical movement alters lightness (polar north representing pure white south pure black). Rotation around the polar axis adjusts hue. Altering horizontal depth changes saturation. Complementary colors are available at the reciprocal distance and angle from center. Any color and it's complimentary form are always within reach. Initiating color adjustments may occur in reaction to optical focus, controller clicks, or adjusting a virtual wristband.

***** Benefits: 

A tool for designers, artists, teachers, schools, architects to access color in the most complete way. 

**** Understanding Color: 

Color is embedded in every visual, yet most people have not had the opportunity to understand why or how our eyes perceive it. By presenting this 3D spectrum as an immersive and interactive experience, the average user innately becomes more educated about color and thus about their own sense of sight.

***** Benefits: 

More designers and developers will gain a deeper understanding of color, creating richer and more color-coordinated content for all technology users to experience. Eventually, this will lead to a Virtual World that can more closely resemble the color and texture of the physical world. 

**** Pleasure & Wellness of Color

For close to a millenium, chromotherapy has been practiced in various forms at various points throughout the world. In some cases colors are portrayed onto certain parts of the body to increase blood flow and cleanse the anatomical system. Other methods of chromotherapy are best received when the human eye perceives certain colors as a form of visual treatment. 

***** Benefits: 

As we step into XR color, we access an entirely new component of chromotherapy, as the user is now /surrounded/ by various colors from different hues, saturations, and forms of light. This opens the door for a new version of exploring chromotherapy in a way that hasn't previously been available. 

The 3D element of XR color also means designers and developers are up out of their chair, standing and moving around to select and experiment with color. The wellness and creative benefits of this energy exertion positively influence the health of people whose careers are based in computer-generated design and development. 
 
