* Design Brands 

Virtual and Augmented Reality are gradually becoming more prevalent in the world of design. Firms who've yet to adopt the technology have failed to realize an opportunity to powerfully communicate the essence of their brand.   

** Tell the story 
With the advent of the television screen last century, marketers, advertisers, and content creators developed captivating forms of holding and maintaining consumer attention. With talk shows, news programs, and commercials, forward thinking companies promoted their brand on this flickering screen that gradually became more ubiquitous in homes across the United States. Like the journalists, novelists, radio hosts, and billboard designers before them, television producers ushered in a new way to tell stories. 

** To promote their production process 
High-level interior design requires craftsmanship. This takes time. Pieces are custom-made for clients. More and more often they're built with up-cycled materials, environmental consciousness at the forefront of the creative process. These design pieces come from across the globe, created by the most sought after designers on the market. When such care is embedded in the creation of an object, the buyer deserves the full story, and now we're able to show these stories inside the immersive world of VR.   

** Reach a wider audience 
The most viable application of VR content for design studios and retailers is installing the hardware inside the showroom. Folks who come in off the street in neighborhoods like Manhattan's SoHo, have the chance to see, hear, and feel the backstory of a variety of the studio inventory by donning the VR headset. Wise businesses always have an eye on the future, and these are the companies that realize that the demographic of VR users is the next generation of high-end buyers. The 10 roughly million headsets in homes across the United States belong to men and women between the ages of 18 and 34 with an upper-middle class income level. Smart design firms are partnering with tech studios to devise clever ways of reaching this audience. The long term. 

** Connect emotionally with clientele 
Print, audio, and television can bring us tears, laughter, sadness, and anger. Yet consider the emotional distance between the human consciousness and the aforementioned devices. It takes practiced creativity and heightened sensitivity to feel emotionally connected with the words on a page, the sounds from a speaker, and the audio and visuals coming from the television screen. Interaction with VR eliminates these barriers, inviting the user into a new and immersive digital world. Elements like 3D audio, networked Virtual environments, and 360 viewing raise our heartbeat, dilate our eyes, increase perspiration on our skin. Virtual Reality is a heightened emotional platform. 

** Shed awareness on cultural diversity 
With brilliant designers living throughout the world, VR provides the opportunity to shed light on the cultural diversity of 21st century design. Visit Brazil, Taiwan, Sweden, Morocco and many other design outposts and journey inside an interactive 3D experience revealing the roots of today's most powerful design concepts. 

** How it was
 In 1951, eight million people owned televisions. Storytelling upon the platform was young and growing. In 2018, 10 million people own the highest caliber VR headsets, and designers are driving the stories inside. 
