* Design Brands in VR

Virtual and Augmented Reality are gradually becoming more prevalent in the world of design. Firms who've yet to adopt the technology have failed to realize an opportunity to powerfully communicate the essence of their brand.   

** Tell the story 
With the advent of the television screen last century, marketers, advertisers, and content creators developed captivating forms of holding and maintaining consumer attention. With talk shows, news programs, and commercials, forward thinking companies promoted their brand on this flickering screen that gradually became more ubiquitous in homes across the United States. Like the journalists, novelists, radio hosts, and billboard designers before them, television producers ushered in a new way to tell stories. 

** Promote the production process 
High-level interior design requires craftsmanship. This takes time. Pieces are custom-made for clients. More and more often they're built with up-cycled materials, environmental consciousness at the forefront of the creative process. These design pieces come from across the globe, created by the most sought after designers on the market. When such care is embedded in the creation of an object, the buyer deserves the full story, and now we're able to show these stories inside the immersive world of VR.   

** Reach a wider audience 
The most viable application of VR content for design studios and retailers is installation of the hardware on-site, inside the showrooms. Folks who come in off the street in neighborhoods like Manhattan's SoHo have the opportunity to wear the headset and experience the backstory of design inventory available in-store. Wise businesses always have an eye on the future. In the design world of the 21st century, companies are proving wisdom by promoting to today's demographic of VR users - the next generation of high-end buyers. The roughly 10 million headsets installed homes across the US belong to men and women between the ages of 18 and 34 with an upper-middle class income level. Smart design firms are partnering with tech studios to devise clever ways of reaching this audience. A long term play. 

** Connect emotionally with clientele 
Print, audio, and television can bring us tears, laughter, sadness, and anger. Yet consider the emotional distance between the human consciousness and the devices alluded to above. It takes practiced creativity and heightened sensitivity to feel emotionally connected to the words on a page, the sounds from a speaker, and the audio and visuals coming from the television screen. Interaction with VR eliminates these barriers, inviting the user into a new and immersive digital world. Elements like 3D audio, networked Virtual environments, and 360 viewing raise our heartbeat and increase perspiration on our skin. Virtual Reality is a heightened emotional platform. 

** Shed awareness on cultural diversity 
With brilliant designers living throughout the world, VR provides the opportunity to shed light on the cultural diversity of 21st century design. Visit Brazil, Taiwan, Sweden, Morocco and many other design outposts to journey inside an interactive 3D experience. Discover the roots of today's most powerful design concepts. 

** How it was
 In 1951, eight million people owned televisions. Storytelling upon the platform was young and growing. In 2018, 10 million people own the highest caliber VR headsets, and designers are driving the stories inside. 
