* Website Glossary 

- *Campaign*: The breadth of a project. From the time the idea is conceived to the final post-production. 

- *XR (Extended Reality)*: An expansive term inclusive of all digitally enhanced realities. Virtual, Augmented, and Mixed Reality being the foremost subsets. 

- *Deploy*: The act of delivering a finished product to its most appropriate place in the market. Putting the right message in front of the right people at the right time. 

- *Distribute*: Determining the channels through which the product or content will be deployed. A campaign may be distributed across a VR app store, on Web GL, via YouTube, etc. 

- *Game Engine*: A 3D space in which interactive digital experiences are built. It's the equivalent to the factory space in which an automobile is created. 

- *Booth Portal*: A physical-world architecture meant as a segway, creating continuity between the area in which the user dons the VR headset and the Virtual World they enter into. This is a marketing concept and typically manifests as a replica of place or object that exists inside the accompanying Virtual experience. 
 
- *VR*: Digitally immersive worlds created in a game engine and/or from 360 lens-captured content. In 2018 VR is accessible through head mounted displays. 

- *MR*: The result of superimposing real world lens-captured content into a VR world. 

- *AR*: The result of superimposing digital information on top of real-time human optical perception. AR is accessed through HMDs or handheld devices. 

- *HMD (Headed Mounted Displays)*: Varying pieces of hardware resembling goggles or glasses providing access to various forms of Extended Reality. 

- SOP: Standard operating procedure implemented by groups of individuals working together. These are processes meant to regulate workflow for maximizing quality and efficiency.  
...

MARKETING TITLES:

GOOGLE:

NOVA XR | Media Production: Dream Awake https://www.novamedia.nyc Nova XR provides access to advanced technologies and strategic development

Virtual / Augmented Reality: Architect virtual worlds, deploy 3D game engines and develop AR mobile applications

New Years Eve: Live in 360º VR from around the world - join the celebration!

Build XR: Free price quote and strategy by answering these 5 questions

Research: XR Financial Strategies, Marketing Evaluation, Persuasion Systems

==========

TWITTER

Nova XR Media - New York Production Studio Dream Awake | Your access throughout the revolution, renaissance and singularity. Learn how to design, build and distribute XR media content.

========

FACEBOOK

Nova XR Media - New York Production Studio

Dream Awake Your access to advanced media and strategic development. Learn how to design, build and distribute immersive content.

==============

BING

NOVA XR Media - Production Studio | Dream Awake

Nova XR creates VR software, customized and strategic.

New Year’s Eve: Live Global VR Stream - Join the celebration, pre-register for free

Infinite Art Gallery: Want to see your art in an infinite gallery? email us ;)

Answer the following five questions to get a price range, time table and next steps build your own extending reality

Blog: (latest title) and headline + beginning

About us: Who is Nova XR?

Successful Stories: Explore the world and live out your dreams. Go places you’ve never been. Now.

How to Begin: Build your own extensive reality experience concept in a matter of minutes. Get involved.

=========================

DUCKDUCKGO

NOVA XR. [Media Tech Production House] Dream Awake

...

We are open most days, all hours, by appointment. 481 Van Brunt, Brooklyn, New York, 11231

map : https://www.google.com/maps/search/xr+media/@40.658784,-74.0266566,12z/data=!3m1!4b1
[text box Message Submit ]

Email : AnnaIrene@novamedia.nyc
Telegram : https://t.me/xrnewyork
Instagram : @novaxrmedia
Facebook : https://www.facebook.com/N0vamedia/
Twitter : @N0vamedia
GoogleVoice : (732) 903-5537
slack : novamedianyc.slack.com
steemit : @novaxr
Sketchfab : /novamedianewyork
