* NYE TEXT

On New Year's Eve 2018, Nova XR Media produced a dual live broadcast in virtual reality. With one production team in Tel Aviv, Israel and another in Ramallah Palestine,we broadcast the first annual New Year's XR from either side of a conflict zone in the Middle East. 

With the most modern 360 live streaming hardware, we streamed live at 8K image quality for more than six hours. From 9PM - 3AM local time, we straddled the New Year, shed light on either side of a notorious border wall, and invited anyone in the world with an internet connection to tune in. Those with access to a VR were immersed in the sights and sounds of the Arafat Square in Ramallah and Old Jaffa in Tel Aviv. Folks viewing on a computer screen viewed through YouTube's 360 feature. 

In 2019, we are expanding New Year's XR to 10 cities. From a marketing perspective it is a new opportunity to showcase your destination. We have not yet decided broadcast locations and are accepting applications from tourism boards through the second quarter of 2019. 
