This is the website architecture and all the web text for novamedia.nyc to be launched Sunday, October 28. 

KK/JB met for one hour on Tuesday afternoon. After the hacking of the website, Nova needed to deal with tech debt on the backend. During this time the website has been offline. While working through the tech debt, about 80% of the webtext was lost. 

Rather than repasting all the webtext into the admin page, JB/KK decided to trim the website down. To summarize this decision, we are leaving 3 left panel options, and the subsequent dropdown options beneath them. Now, when clicking on one of these subsequent dropdown options (example: “Consultation”), the user will no longer see three tabs available across the top of the right panel. Instead, the “Consultation” text entirety of the consultation text will appear right there on the right side of the screen.

There exceptions to this modification 

1) The format of the products page will remain the same as before with rectangles appearing upon the right panel and the user with the option to click on each rectangle (product) to read further. 
2) The publications page will remain divided by three tabs across the the top. These will read: 
- *Technologies*
- *Industry Insider*
- *Use Cases*

We will source all of the most valued and well-written pages from the pre-hacked website (Game Engine, C#, Crossing the Chasm, Google Earth, Financial Strategies, etc.) and divide them among the three subheadings listed above. When clicking on one of the subheadings within “Publications” the user will arrive at a page with rectangles running along the right panel. A click will bring them to the full article. 

3) The subdivision of “Nova XR” will change slightly. Here are the new subcategories 
- *Who We Are:* This will include “About Us” and “Find Us”
- *Partnership:* This will feature a full-body text describing Nova’s philosophy (highly centered on Partnerships). 
- *Productions:* This will feature a right panel listing of all our clients 

JB/KK agree that “Contacts” (which is currently inside the “About Us” tab and lists various means of connecting with Nova) features too many means of connection and the table appears a bit unprofessional. This table should be designed by JB. 

JB is working with TB to finalize relaunch

================================ WEB TEXT BEGINS ON NEXT LINE
* Home 
Nova XR Media is a team of artists and engineers. We design and build Virtual and Augmented Reality. 

* Build XR 
Build XR page intro text: Extended Reality may provide a variety of solutions across a range of industries. By answering these five questions, you provide us with tools for applying XR to your needs. Marketing, training, and internal productivity begin to outline the scope of XR applications.

*** Why build XR? 
*** Who is the audience? 
*** What industry?  
*** What problem needs to be solved? 
*** What is the Budget
- 4 figure 
- 5 figures 
- 6 figures

*** Describe your idea
*** Contact information

*** Submission Text

Thanks for taking the first step toward building your XR solution! We'll apply your responses to the next step in our consultation. 

* Solutions 

** Products 

*** Intro 

Through consistent experimentation, research, and a desire to solve real problems we have created these original Virtual Reality products.

*** New Year's Eve 
/Live Stream VR From Around the World/

## Abstract

By setting up 360 cameras in 10 of the most iconic locations, we’re live streaming from around the world for 36 consecutive hours. Travel from down under, to Dubai, through the old world, and all the way to North America, experiencing the sights and sounds of New Year's Eve in the most thrilling locations. Anyone with an internet connection can participate. 

## *Display Your Brand*

Users can travel with friends, meet new people along the way, or go it alone. Beyond the raw sights and sounds from the 360 video stream, anything about the experience can be sponsored. We could build a customized style of transportation or incorporate brand visibility with retail products placed throughout the XR experience. 

## *User Experience* 

Begin in your branded lobby, the Virtual globe at center. Click it, move it, rotate it, and select among marked locations. Travel stylishly and arrive among the people. Listen to the sounds; explore the town. Stay a while or return to the lobby to explore another celebration.

## *Broadcast* 

Destinations working to attract visitors may display their culture, infrastructure, and appearance - shedding light in a brand new way. Virtual Teleportation shows the glamour of your destination. Make global use of VR’s live potential.

*** XR Architecture 
/Sketch, Measure, and Build/

## Abstract 

Before infrastructure reaches the physical world it is crafted on a 2D screen - an inexact tool. VR is an intermediate space between digital and physical. The architect steps inside his 3D structure to refine its precision.

## *Increase Certainty* 

In Virtual Space, architects inspect the relationship between the geometrical dynamics of a structure and it's environment. Traffic flow, pedestrian movement, sunlight, and rainfall are among the variables to be evaluated from inside an environment replica. 

## *Expand Potential* 

!!! Today, more architects are gaining access to computer aided design (CAD) and computer aided manufacturing (CAM). These programs introduce a new language of forms and shapes too complex for the human brain to project and visualize. Virtual Reality is the technology enabling the mind to comprehend this imagery.

## *The Buyer*

Receives multiple architectural proposals for major construction projects. When receiving a submission in Virtual Reality, the investor, often local government, makes a more informed decision from inside the Virtual Model.       

## *Financial Efficiency*
 
Architecture is a spatial discipline that's at home in the Virtual World. Inviting architects into VR increases the precision of their calculations and the sensitivity of their design. It's a tool for maximizing efficiency of major construction projects before they break ground in our towns and cities.

*** Infinite Gallery 
/Virtual Product Display/

## Abstract 

As content creators transition to VR they’re met with the challenge of presentation. The Infinite Gallery, our original VR interface, is built to display content linearly. It’s step one in creating customized Virtual architecture.

## *Welcome Inside*

The experience begins in a space custom-designed for content display. A finger against the VR touchpad initiates movement. Remove your finger to stop moving. Continue like this to navigate the entire architectural structure. Just as in the real world, users can move their head to access 360-degree viewing.

## *What to Display*

Capable of hosting an unlimited content library, The Infinite Gallery is prepared for original display ideas. Hang products on the wall, show content behind glass window panes, create doorways to varying dimensions, or build the second floor of your company’s customized structure.

## *In Business*

This interface is immediately applicable for basic 3D marketing. Regardless of file type, any visual content ports to The Infinite Gallery. Photographers displaying in 3D, galleries scaling beyond a physical location, and 3D artists creating VR-ready content from scratch are among early adopters.

## *Provide Access*

At the beginning of the 20th century, F.W. Woolworth altered retail marketing. Before the advent of his “Five and Dime” drugstores, the customer requested a product, the clerk retrieved it, and the transaction took place. Woolworth was the first to display drugstore products on publicly accessible shelves, initiating a physical and emotional connection between goods and customers. 100 years later it remains a global display standard in retail.

## *Show Your Story*

The Infinite Gallery is a linear display interface in 3D. Upon reaching the end of your story, the user has connected with your brand.

*** Torus
/Virtual World Mobility/

## Abstract

The early days of Virtual Reality revealed a flaw in user experience. Like a computer without a mouse, Virtual Reality without the Torus is difficult to navigate. Inspired by VR’s fully immersive nature, we developed the Torus to reflect real world energy flow.

## *Making Nature Virtual*

Energy flows in the same manner at all universal scales. Known scientifically as toroidal flow, it’s the energetic movement that powers our planet. Similar to the way light colors our vision, toroidal energy drives our perception of movement.

!!! To maximize Virtual Reality’s function as a tool for enhancing real world experience, we’ve integrated this energetic flow into immersive technology, enabling intuitive mobility.

## *Applying The Torus*

Once the Torus surrounds the user, information emerges in two locations. By glancing above eye level, content appears similarly to a computer screen’s top bar. Glance down to access the bottom bar. Both information sources slide, change, and refresh in reaction to eye movement, controller commands, or interaction with a virtual wristband. Customize the Torus however you choose. Once information is selected, the featured content appears at a comfortable viewing angle within the user’s vantage point.

## *Maximizing The Torus*

Considering the omnipresence of toroidal flow in the physical world, it’s a challenge to narrow down the Torus’ applications in Virtual Reality. The most effective VR content promotes mobility and interactivity, and the Torus is designed to facilitate these functions in all cases.

The Torus is the foundational tool we’ll use to build your customized VR content.

*** XR Color 
/Live In Color/

## Abstract

Currently, designers and developers create immersive worlds by working off a 2D screen. There lies a natural incoherence between tool and product. XR Color immerses human consciousness in a 3D color object and grants interaction with any color on the spectrum.

## *Choosing color*

Users can move three-dimensionally. Vertical movement alters lightness (polar north representing pure white and south pure black). Rotation around the polar axis adjusts hue. Altering horizontal depth changes saturation. Complementary colors are available at the reciprocal distance and angle from center. Any of the interactive options (optical focus, controller click, or a virtual wristband) may initiate interaction.

!!! As more designers and developers interact with color in 3D, richer and more color-coordinated content will result. Eventually, we’ll experience a Virtual world resembling the color and texture of the physical world.

## *Understanding Color*

Although color is a foundational component of human sight, how and why our eyes perceive it is often misunderstood. Integrating this Virtual object with academic programs adds a tangible element to the relationship between student and study. Making XR Color available to the general public through VR app stores democratizes this form of immersive education and enhances our understanding of the human sense of sight.

## *Pleasure & Wellness*

For close to a millennium, humans have practiced various forms of chromotherapy. In some cases, colors are portrayed onto varying body parts to increase blood flow and cleanse anatomical systems. Other methods of chromotherapy work by exposing the eye to specific colors for specific time intervals. XR Color is a new form of accessing chromotherapy.

The health benefits of XR Color span widely, elevating the computer programmer and graphic designer out of their chair - initiating movement, blood flow, and precise access to their paint.

*** Bloomaway 
/Seamless Virtual Transport/

## Abstract 

When users first enter Virtual Reality they often need instructions on how to navigate their new digital surrounds, so we created Bloomaway. It’s seamless virtual navigation powered by user intuition.

## *Seamless* 

!!! Bloomaway smooths the transition into VR. By eliminating controllers, this internally developed software responds to manual action and optical focus, empowering users to dictate destination and pace of movement. 

## *Virtual* 

Dizziness in VR results from scene shifts within user vantage point. Bloomaway solves by loading environment transitions outside the user's sightline. See the map, touch the destination, turn 180 degrees, and you've arrived. Dreamscape across nations and overseas with touch and sight.

## *Transport* 

Bloomaway reduces business travel expenses (like those associated with employee relocation) by displaying properties, schools, car dealerships, city buildings, and providing general area orientation in VR. While some experiences cannot be replicated by Virtual Reality, others merge with it to reduce travel demands and maximize efficiency. Bloomaway ports destinations into VR and brings you to them.

...

** Consultation 

## Rectangle Intro 

People of every industry are finding solutions to their most stubborn challenges by producing immersive (XR) media content. Share, communicate, and learn in XR. 

## Full Text

Virtual Reality (VR) and Augmented Reality (AR), fitting under the parent term "Extended Reality", enhance communication, collaboration, and education. Unlike its predecessors, XR Media is interactive, calling on the user to embody their consciousness.

These technologies will increasingly be in the home, integrating with daily living in the way televisions, computers, and phones already have. As of today, you can engage with simulated environments through your phone (or XR glasses/goggles).

Historical rates of technological adoption suggest that 25% of the people living in the US will have AR/VR in their homes within the next five years. It is the next frontier of human connectivity.

In business, XR Media cuts internal costs by providing immersive training programs and business travel alternatives. When used to drive revenue, XR is a natural marketing tool, the backdrop for new age content creation.

XR Media can be the ultimate communication tool or the reason your business falls behind.

...

** Publications 

## Rectangle Intro 

These publications are to help you better understand the details of Extended Reality. They analyze the technologies used, the state of the XR market, and the path to a return on investment.

*** Technologies 

**** 3D Audio
(Also referred to as binaural audio) is a technology that presents sound to the human ears in a manner resembling the auditory qualities interpreted from the natural world.

Stereoscopic playback systems (headphones and speakers) emit sound from a single point in space. When you move your head while wearing headphones, the sounds move with you. Yet when you move your head in relation to sounds of the natural world, the location of the sound source remains fixed. In the case of stationary speakers, the sound remains fixed but unidimensional.

Without technology, human ears perceive sounds from an infinite number of sources and locations simultaneously. Because the ears are positioned on different sides of the head, sound waves reach one ear at a slightly different time and with slightly different properties than when they reach the other ear. Much like having two eyes enhances our ability to see in three dimensions, the same is true for the human auditory system. Amplitude, frequency, and timing differences reveal to our ears the specific location of a sound, which direction it’s coming from, and even the properties of the space in which it’s being heard. The most pivotal factors relating to this dynamic auditory perception are the physical properties of the human ear. It’s oval shape with varying coves, curves, and suppleness all contribute to the way it receives sound waves and the way the brain interprets sound.

In order to recreate this sound interpretation with modern technology, VR studios are capturing sound with microphones that resemble the shape of the human ear. These mics record sound not through a flat or circular device but with respect to the natural contours of the ear. When the recorded sounds are played back, they’re more dynamic. They’ve been enriched by the same intricacies as the organ that receives and delivers them to the brain. When hearing 3D audio through a pair of headphones, the various sounds may seem to crawl from one ear to the other, come from 10 feet in front of you, or bleed in from a distance.

This the technology is not a new realization. Through the 20th century (and most of the 21st thus far) there has not been a demand for 3D audio, as visual content has been almost exclusively 2D. The emergence of 3D imaging in Virtual Reality is now calling for sound technology equally as dynamic.

**** 3D Game Engines 

A game engine is the software environment where computer developers build interactive 3D experiences. Game engines combine three elements: graphics, audio, and logic. Think of them akin to the factory in which a vehicle is constructed — where all the necessary space, tools, and engineering platforms exist. In the current Virtual Reality climate, most developers choose between the two most powerful game engines.

## Unity

Unity supports the construction of both 2D and 3D experiences for computers, consoles, and mobile devices. It was first revealed at Apple’s Worldwide Developer’s conference in 2005. Since then, five major versions of it have been released and more than 100 of the most well-respected experiences in the gaming industry have been created inside.

Unity is now free for download, making it more accessible for anyone in the world to gain access to high-end VR development tools. This has been huge step in the growing ecosystem of VR coders across the globe.

While there are features available for non-coders, understanding how to read and write in one of Unity’s supported programming languages is the ticket to maximizing its potential. Unity supports three programming languages, yet C# (Cee Sharp) is preferred by most professional developers. C# is an object-oriented language, making it compatible with the three-dimensional relationship among objects in this Virtual Space.

A new feature released in Unity this year is enhanced texturing, allowing developers to create more detailed replicas of complex physical world objects. The surface of a rock, for instance, with its infinite nuances, is difficult to replicate. Unity’s new texturing feature allows developers to create more life-like visuals of such complex surface.

## Unreal

The decision of which game engine to use coincides with the creator’s existing skills. Are they a coder or a designer? As a coder, the creator will write in one of the languages supported by the game engine. Unreal supports a language called C++.

While it’s not always the case, coders may be more likely to work in Unity while designers may gravitate toward Unreal’s “visual programming.” Instead of writing scripts, the designer places modules in an open area within the software interface.

Regardless of the game engine in use, creators work within many “frameworks” built into the engine. During the creation of the 3D experience, the creator may want to generate a similar (or even identical) outcome at various points throughout the experience. Perhaps the user’s movement should lead to the same outcome regardless whether they’re in Virtual New York city or Virtual San Francisco. Building frameworks is like building bridges. Once the bridge has been constructed and finalized, traversing that body of water in the future becomes standardized, saving time and energy.

Access to these frameworks is one of the great appeals to industry-leading game engines like Unreal. However, there are cases when the developer may want the flexibility to work outside such parameters or even build their own frameworks. Understanding this, Unreal makes all of its source code (the lines of code written to build the game engine itself) available to subscribers. With this access, the community of Unreal developers has created documentation to help other coders work through the inevitable hurdles of programming in Unreal.

**** Physics Engine

## Laws of the Virtual World

A physics engine allows us to construct the physical laws of an XR experiences. The behavior of light, rain, the laws of gravity, and the relationship among objects are all programmable in a physics engine. 

Many virtual environments are centered on the movement of human avatars. We must build their virtual capabilities and restrictions. When constructing an environment of virtual football players, for example, we assign certain properties to each player. X player weighs Y pounds and has the ability to jump Z height. 

For many virtual creators, it's important that the constructed environment abides by basic real-world parameters. For example, when the user approaches a wall in a virtual space, the physics engine is the tool used to determine whether the user collides with the wall or passes directly through it. 

"Unity" supports the most dynamic physics engine.

**** Python

# Machine Learning Language 

Python is a succinct, object oriented programming language. It's scripting capabilities allow programmers to design visual assets by writing lines of code into a game engine like Blender. Not only can we generate shapes with python but we can also manipulate, scale, and put them into motion.

This is the default language of the machine learning world. While machine learning toolboxes are written in C++ (for performance benefits), we often use python as the intermediary tool to access these stores. In this way, it functions as a librarian who retrieves a book from the stacks and delivers it to the reader. Combining these languages blends the succinctness of python with the high performance of C++.

In the VR world, python is a tool that provides access and adds efficiency to game engine development.

**** C-Sharp 

## Object Orientation

This is one of the programming languages compatible with Unity (the most commonly used VR game engine).

Among its most beneficial characteristics is its portability. Regardless of whether the programmer is using Linux, Mac, or Windows, the C# syntax remains consistent. This is also an oriented programming language that's compatible with a .net backend. If the goal of your XR build is to integrate with your existing internal software solutions hosted on a .net, C# may be the most appropriate language for this work.

It's an object-oriented programming language, making it a valuable resource for building interactive VR experiences. Historically, programming has been understood as a logical procedure for performing an action - taking input data, processing it, and producing an output.

At its origin, the essence of programming has been writing the logic rather than defining the data. By contrast, object oriented programming is rooted in the belief that what we really care about are the objects we want to manipulate rather than the logic required to manipulate them. An "object" could be anything from a human being to a building to widgets of a web page.

VR is based on the creation of such objects, and C# is the object-oriented programming language driving much of the VR world.

**** AI

# Artificial Intelligence 

It's a wide-ranging term for intelligence demonstrated by a machine. The branch of computer sciences that studies AI research studies and develops machines that are designed to mimic "cognitive" functions associated with human minds, like "comprehension", or "deductive reasoning".

## Content

Artificial Agents enhances VR through 
- Personalization 
- Generative design
- Contextual awareness
- Storefront Navigation 
- Data indexing
- Character engines

## Personalization

Personalization is when a computer remembers your preferences and automatically loads them PLUS some other new ideas it predicts you will like. This is done through probability models, also known as an /AI algorithm/ or some other hype name.

In VR you are led to experiences you are likely to enjoy. Your space is tailored to your taste. Because of AI, the world works according to your preferences.  

By delivering a highly personal experience, we increase game-play, engagement, and retention. AI accelerates the rate of learning.   

## Generative design

Generative design is creation by a computer, based on data. By feeding big data into an AI we can generate designs humans may not have conceived. With proper programming, you can enlist the requirements for a airplane, request certain fuel intake and other variables, and receive a menu of physically possible designs.  

In Virtual Reality, we generate worlds based on game-play and experiences. Generative design is an upfront cost that pays dividends long after it's investment has been returned. There is no limit to how many world designs you generate, and the parameters are within you control. 

## Contextual awareness

*Contextual awareness* allows the machine to compare the query to known information.  For example, google maps knows your location. If you press the blue dot (ask where you are), it compares this request to its knowledge of the map. The computer has a small degree of contextual awareness.   

In Virtual reality When a AI character knows it's surroundings it will play more thoughtfully, making for better competition/collaboration and game play. AI characters train through trial and error. They record the context of the successes and failures and adjust to optimize likelihood for success.   

## Storefront navigation

At the front of a store, or in a virtual world, you will ask an AI "butler" or "host" for information about the local area. These bots will grow more and more expert in communicating with patrons and visitors. Think about friendly chatbots on a website but personified as a character.

## Data indexing

Artificial intelligence algorithms to better index user data. If information is better categorized it will be better read and understood. We'll comprehend larger and large sums of data, especially very intimate information VR can facilitate, such as body movements and emotional states.  

A semi-technical explanation of the process is to track, collate, distill and visualize.

By visualizing the data of VR players through indexing, we gain a complete understanding the user's experience. The AI creates visuals of complete data in 3D, so you can move around and scale the data in real-size. This engagement significantly increases comprehension.  

## Character engines

In Virtual Reality (XR) develops "character engines" into the experience. These enhance the characters behavior and decision making. By programming learning algorithms your characters can remember information about you, your game play, and whatever else we teach it to...within reason. They can be your virtual friends.

Intelligent characters make for better game play. The user's experience is familiar and personalized. When you allow visitors to customize their environment, they feel ownership. Intelligent characters increase experience affinity and replay-value.

**** Web GL

Web GL is a means of displaying immersive content through a web browser. This drastically expands the XR user base, allowing anyone in the world with an internet connection to view XR content through a computer, smartphone, or tablet. With high-end VR headsets having reached about 15 million homes, deploying content through Web GL bridges a massive accessibility gap.

Affording accessibility costs imaging quality. For instance, Web GL content will generate a lower quality imagine than content build in a game engine. In order to program physical properties into a Web GL Virtual environment, the development team must work with a Java Script framework (Called THREE.js), affording access to ertain C++ functions. Because it's the web browser that allows this access, the process must pass through a security "sandbox." These are all elements of the world build that are available within high powered game engines. Inclusion of the aforementioned extensions saps speed and performance.  

If maximum accessibility is the most important aspect of your XR build, we'll advise Web GL. In most other cases, it's wises to build in a game engine.

**** C#

This is a Microsoft language. Among its most beneficial characteristics is its portability. Regardless of whether the programmer is using Linux, Mac, or Windows, the C# syntax remains consistent. This is also an oriented programming language that's compatible with a .net backend. If the goal of your XR build is to integrate with your existing internal software solutions hosted on a .net, C# may be the most appropriate language for this work.  

**** Explore The World In VR, Really 

Virtual Reality as a home entertainment option is of the future. Yes VR is being used right now across various industries and solving problems for some business who are forward thinking enough to implement it, yet fewer than 10 million people have the most advanced VR hardware in their home. As a result, the content available on VR systems is thin and underfunded. That said, there is one VR experience that’s completely exhilarating. Actually, It’s the family member of a program that many of us now use and rely on every day (and in some cases every time we leave the house).

Google maps puts the entire world on a phone screen and helps us travel anywhere we want. Google Earth makes the world big again. It’s an immersive and more visually realistic version of Google maps available in a VR headset. In Google Earth you can fly above the world, descend on your destination, and move through city streets anywhere on our planet.

The images are gathered by satellites and airplane cameras. With multiple lenses and varying angles, Google has captured all 196.9 million square miles of the globe, arranging the images together through a process called photogrammetry to create a digitally immersive replica of the earth. The number of photos that make up the program is “in the order of 10s of millions” and the globe is shown to us as an 800 billion pixel image (if this many pixels were printed on a physical object, it would fit across an entire city block).

Graphicists working in a game engine photo edit the images to remove shadows, clouds, and in some cases objects that may impede our clear view of the earth. Once the photos are arranged properly (not out of order) objects like trees, buildings, and bridges are stitched together through a software called “mesh.” This transforms them from flat images into 3D models that sprout from the earth’s surface.

It’s all created to scale and inside a digitally immersive world. By pressing the buttons of the VR controls you move like a drone. You can view the earth as though you’re standing on the moon, zoom all the way in to the mailbox in front of your house, or stop anywhere in between.

By updating some of the images multiple times per year, Google is able to look back at the data — across the program’s 10-year lifespan — and notice changes in forestation, human foot and auto traffic, and use heat maps to evaluate variation in temperature patterns across the world.

It may be the only VR experience we’ll never fully explore.

**** Scale Beyond You OS

Spatial OS is a cloud-based platform that hosts collaborative applications built by game developers. It was created to expand beyond the limits of a single server. It’s a distributed operating system with the power to host massive simulations thousands of times bigger and more powerful than what a single computer is capable of building or hosting.

Developers log on and interact with it as an online platform, downloading tools that can be integrated with game engines like Unity and Unreal. Once the world has been built on the developer’s local operating system, the application is packaged and pushed to Spatial OS. With the code hosted and available to other developers on the cloud, it can be grown to massive scales.

Think of the content that exists in Spatial OS to have similar properties and functionalities as the physical world. Users log on and travel to these simulated worlds. However, unlike games and worlds that exist on your home computer or gaming system, Virtual simulations hosted on Spatial OS exist and evolve even when you’re not logged in. As with the real world outside — let’s say on the street outside your house — if a tree falls or a new car parks along the curb while you’re asleep, that new information is available to you when you walk outside the next morning. The same principle applies when you return to a world hosted on Spatial OS.

Massive projects like public transportation construction or renovation in major cities can be first simulated to scale in Spatial OS before being applied in the physical world.

Check out this video featuring the CEO of the company who created it. 

https://www.youtube.com/watch?v=cn00UKfYaaU

**** Internet of Things 

The Internet of things (IoT) is the network of digitally connected devices, such as home appliances and vehicles, that are connected to the internet. These devices are equipped with sensors and operating software, enabling remote access and management. For example, adjusting your beach house thermostat from upstate, or receiving a text message notifying you the plants need watering (because your botany sensors noticed drought).

Simulations of physical tasks allow for us to practice, minimize risks, and scale profit margins. Imagine remotely controlling construction machinery. By being in the simulation, apprentices can train without the risk of hurting themselves. Experts can control machines remotely and thus down on transportation costs. Through VR simulation one can navigate the controls to operate an actual piece of machinery just as effectively as if he were in the machine itself, but from the other side of the world. This is the “internet of things”, which will quickly evolving into the “Internet of Everything” (IoE) and then the “Internet of Humans” (IoH).

*** Industry Insider 

**** Apple In XR...The Missing Giant 

In an interview last year, Vitalik Buterin (creator of Etherum) was asked, “How would you describe Etherium to the average person?” His answer: “There are two kinds of average people, the average person who has heard of Bitcoin and the average person who hasn’t.”

When considering the evolution of Virtual Reality, the division feels more related to a moment in time. There was the Virtual Reality before Facebook bought Oculus in 2014 and there is Virtual Reality since that 3 billion dollar investment.

“Before [the acquisition] there were a few companies that believed in VR. And when I say a few, I mean a few,” Palmer Luckey (founder of Oculus) told Re/code in 2016. “After that [acquisition] happened, I think it was a signal to the rest of the industry that VR was here. This is gonna be a huge thing and if you didn’t invest in VR now you were gonna get your ass kicked down the line. That’s how you wake the giants.”

The Giants.

Since 2014, Google, Microsoft, Sony, and HTC have all either upped their investment or joined the VR movement. Yet there’s one giant who has remained on the periphery, and with the Extended Reality industry still humming in the aftermath of the new Magic Leap headset and the 5th installment of the Oculus Connect conference in California, we’re asking…is there another giant ready to augment the XR world?

This month Apple released the next iPhone: Iphone XR.

For the past few years (since the Facebook/Oculus marriage) XR has been the all-encompassing term for referencing Virtual, Augmented and Mixed Reality. The collective definition for “XR”: technologies that add digital enhancement to our visual perception through the use of head-mounted displays.

Before the September 12 Iphone XR announcement, an “XR” Google search yielded companies, websites, and publishings centered on “Extended Reality.”

Since then, an “XR” search brings a stream of Apple content.

Unlike the other giants, Apple is not publicly invested in the development of Virtual Reality. The infamous “MacRumors” website has maintained for months that “Apple is rumored to have a secret team of hundreds of employees working on virtual and augmented reality projects.”

What we do know is they are heavy involvement in Augmented Reality (the use of goggles to digitally overlay information onto our visual perception of the physical world). Although the Cupertino giant hasn’t yet released their own AR hardware, they have become one of the leaders in consumer-level AR software with their easy-to-use AR Kit.

Here’s a breakdown of Apple’s XR activity.

## AR Kit

The AR kit has been available on multiple devices since IOS 11 released last fall. The applications range from visualizing Ikea furniture in your own living room to a guided map of an American Airlines terminal at flight time to the anatomy of the human body. So, Apple is creating XR software, yet, unlike the other giants, they haven’t released a piece of hardware.

## AR glasses

…There are reports of a coming release. Check out this recent job listing where Apple is seeking to hire a 3D user interface engineer to “drive the next generation of interactive experiences for our platform. You will work with some of Apple’s most advanced technologies including the Augmented Reality (AR) and Virtual Reality (VR) support offered in ARKit and Metal 2.”

## Reports

An earlier report suggested Apple could release AR glasses by 2020. Apple’s headset could feature an 8K display for each eye, offering a more realistic experience. Apple may be waiting for display and chip technologies to mature before releasing its headset. A previously uncovered Apple patent revealed that the company is investigating AR lens technology. Apple’s research calls for a compact lens array to help focus light and eliminate chromatic aberration effects.

Unlike some current AR and VR solutions on the market today, Apple’s implementation will reportedly not need trackers or cameras.

“We have been and continue to invest a lot in this,” Apple CEO Tim Cook said in a 2016 interview when asked about the technology. “We are high on AR for the long run, we think there’s great things for customers and a great commercial opportunity.”

Apple AR glasses may be part of this investment. According to a growing number of rumors leaked by three alleged Foxconn employees, the internal development is apparently known as Project Mirrorshades.

## Apple XR Patent

Apple also has a registered patent for the use multiple lenses to achieve the same effect as larger headsets, arranging them into what is known as the “catadioptric optical system.” More commonly seen in telescopes, this arrangement is a compact way to focus light, and helps to eliminate the colors that can sometimes be seen on the edges of your vision in VR or AR — or “chromatic aberration.”

The XR movement has been on the rise for decades. It got louder in 2014 as Facebook single-handedly accelerated the industry. It feels a bit peculiar that Apple has not been a front man in the XR world, unless they are operating on the other side of the curtain.

## Resources

https://www.apple.com/ios/augmented-reality/

https://www.digitaltrends.com/computing/apple-hiring-engineer-for-ar-glasses/

https://www.digitaltrends.com/computing/apple-ar-vr-mixed-reality-headset-may-arrive-in-2020/

http://pdfaiw.uspto.gov/.aiw?PageNum=0&docid=20180039052&IDKey=2B39F82750D2&HomeUrl=http%3A%2F%2Fappft.uspto.gov%2Fnetacgi%2Fnph-Parser%3FSect1%3DPTO2%2526Sect2%3DHITOFF%2526u%3D%25252Fnetahtml%25252FPTO%25252Fsearch-adv.html%2526r%3D27%2526p%3D1%2526f%3DG%2526l%3D50%2526d%3DPG01%2526S1%3D%2820180208.PD.%252BAND%252Bapple.AANM.%29%2526OS%3Dpd%2F20180208%252Band%252Baanm%2Fapple%2526RS%3D%28PD%2F20180208%252BAND%252BAANM%2Fapple%29

**** The Next Spielberg In VR

From the outside Virtual Reality must seem…so far in there. So far into this digital world that’s become part of us all. From the outside VR must fall somewhere among time travel and an embodied internet. In other words, somewhere in the future. In the big cities you’ve heard about VR or have a friend who does “something with VR.”

But the future has become a tough concept to pinpoint. The idealist hears autonomous vehicles on the road, Alexa speaking back to him, and conversations about human colonies on Mars, yet the pragmatist knows Uber got suspended from testing autonomous vehicles in Arizona after a fatal crash last month, speaking to Alexa is sometimes like speaking to a 3-year-old, and there are no plans to put a human being inside a spacecraft (let alone establish a society on a planet that would take several years to reach).

Virtual Reality is right in the middle of this search for the ground between human imagination and human capability. Google’s two most ubiquitous VR programs: Tiltbrush (in which you draw and paint inside a three-dimensional space) and Google Earth (in which you walk the streets of any city in the world) provide a taste of how vast this technology will become. In these early programs you begin to understand how we’ll one day educate children with this tech, test architectural structures before building them in the physical world, and reunite with deceased family members. The ideas are real, yet realizing them still feels off in one of those years that doesn’t yet read like a year — somewhere like 2045.

On the inside of this industry we’ve speculated about what needs to happen in order to move this tech to the forefront. We’ve worked to help it shed the stigma of being the next gaming home for 17-year-old techies who stay up all night firing first-person shooters. On the inside we’ve seen firsthand VR as a catalyst for human interaction, education, and global exploration. It has become our work to make all this imagining attainable.

So what does need to happen? Well, some of the wheels are already in motion. Even before Facebook, Google, and Microsoft invested heavily in VR, there was a writer. Ernest Cline. He was 38 when Crown Publishing printed his first novel, “Ready Player One.” The next day Warner Bros. bought the rights to convert the script into a film, hiring Cline to co-write the screenplay. Nearly a decade later, the movie has arrived in theaters, directed by the most famous name in film — Spielberg.

The story begins in the year 2045 when — resulting from global warming and the depletion of fossil fuels — the world is mired in an energy crisis. The OASIS is where many folks go to escape their decimated surroundings. It’s a Virtual World accessible with a visor and enhanced with haptic technology. In the opening pages of the novel, the richest man in the world — James Holiday — has passed away, leaving behind a video message. He announces to the public that he’s hidden a golden egg inside OASIS, and the first person to discover it will inherit his wealth. Teenager Wade Watts is the main character.

It arrived in theaters on March 29 and grossed roughly $50 million on its opening weekend (only Black Panther and A Quiet Place grossed more on opening weekends this year). By the end of its third weekend Ready Player One earned a combined domestic/international gross of nearly half a billion dollars, making it one of the top 10 grossing Spielberg productions since we learned his name in the summer of 1975, with Jaws.

Ready Player One (the film), an action/thriller, is not meant to update the public on the current state of VR. So…the industry isn’t wealthy enough to attract the most highly trained coders and push the cutting edge of computer science. Secondly, just like the futuristic industries mentioned at the top, we don’t yet understand how this will influence the human mind. Remember, this is a technology predicated on immersing people in a digital world. What happens when human eyes perceive a new reality, when movement of your arms and legs pushes you deeper into a manmade environment? What influence does it have on the brain, the psyche, and our perception of reality?

It’s not the first time technology and storytelling have come together to influence the mind. While we’re on the topic, let’s take a look back at Spielberg, who — as a 29-year-old director in 1975 — created a new world and called it Amity Island, the setting of Jaws. He brought viewers to another place and with it ushered The New Hollywood Era. I remember waking up in the middle of the night screaming for my sister to get out of the water. The anticipation of the shark’s arrival, the terror among the people on Amity Island, the sound of the bloody ocean, and the feeling of raw danger circling me. It created an affect on the human brain. And we’re talking before computer graphics. When the shark was mechanical, the film schedule shot according to the Cape Cod tides, and the music there as a warning.

Considering that, it seems fitting that Spielberg has now helped move the needle forward on the next version of immersive storytelling. We’re a long way from this Virtual space being a refuge from a fossil-fuel-depleted world, but we rarely turn to Spielberg for practicality. We often turn to him for imagination. The question is so tangible that it’s become tantalizing…what is possible in Virtual Reality? If not a new world to rescue us from global warming, then…?

For hundreds of years we’ve asked the writers, the directors, the creators to show us their vision and help provide insight to these very questions. So consider for a moment that two of the most commercialized storytellers in action today — Ernest Cline and Steven Spielberg — are not storytelling in VR. They are storytelling about VR. Until that changes, Virtual Reality stays in 2045.

**** Back From The Olympics

A lot more people have asked about VR over the last couple of weeks, mentioning they “heard something about it” on the Olympic coverage but didn’t know exactly how it had been used.

Because fewer than 10 million people have purchased VR headsets, awareness of the technology and its programming is limited. So I’m going to use a page or two here to help you understand what the Olympics did with VR headsets and, more importantly, what it didn’t do.

The basics.

Who was Involved:

NBC Sports created its own Olympic VR app and worked with Intel and Olympic Broadcasting Services (which produces video of the Olympic games) to stream live event coverage to a range of VR headsets. It’s the second time NBC has included 360 video in its Olympic coverage but the first time they streamed live events.

What hardware was Included:

Samsung Gear VR, Google Daydream, and Windows Mixed Reality headsets.

Coverage:

NBC offered 50 hours of 360 video coverage during the 2-week event. And because stats mean nothing without relative stats against them, consider that NBC broadcasted 2,400 hours of 2D (television/computer) screen coverage of the games (the most ever). Among the events streamed in VR headsets were curling, snowboarding, bobsledding, and ski-jumping.

Did you have to pay:

Yes and no. Downloading the NBC Olympics VR app was free. Then you needed to enter your cable provider and password.

What did it look like:

Compared to high definition on a 2D screen, the 360 video in VR was grainy. Some events were offered in 180 (basically meaning you watched a 2D screen inside the Virtual space).

What content was the best:

The Opening Ceremony in VR was pretty cool (it’s such a dynamic event with a portion of the show emerging from the stands and a variety of lights and colors). Getting the chance to view the ceremony in VR did provide the feeling of being there. You got to look all around the stadium, hear the moving crowd, see the energized environment, and focus on whichever portions of the show interested you most.

What needs to improve:

The quality of 360 video. Compared to the HD quality of your 2D TV or computer screen, 360 video falls well short. Additionally, it’s crucial to realize that the Olympic content was marketed as “The Olympics in VR” but it was actually “The Olympics in 360 Video” — inside a VR headset.

The Difference Between VR and 360 Video:

What makes VR such an incredible technology is the interactivity it provides. For the first time, humans are able to interact with (actually reach out to touch, move, and have an influence on) the digitally immersive world surrounding them. This foundational element is what’s garnered massive investments from Facebook, Microsoft, Google, Samsung and others. “The Olympics in VR” included none of this impact — excluding interactivity among users inside the digital world and interactivity with the digital world itself.

Bottom Line:

The reason “The Olympics in VR” was actually “The Olympics in 360” is two fold.

The type of headset that’s capable of supporting 360 video is more affordable than the full VR rigs (and, thus, far more prevalent in the US).
Creating truly interactive and high quality VR content to cover an event like the Olympics would be far too costly and require far too many resources to generate an ROI (again, considering how few people own the hardware and thus how few people would have the capability to interact with the content).
Wrapt it up:

Credit to NBC (and the others who were part of it) for getting out there and experimenting with the new technology. But if you missed out on the 360 coverage this year…you’re probably just as well off checking back in with the coverage in the summer of 2020 in Tokyo.

**** The Father of VR 

There were a few middle-aged guys over the studio last month and I referred to VR as a “new technology.” One of them seemed ready to catch me on this and drop a mention of how VR has been around for decades and how our studio should know all about this — being that we produce it and all.

“A new technology?” he asked with a suspicious tone.

“Well,” I said. “If you really wanted to you could go all the way back to Morton Heilig in the 1950s and begin the story of VR back then.”

Mentioning that name was, in itself, enough to prevent any further suspicion. But if the gentleman had asked me to speak any more about Heilig I wouldn’t have been able to.

I remembered that an old guy on the back patio of the coffee shop in Red Hook had labeled him as “The Father of VR” back in the fall, but beyond that I didn’t know much more.

So, I spent last night reading about him and what he brought to an industry that is, more than half a century later, still budding.

Born in 1926, Heilig established himself as a cinematographer, using that background to eventually develop and patent two pieces of technology: “the telesphere mask” and the “Sensorama.” He and his partner began the development of these machines in 1957, patenting them in 1962.

A bulky piece of technology shaped like an old-school arcade game, the sensorama allowed the user to sit on a chair and lean their head into the equipment — kinda like you would the vision machine at the optometrist. One of the first experiences available in the Sensorama was of a motorcycle ride through Brooklyn. Heilig attempted to incorporate all the senses and draw the viewer into a cinematic experience — a very similar description of what we understand VR to be more than 60 years later. He referred to it as “Experience Theatre.”

He published a paper in 1955 called the “The cinema of the future” in which he detailed a multi-sensory theatre experience. The first text that appears inside the document reads, “Thus, individually and collectively, by thoroughly applying the methodology of art, the cinema of the future will become the first art form to reveal the new scientific world to man in the full sensual vividness and dynamic vitality of his consciousness.”

After this writing he went on to create the sensorama and five short film displays. The machine still functions to this day.

Eventually, Heilig said he wasn’t able to capture high enough quality images from 35 mm film cameras in order to create an immersive experience that was marketable enough to the general public.

Here’s the link to his 1955 research paper. https://gametechdms.files.wordpress.com/2014/08/w6_thecinemaoffuture_morton.pdf

**** Off The Ground 

This Is The 2nd In a Nova XR Media Multi-Part Series

As we study the way a new technology progresses through the Adoption Lifecycle, we realize the innovators have already captured Virtual Reality.

Geoffrey Moore describes the innovators as a group of technology enthusiasts who appreciate the tech for its own sake. They don’t need to believe it will break through in the market nor that it holds the potential for greater achievement. The innovators savor in the technology for everything it is — whether it’s the smooth texture of the software or it’s painfully slow operating speed.

With Facebook having committed a multi-billion-dollar investment and MIT using Facebook’s new VR headset to allow humans first person control of robots, the innovators have their hands on Virtual Reality.

[Tech Adoption Chart displaying Innovators, Early Adopters, Early Majority, Late Majority, Lagards]

The early adopters come in behind the innovators and bring their vision. Moore calls them, “That rare breed of people who have the insight to match up an emerging technology to a strategic opportunity, the temper to translate that insight into a high-visibility, high-risk project, and the charisma to get the rest of their organization to buy into that project…the core of their dream is a business goal, not a technology goal.”

Well, as we approach 2018, VR has extended it’s reach all the way to Lowe’s, who’s incorporated a Holoroom to allow customers immersive experiences such as shifting the paint color on the walls of their new room. This means homeowners who may work in any range of industries have experienced VR inside a building operated by one of the strongest brands in the country.

While reaching this level of audience is an advanced step for the technology, it’s an indication of Lowe’s reaching right to left across the chasm and becoming an early adopter.

We see evidence of this with CNBC’s report that estimates Facebook sold fewer than 400,000 units of their Oculus Rift in 2016. Remember, the early majority represents one third of the market, so if the largest tech giant didn’t break ½ million sales in its first year, we understand that VR has yet to cross over.

**** Crossing The Virtual Chasm 

This is an introduction to Nova Media’s multi-part examination of Virtual Reality’s journey toward critical mass in the consumer market.

VR has a long and fragmented history dating all the way back to Morton Heilig in the 1950s. Then there was a simulation of Aspen, Colorado that came out of MIT in the late 70’s. A-decade-and-a half-later Sega announced the release of their first VR headset for an arcade game.

All of these…just a few of the breakthroughs that have led to predictions about how and when VR will make its significant impact on the consumer market.

But as the years passed we heard just a faint noise from this new virtual world playing in the background, often drowned out by HD TVs, smartphones, and social media.

The noise got louder, though, in 2014 when Facebook acquired Oculus and its new VR headset for over $2 billion. And then — at Oculus’ annual conference last month — a louder noise from Mark Zuckerberg, who said, “I am more committed than ever to the future of VR.”

So now, three years into Facebook’s involvement with this emerging technology, we’re still asking the question: when will VR reach critical mass?

In 1989 Geoffrey Moore wrote the first version of “Crossing The Chasm”, studying why, how, and at what rate new ideas and technologies spread through the market.

His book, which emerged in its third version three years ago, studies the tendencies with which young technologies progress through the adoption life cycle. The writing focuses on how these products often wind up stuck in the divide between the early adopters and the early majority. This can be a deadly place for a new technology to try and survive, as the early majority makes up 1/3 of the market.

[Tech Adoption Chart displaying Innovators, Early Adopters, Early Majority, Late Majority, Lagards]

This series will examine where VR stands in relation to this curve, what’s prevented it from breaking through, and what will need to happen in order for it to cross the next divide.

**** World Peace
Virtual Reality will democratize experience.

Consider how the internet democratized information.

The internet has globalized us. We communicate, share, and do business with people around the world - most we've never met in person. We may have never seen their face or heard their voice, but we /know/ them.

XR empowers remote access to in-person experiences through shared virtual environments.

If we really knew what it was like to walk in another's shoes, we'd be humbled. If we visited the places our governments declared as enemies, we'd ask more questions. If we knew first hand the horrors of war, the inhumanity of greed, and the glory of love, we'd live differently.

Virtual Reality will democratize experience and facilitate peace.

*** Use Cases

**** Education 
Like the media platforms before it, Extended Reality will continue merging with educational systems around the world and advance visual learning. 

The industry is implementing bar code stickers for the interior of academic textbooks. Scanning the code with an AR kit brings information off the page. This visual learning also reduces the cognitive load required of school teachers.   

In a test run for this program students learned basic anatomy of the heart. 

**** Immersive Art 

Artists are already creating and displaying in Virtual Reality. 

Google's "Tilt Brush" is a Virtual painting program. Stepping inside, artists select various brush strokes, hues, and implements for designing 3D models. In Tilt Brush, and similar customized programs, graphic designers are learning how to design 3D models in a 3D space, enhancing the work they've already done in programs like Blender and Maya.

In addition to the creation of 3D models, artists and businesses are displaying artwork in the Virtual World. The work of Photographers, sculptors, designers, and other visual artists are on display in Virtual art galleries. See Infinite Gallery.

**** Medical 

# Neuroscience
Stanford Medicine is using a software system that combines imaging from MRIs, CT scans, and angiograms to create a three dimensional model of the patient's brain prior to surgery.

Inside these 3D renderings, surgeons wear the headset and step inside a model of the patient's brain. It's a pre-op tool that allows for customized planning. Interaction with the three dimensional images enhances preparation and improves accuracy.

“We can plan out how we can approach a tumor and avoid critical areas like the motor cortex or the sensory areas. Before, we didn’t have the ability to reconstruct it in three dimensions; we’d have to do it in our minds." -Gary Steinberg, MD, neurosurgeon, PhD.

https://www.youtube.com/watch?v=TYBxhomLAcw

https://med.stanford.edu/news/all-news/2017/07/virtual-reality-system-helps-surgeons-reassures-patients.html

**** Collaboration 

# Virtual Meetings

Despite thousands of physical miles that may separate business associates, Virtual Chat Rooms allow folks to be together in the same Virtual space. Thin flexible fibers with glass core light signals (fiber optics) send data and information at a rate of 50Mps. Our movements and voices are read and replicated, so recipients can experience these behaviors through simulated software. We’re now calling this technology "Virtual Reality."

As VR becomes more prevalent in business, it will replace video conferencing. Instead of seeing the image of a colleague's face on your 2D computer screen, you'll put on the headset and join them in a Virtual Conference room, hearing their voice in 3D audio and using Virtual controller commands to trigger interaction and demonstration.

**** Travel and Tourism 

National ministries (tourism/trade divisions) are developing content that lets us soar through the sky like an Olympic ski jumper (Korea Tourism Office, ~$100k), hang out backstage with Sir Paul McCartney (Visit Britain, ~$1.5mm), and swim the crystal clear Caribbean alongside stingrays (Caribbean Island, ~$300,000). These organizations are finding that immersive media engages travelers and influences agencies more effectively than any media prior, with more robust analytics to prove return on investment.

«Before, travelers just had a brochure or information on the website to inform their choices. Virtual reality allows them to get a true sense of the hotel and the excursion they can go on. It’s been a real game changer for us all.»
  - Marco Ryan, Chief Digital Officer, Thomas Cook

«…Virtual reality let’s our travel trade and media partners experience our destination in a new and unique way that has not been possible before.»
   -Marsha Walden, CEO, Destination British Columbia.

**** XR Auto Revolution 

Through various holiday sales and new vehicle features, the automotive industry works to attract buyers to the showroom. Virtual Reality brings a three-dimensional automotive experience to the buyer’s home. Inside their VR headset, the user is able to interact with the vehicle and even sit in the driver's seat. 

First we capture dozens of photos from various angles of both the vehicle's interior and exterior, a process known as photogrammetry. Once the images are captured, they're arranged (or "meshed") together in a 3D software to be exported and made compatible with VR hardware. 

The end result: the user can sit inside the car and walk around the exterior of the vehicle. Once they sit behind the wheel, they’ll be able to adjust the seat and mirror before turning the key and taking the car for a simulated test-drive through the streets of any city or town in the world.

**** Gaming 

# The Pioneering Industry 

In its earliest days, Virtual Reality was predominantly a home for gamers. Classic video games like "Doom" have been remade for VR, while new games like "The Price of Freedom" are expanding the concept of VR gaming. 

The software programs most commonly used to build Virtual programs (game engines like Unity and Unreal) were first a platforms for building video games. These game engines are now evolving to build all forms of Virtual interactivity. 

VR is different from most media forms that have come before it. Unlike newspapers, books, radio, and television, VR encourages the user to be part of the content, using their body and mind to influencing the information surrounding them. This is a principle first mastered in the gaming industry. 

We continue to source the expertise of video game programmers to realize VR's potential.

**** Fundraising 
Allow the immersion of Virtual Reality to draw a stronger connection between the donor and those who are in need of their assistance.

At the root of fundraising is the empathetic connection that encourages funds to change hands. Take the example of the Wounded Warriors Project. With a mission of offering a variety of educational, health, and employment programs to veterans, the foundation relies heavily on donations from a variety of sources. Often these donations are solicited at events that attempt to communicate the journey, mentality, and some of the post-combat struggles that afflict soldiers across the country.

For those who’ve never been to war, one of the most incomprehensible tasks is truly understanding the journey of a soldier. Advanced technology does not bridge this gap between civilians and soldiers. However, it can increase the likelihood of striking an empathetic connection.

At a fundraising event geared toward raising money for Wounded Warriors, Virtual Reality can take the donor inside an immersive experience that reflects some of the perils and post-combat ills that plague soldiers. Virtual Reality can digitally put the donor in the place of a soldier as the say goodbye to their family, arrive oversees, and ride through foreign terrain toward combat. Inside the headset, the donor can also experience the elation of returning home from war and the devastation of rehabilitating some of the life-altering injuries sustained by these men and women.

**** Hiring 
Even some of the most successful companies struggle to hire the right employees. The applicant creates a resume from their most attractive accomplishments and prepares their best presentation to display during the interview process.

Virtual Reality provides an opportunity to evaluate the psychology of the applicant more explicitly. By presenting a Virtual component to supplement your company’s interview process, you’ll ask the applicant to enter an interactive Virtual World in which they’ll go through a series of short prompts. Through advanced psychological studies, we’ll help you understand how the applicant’s interaction with the Virtual prompts reveals elements of their mentality, learning style, and competence as related to the particular job opening.

Data collected from their spatial behavior, interaction with various objects, and reaction to varying colors will help companies better evaluate applicants and ultimately reduce costs in their HR department.

**** Relocation Financial Strategy

One of the most powerful applications of VR is Virtual Teleportation. This capability inside the Virtual world introduces a number of travel-based business solutions, the most immediate of which we’ve found within the relocation industry.

When a company relocates an employee from one city to another, the move may require multiple flights to the target city. The employee must find a new home, orient with the geography, and determine the right school for their children.

Customizing this solution for various relocation-based businesses includes the following Financial Strategy.

## Abstract

This document investigates a financial strategy to scale VR in the relocation industry. When a company relocates an employee, this implies the cost of accommodating the employee to this new location. This translates into flights, meals, lack of sleep, lack of availability at work among other issues.

The analysis covers the costs of the application itself, the hardware necessary to run it, and the content development costs. A strategy is suggested to obtain a return on investment as quickly as possible and break even during the second year following the project’s start.

By replacing the employee’s first exploration trip to the new city with a virtual experience (simulating the location), Dwellworks could save between 33% to 50% of traveling related costs and could see a net return on investment of about $1 million by year 4.

## Introduction

Using virtual reality in the relocation industry in order to reduce operating costs is an obvious application of the technology. We will try to quantify the costs associated with such a project and the revenue it can generate. We will then define a method to scale the project to multiple cities until all the cities are accessible from the VR platform.

/See our Contact page to inquire about more info/

**** NYE Financial Strategy

This document analyzes the New Year’s XR Virtual Reality experience from the perspective of the advertiser. Our subject is a tourism board seeking increased visibility abroad and short term foot traffic at home. The project’s return on investment is detailed before the paper’s conclusion.

## Abstract

Nova Media is producing New Year’s Eve in Virtual Reality, an opportunity to reach a target audience through immersive media. This project heavily targets VR headset owners, encouraging them to try New Year’s XR with friends to increase the program’s overall viewership.

## Introduction 

This paper investigates the advertising potential of New Year’s XR. The cost of sponsoring New Year’s XR is $100,000, 20% of which will be dedicated to the advertising budget. There will be 10 sponsors and thus a $200,000 ad budget. By pooling together 10 ad buyers, your $20,000 investment returns as a $200,000 product. Through specific social media channels and YouTube programming geared directly toward this campaign’s target market, we explain the probability of going viral and what that means for your final return on investment.

/See our Contact page to inquire about more info/.

**** Projection Mapping Market Analysis 

One of the display options within Extended Reality is Projection Mapping. With a series of images projected onto the walls, users are taken into a digitally created 3D environment without holding a smartphone or wearing a VR headset.

Industries have used projection mapping for decades as a means of enhancing both their product image and marketing strategies. While the term is relatively new, we see traces of this content display dating all the way back to 1969 at Disney’s haunted mansion ride, when the technology was more commonly referred to as “Spatial Augmented Reality.”

Five decades later, “Projection Mapping” has stretched into many corners of entertainment, education, and visual art. For nine consecutive years in Australia, the Sydney Opera House has hosted “The Lighting of the Sails” - selecting a digital production company to display a dramatic and colorful array of images and motion pictures onto the grand sails of the famous 20th Opera House.

Every fall, the city of Bucharest hosts the biggest projection mapping competition in the world, inviting visual artists to project a series of mapped structures onto the 60,000 square foot facade of the Palace of Parliament, the second largest administrative building in the world. The event is called Imap Bucharest.

In 2017 the Canadian tech company SAGA released a project called “The Interactive Gym.” By projecting a series of shapes onto the wall of an elementary school gymnasium, the product enticed young students to participate in physical education class. With the objective of tossing a ball against the wall and pegging the projected shapes in motion, students earned points in accordance with the accuracy of their tosses. With a prototype created in less than a month, SAGA has begun investigating the deeper seeded influence of combining digital gaming with physical activity and team play.

In her book titled “Alone Together,” Sherry Turke, a social scientist at MIT, summed up an alarming phenomenon we’ve all become familiar with since the advent of the smartphone. It’s the feeling you get when you’re in the same room with close friends, family members, or coworkers, yet everyone is silent - interacting only with the tiny screens between their fingers. It’s disconnectedness. The recent development of Extended Reality is influencing this concept, enticing users to interact with the technology as a group.

**** NYE Market Analysis  

Nova's New Year's XR is the first ever live New Year's celebration in Virtual Reality. We set up 360 cameras in 10 cities around the globe and live stream the scene from Times Square or a rooftop in Dubai on the most festive night of the year. We evaluated the market for this content and quantified how many potential viewers might be at home and interested in experiencing this content: 

Live streaming from an array of global destinations has never happened in VR, yet the concept has already been validated in 2D. On December 31, 2017 Time Magazine streamed live from 12 countries across four continents.

As we enhance this concept for VR technology, consider most VR users access their equipment at home, similar to the way television content is consumed. As New Year's Eve is famous for attracting people into the nightlife, we examine how many people in the United States were viewing each of the last three New Year's Eve Celebrations on the four major American television networks. {{{cite(NYE-2D-Stream)}}}

#+CAPTION: NYE network ratings
| Network | 2015    | 2016    | 2017     |
|---------+---------+---------+----------|
| ABC     | 18 mil  | 16 mil  | 21.1 mil |
| CBS     | 3.1 mil | 3.4 mil | 3.1 mil  |
| NBC     | 6 mil   | 6.6 mil | 3.6 mil  |
| FOX     | 4 mil   | 6.6 mil | 3.6 mil  |


Over the last three years the major American networks have combined to average 30 million viewers on New Year's Eve. On Average, 12.5 million of those viewers came from the 18-49 age demographic (the same demo that owns the majority of Virtual Reality headsets.

There are three important conclusions to draw from the information in this section: 

 1) Major publications like Time Magazine and high profile tourism locations like Dubai, Hong Kong, Rio De Janeiro, and New York City have already adopted this live stream concept on New Year's Eve.
 2) The basic hardware and software challenges presented by this streaming concept have already been validated for the flat screen. 
 3) Despite New Year's Eve being famous for drawing people out of the home and into the nightlife, official network ratings reveal that millions of people are in fact in the home on this night of celebration. 

Also to Note: a VR studio in Amsterdam released a 360º video series in 2017 centered on immersive VR tours of London, Amsterdam, Bangkok, and Rome (among others). In total, the series received more than one million views on YouTube. 360º is an immersive experience that is beginning to drive Virtual travel. 

"...[Virtual Reality] let's our travel trade and media partners experience our destination in a new and unique way that has not been possible before." - Marsha Walden, CEO, Destination British Columbia.

* Services 

** Design 

## *Concepting*

This is the first phase of XR design, the foundation of the project build. Here we must consider: 

- ** 1.The Brand's Identity:** What problem is the brand aiming to solve by expanding into XR?

- ** 2. The Audience:** Who is the brand aiming to reach? 

- ** 3. Reaching the Audience:** On which channels and platforms is the audience likely to exist?

- ** 4. The User Journey:** How does the experience begin? What does the user see, hear, and feel? What actions are they prompted to take? What is the memory that stays with them after the experience ends?  

In XR we can build innovative digital worlds that abide by their own physical laws, or we can bring the laws of the physical world into the virtual environment. Limitlessness is the both the challenge and the attraction. 

## *Designing Physics*

The finest XR programs are built in collaboration between 3D designers and 3D developers and the confines of the imagination are the only limits. 

We will use the retail industry as a case study. Consider that the general design of current brick and mortar retail space is bound by the laws of gravity. Objects must be supported by shelves and hangers. For similar terrestrial reasons, inventory is often retailed inside a piece of physical architecture restricted to a single plot of land. Inside Virtual architecture, though, object and human movement behave and react however we decide. We can arrange gravitational laws and all of the corresponding elements like sunlight, wind, and rainfall however we choose. Limitlessness design. 

With this in mind, details like the polygon count used and fluidity of user motion all drive the scope of work when integrating the design with the code that brings the environment to life.    

## *New Design Components* 

Designing a Virtual World means telling a story through an experience of shapes, colors, lighting, and movement. Throughout the XR experience, users move through a progression of digitally-created spaces. Each of these segments serve as marketable assets. Consider these spaces akin to the rooms of a home. As the blueprint of a home expands so does the cost of production.  

To maximize the immersive feeling inside XR, we design in a manner evoking user trust. As users move through the world, the must believe what they are seeing. While the style of design may invite their senses into an other-worldly realm, users must believe the integrity of what they are experiencing. The size of objects must agree with their behavior, which must all tie together with fluidity of the user's motion through this digital world. They will walk away from this VR experience inspired to think, create, and dream.

** Develop

The VR we develop is programmable. Virtual experiences can be manipulated through inputs such as code, player interfacing, or physiological behaviors. Content produced can range from photo-real capture to entirely fictitious dreamscapes.

"Networking" the software allows multiple people to interact in VR together. Some of its immediate results are market creation, distributed file keeping, and remote access to devices.

There are a variety of production techniques, tools, and frameworks used to make XR. They are all synchronized in a software framework called a "game engine". A game engine is used to create interactive 3D media (XR). These engines are powerful visualization tools for developing all the features of the internet (networked play, social sharing, secure payments, etc.) into a single application.

Game engines empower developers to custom-design virtual environments. The core game engine frameworks include rendering 3D graphics, engineering physics engines (and response systems), managing memory, and handling graphics scenes.

Nova economizes the Virtual Reality (VR) development process by adapting game engine builds (software executable) to create new VR experiences. By developing with foresight, producers save time and money.

** Deploy

Once the XR program has been designed, developed, and tested it may be deployed through a variety of methods. Broadly, XR content can be distributed on-site or across an XR app store.

*On-Site:* 
Depending on the style of content, it may be best to deploy XR at your place of business. Whether it is a training program, a customized user experience for your guests, or educational marketing material, offering XR content to people who flow through your office, practice, studio, or display room may be the best option. In this case, deploying the content is similar to displaying a video file on your computer. We will install the hardware for you, train your personnel on how to operate it, and provide remote support. 

*XR App Store:*
Consider to the way users download applications from the app store on their mobile phone. A similar means of distribution is available with XR content. By logging onto the Oculus (app store associated with Facebook's XR hardware) or Steam (app store associated with HTC Vive hardware), users access XR content from anywhere in the world. 

Determining which means of distribution best fits a given program will take place during the design phase. 

* Nova XR 

** Who We Are 
/Includes "Find Us"/

Nova XR Media is built by four founders. We come from corporate sales, computer science, architectural design, and production. We bring diversity to a small group of early movers in New York City who are driving XR forward. We design, develop, innovate, and build.

We produce a range of products enabling users to transcend time and space through virtual worlds and simulated play. Our clients use 3D immersive media to market new products, train students and employees, gamify education, and entertain customers. Nova XR Media guides the development, advises on financial strategies and manages production. Our studio and laboratory is located at the edge of Red Hook, Brooklyn.


## Joe Mecca - CEO

Joe started his career in media and production at Purdue University, where he wrote for the Greek Newspaper. He went on to be the sales director and publisher, expanding circulation from 6,000 to 17,000 weekly, growing sales from $10,000 in annual revenue to $25,000.  

After graduating Joe moved to New York to work for Clear Channel as an account executive selling sponsorships direct to brands. With an average of $1 million in sales per year, Joe led execution of mutli-platform campaigns (events, radio, web, mobile, video) and was the point of contact for clients. His role evolved into innovating tech integrations for programming and commercial content, before departing for extended travel to Europe and the Middle East.

Upon returning Joe began a Virtual Reality Studio, Nova Media, out of his apartment, and without capital. While assembling a team, Nova bootstrapped its business, producing and developing XR software for individuals and multinational brands.  Today, Joe and Nova continue to produce bleeding edge content from their studio in Red Hook, Brooklyn.  

## Jacques Lalo - Art Director

Born and raised in Paris, Jacques left the city at age 19, enrolling as a pre-med student in the south of France. Jacques views the human body as extraordinary design. The functionality of the lungs, the power of the heart, the connectivity of the muscular system, and all the body's coherency inspires his work in VR. Back in Paris, he began studying at Ecole Bleue, mastering architectural design and experiencing the world through his deep understanding of the discipline. Along the way he became an expert in Blender, the most complex 3D software environment driving virtual reality asset creation. 

In the summer of 2017, Jacques arrived in Brooklyn and quickly became one of Nova's founding members. Thanks to his intricate understanding of brand creation, the story of Nova deepened. Its 3D logo and graphic charter were born, and its image solidified. Novamedia.nyc features Jacques' hand-crafted visuals, each inspired by his understanding of design, advanced technology, and extended reality as an emerging market.

He recently, under the Nova brand name, designed each of the characters for a Google-backed immersive 360 experience called Armonia. Only as XR begins attracting more artists of his caliber will it blossom. 

## Kyle Kesses - Marketing Director

Six months after graduating from Fordham University, Kyle became a writer and on-camera broadcaster for the New York Yankees. In his final season, as part of a 5-person production team, he wrote and voiced an Emmy-winning episodic series in 2016. 

During extended travel through Latin America, he wrote his first manuscript, a 7-part book of short stories, each chapter introducing the reader to characters who are meeting for the first time. The book exists among their homes, minds, and transience as they interact with death, lust, love, violence, and fear. 

Returning to New York, he met Joe at the start of 2017 and discovered VR. The experience resonated and sent him on an ensuing research journey through the history of media and the evolution of mass human connectivity, a journey that led him back to Nova. He became the team's writer and next co-founder, establishing its marketing philosophy and passion for human-to-human connection.   

With an affinity for language and voice, Kyle simplifies complex concepts into comprehensive writings, bridging many divides among artists, engineers, and businesses.

## Thomas Binetruy - Engineer 

Thomas introduces an extraordinarily global perspective. Born in Egypt and raised among Paris, Houston, and Dubai, he is natively fluent in French and English. Inspired by 20th century giants like Richard Feynman and Albert Eisnstein, he landed at one of the finest engineering schools in the US, Purdue University. 

Purdue owns the airport in West Lafayette, the second most trafficked in the state of Indiana, and this is where Thomas earned his degree in aeronautical engineering. He went on to design hydrogen fuel cell prototypes at Zodiac Aerospace before becoming a consultant at Ailancy in Paris. 

Always engrossed in the process and obsessed with how things work, he could not resist the hands-on opportunity to build an advanced technology company. So when Joe, his former Purdue classmate, shared Nova's incubating business plan in 2017, Thomas began sourcing his self-taught coding skills. Within a year he had built novamedia.nyc on React, writing the codebase in JavaScript.

As computer programming continues shifting into 3D, developers like Thomas, with a true engineering background, will continue leading the way.

** Partnerships 

A shout to our friends and family.  Without ya'll Nova is nothing.  

Our open door philosophy attracts a range of people from varying communities. This makes Nova Studios an idea hub for crafting market opportunities. 

*** Redu Media
Redu is making obsolescence obsolete. A close member of Nova's family, Redu is dedicated to upcycling materials that would otherwise go to waste. Amber and Kaya lead /rescues/, traveling throughout the tri state area to collect materials and prevent them from going to landfill. Back inside Redu's design studio, the materials are tastefully crafted into furniture and applied art.

*** Surf-Far

Produces eco-friendly wetsuits for women, by women.   Made of Yulex or recycled neoprene, recycled water bottles, and water based glues Surf-Far designs comfortable and durable wetsuits that have a low impact on the environment.  As surfers, ocean lovers, and humans, is ensuring that future generations have the opportunity to enjoy this earth the way we all enjoy it today.  Brooklyn, New York. 

*** Fulla Shirts

Fulla designs and produces T-shirts to order.  As a Red Hook native, Ren and his team know what it means to be Brooklyn, and to deliver style.  Swing by the shop anytime to kick it with a true entrepreneur and a good friend.   


*** Potential Synergy 
At the forefront of XR technology development, Potential Synergy builds lucid dreams. They also build practical XR solutions. At the forefront of the studio's cornerstone products is Dreamscaping - a principle designed to eliminate the dizziness some users experienced inside the Oculus Rift. Their current project - Match Quest - tests short and long term memory. As users succeed within the game, they become closer and closer to obtaining real Ethereum. 

*** Construct Studios   
With a basis in both San Fran and New York City, Construct studios has built one of the most trafficked VR worlds available to the public - /The Price of Freedom/. They're a team of game developers working to bring XR to varying fields: Medicine, Education, and Industry. https://construct.studio/

*** Aptonomy 
Aptonomy is a premiere aerial protection service leading the movement into Drone-based security systems.

*** Con Body 
Coss Marte was serving a seven year prison sentence when doctors told him he could die in the prison cell if he didn't take control of his health. While incarcerated, he designed a physical fitness program and began building toward peak physical condition. Once released, Coss built the current ConBody workout facility in the Lower East Side of Manhattan. Today, you can visit Coss and the former prisoners who work with him. They'll put you through your paces. In a 30 or 60 minute workout, you'll experience the sights, sounds, and workout regimen of the incarcerated. Be ready. 
https://www.youtube.com/watch?v=3npsu-wnL6o

*** Clinken Films  
Jon is a storyteller. He began as a writer and stage actor and has spread his storytelling skills with artificial intelligence and Virtual Reality. He's currently developing an interactive story, releasing an episode each week. VR, AI, and snail mail are all forms included.

** Productions

At the core we are an XR production studio. We help brands understand the technology, manage their investment, and build their campaign from start to finish.

*** Hard Rock Hotels

# Hard Rock Hotels

## Situation
Hard Rock Riviera Maya had a PR objective to earn big media.   They had access to top music talent and a badass resort in Mexico.   

## Solution

"Elvis Rocks Mexico -  Riviera Maya"

Throw a massive party
400 attendees 
Match Top music Talent
Strategically promoted
Earn coverage

## Execution
Live From Mexico we broadcasted a weekend of dysfunctional family fun to 63 million.   Live music performances from Nick Jonas and Brett Michaels, all the beach, spa and partying anyone person could handle... 

## Results
- 201,008,806 Gross Impressions
- 280,000 contest entries
- $2.59 million media/PR value (15cpm)
- 86 million social media impressions
- 400 attendees
- $97,000 avg HHI
- 73% Earned Media

It was the dead cold of winter.  Those endlessly numb days.   It was still dark but half the city was on their way to work.   At 7:29AM while inching through traffic, Elvis Duran in his jolly voice announced to the country his plans for vacation.   His words reverbed live to 75 cities and  was giving away vacations to5 million people.  This May he and his family would be flying to the Hard Rock Riviera Maya Resort in Mexico.

Hyped as the vacation of the year, 400x people purchased packages to join the parties.

We recruited Nick Jonas and Brett Michaels to join.

Over the weekend hundreds lived life to the fullest via Hard Rock's all inclusive, while millions enjoyed vicariously.   The program earned more than 85 million impressions on social media, alone.  

Media outlets across the country picked up the fun, earning more than 200 million impressions and more than $2.5 million in media value.

The vacation has now become a tradition.

# Hawaiian Airlines

## Situation

Hawaiian airlines was launching a new flight from JFK direct to Honolulu and needed people to know about it.

## Solution

Multi-platform promotion through traditional media, digital targeting and on-site activation.
 
## Execution

Starting in April we surveyed New York metro about airlines, trafficked customized commercial media, called participants to action and produced world-class content.   On-stage in front of thousands of professionals Hawaiian Airlines brought culture to life and associated it with the new route's details. The response was unforgettable. 

## Results

- Increased brand recognition by 12.1%
- Click-through rate four times the national average
- 11% greater reach than predicted

# Kelly Vision

## Situation

Dr. Kelly was looking for a way to combine the mass reach of traditional media with modern technologies of digital tracking to quantifiably measure his return on investment

## Objective

To get people in the door and start taking their considerations of vision enhancement seriously.

Educate and welcome prospective patients into our family and computer system

Evaluate the cost per eye.  

Investment $30,000 to return $35 surgeries.  

## Campaign

Brand ambassador on 5 top media outlets for full scope of media deliverables.

Promotion code to track business (interests, connections, bookings, payments.

Adjusted content on the fly to improve ROI

## Results

- Delivered more than $20k in vision business in 21 days.

- 100 surgeries in 10 months

- 50+ phone calls received

- 1,000 + text messages 

# Taiwan

## Situation

Taiwan is of the lesser known Asia destinations but has an amazing culture to share. We needed to stand apart from the rest of Asia. Knowing we will not brand bigger than China or Japan in the short-term, we complimented them.

## Strategy

(1) Bring a credible message about culture, food, beauty and other features of the destination. 
(2) Transfer the earned trust and credibility of a known personality to highlight “Why Taiwan”. 
(3) Share from a first person perspective. 
(4) Develop PR exposure through creative engagement

## Execution
 Travel expert, Pauline Frommer, brought the travel show to Taiwan. We created an array of content to share across multiple distribution channels. Integrate with entertainment darlings and showcase the culture through event partnerships in Bryant Park.

## Results
- 7% increase in US visits year over year. 
- Renewed production program at a 45% increase in investment. 
- 10 million media impressions through “earned media”. 
- Evergreen content to re-purpose indefinitely.

* Legals

** Terms and Conditions of Use

We maintain this site as a resource and communication portal. Terms of Service apply to anyone browsing the website. Accessing the site is acceptance without limitation or qualification of the following Terms and Conditions. If you do NOT accept the Terms and Conditions, please discontinue your use of this Site.

** Privacy Policy

We use basic Google Analytics to improve our services:

Opt-out of Google Analytics: https://tools.google.com/dlpage/gaoptout/

*Save the Internet*

The internet is subject to change under proposed US policy that would compromise /Net Neutrality/.   We strongly support a free and open internet, which is at stake. Read more at SaveTheInternet.com https://www.savetheinternet.com/net-neutrality-what-you-need-know-now

/Net Neutrality/ the principle that Internet service providers should enable access to all content and applications regardless of the source and without favoring or blocking particular products or websites.

*Exhaustive Legal*

This privacy policy has been compiled to better serve those who are concerned with how their 'Personally Identifiable Information' (PII) is being used online. PII, as described in US privacy law and information security, is information that can be used on its own or with other information to identify, contact, or locate a single person, or to identify an individual in context. Please read our privacy policy carefully to get a clear understanding of how we collect, use, protect or otherwise handle your Personally Identifiable Information in accordance with our website.

*What personal information do we collect from the people that visit our blog, website or app?*

When ordering or registering on our site, as appropriate, you may be asked to enter your name, email address, mailing address, phone number, credit card information, interest or other details to help you with your experience.

*When do we collect information?

We collect information from you when you register on our site, respond to a survey, fill out a form, Use Live Chat, Open a Support Ticket or enter information on our site.

Provide us with feedback on our products or services

*How do we use your information?

We may use the information we collect from you when you register, make a purchase, sign up for our newsletter, respond to a survey or marketing communication, surf the website, or use certain other site features in the following ways:

      • To personalize your experience and to allow us to deliver the type of content and product offerings in which you are most interested.
      • To improve our website in order to better serve you.
      • To allow us to better service you in responding to your customer service requests.
      • To administer a contest, promotion, survey or other site feature.
      • To quickly process your transactions.
      • To ask for ratings and reviews of services or products
      • To follow up with them after correspondence (live chat, email or phone inquiries)

*How do we protect your information?*

We do not use vulnerability scanning and/or scanning to PCI standards.
We only provide articles and information. We never ask for credit card numbers.
We do not use Malware Scanning.

Your personal information is contained behind secured networks and is only accessible by a limited number of persons who have special access rights to such systems, and are required to keep the information confidential. In addition, all sensitive/credit information you supply is encrypted via Secure Socket Layer (SSL) technology.

We implement a variety of security measures when a user enters, submits, or accesses their information to maintain the safety of your personal information.

All transactions are processed through a gateway provider and are not stored or processed on our servers.

*Do we use 'cookies'?*

Yes. Cookies are small files that a site or its service provider transfers to your computer's hard drive through your Web browser (if you allow) that enables the site's or service provider's systems to recognize your browser and capture and remember certain information. For instance, we use cookies to help us remember and process the items in your shopping cart. They are also used to help us understand your preferences based on previous or current site activity, which enables us to provide you with improved services. We also use cookies to help us compile aggregate data about site traffic and site interaction so that we can offer better site experiences and tools in the future.

*We use cookies to*

      • Understand and save user's preferences for future visits.
      • Keep track of advertisements.
      • Compile aggregate data about site traffic and site interactions in order to offer better site experiences and tools in the future. We may also use trusted third-party services that track this information on our behalf.

You can choose to have your computer warn you each time a cookie is being sent, or you can choose to turn off all cookies. You do this through your browser settings. Since browser is a little different, look at your browser's Help Menu to learn the correct way to modify your cookies.

If you turn cookies off, Some of the features that make your site experience more efficient may not function properly.Some of the features that make your site experience more efficient and may not function properly.

*Third-party disclosure*

Do we disclose nothing to third parties.   

Occasionally, at our discretion, we may include or offer third-party products or services on our website. These third-party sites have separate and independent privacy policies. We therefore have no responsibility or liability for the content and activities of these linked sites. Nonetheless, we seek to protect the integrity of our site and welcome any feedback about these sites.

Google's advertising requirements can be summed up by Google's Advertising Principles. They are put in place to provide a positive experience for users. https://support.google.com/adwordspolicy/answer/1316548?hl=en

We use Google AdSense Advertising on our website.

Google, as a third-party vendor, uses cookies to serve ads on our site. Google's use of the DART cookie enables it to serve ads to our users based on previous visits to our site and other sites on the Internet. Users may opt-out of the use of the DART cookie by visiting the Google Ad and Content Network privacy policy.

We have implemented the following:
      • Remarketing with Google AdSense
      • Google Display Network Impression Reporting
      • Demographics and Interests Reporting
      • DoubleClick Platform Integration

We, along with third-party vendors such as Google use first-party cookies (such as the Google Analytics cookies) and third-party cookies (such as the DoubleClick cookie) or other third-party identifiers together to compile data regarding user interactions with ad impressions and other ad service functions as they relate to our website.

California Online Privacy Protection Act

CalOPPA is the first state law in the nation to require commercial websites and online services to post a privacy policy. The law's reach stretches well beyond California to require any person or company in the United States (and conceivably the world) that operates websites collecting Personally Identifiable Information from California consumers to post a conspicuous privacy policy on its website stating exactly the information being collected and those individuals or companies with whom it is being shared. - See more at: http://consumercal.org/california-online-privacy-protection-act-caloppa/#sthash.0FdRbT51.dpuf

Our Privacy Policy link includes the word 'Privacy' and can easily be found on the page specified above.

You will be notified of any Privacy Policy changes:
      • On our Privacy Policy Page
Can change your personal information:
      • By logging in to your account

*How does our site handle Do Not Track signals?*
We honor Do Not Track signals and Do Not Track, plant cookies, or use advertising when a Do Not Track (DNT) browser mechanism is in place.

Does our site allow third-party behavioral tracking?
It's also important to note that we do not allow third-party behavioral tracking

*COPPA (Children Online Privacy Protection Act)*

When it comes to the collection of personal information from children under the age of 13 years old, the Children's Online Privacy Protection Act (COPPA) puts parents in control. The Federal Trade Commission, United States' consumer protection agency, enforces the COPPA Rule, which spells out what operators of websites and online services must do to protect children's privacy and safety online.

We do not specifically market to children under the age of 13 years old.
Do we let third-parties, including ad networks or plug-ins collect PII from children under 13?

*Fair Information Practices*

The Fair Information Practices Principles form the backbone of privacy law in the United States and the concepts they include have played a significant role in the development of data protection laws around the globe. Understanding the Fair Information Practice Principles and how they should be implemented is critical to comply with the various privacy laws that protect personal information.

In order to be in line with Fair Information Practices we will take the following responsive action, should a data breach occur:
We will notify you via email
      • Other
Within 300 days

We also agree to the Individual Redress Principle which requires that individuals have the right to legally pursue enforceable rights against data collectors and processors who fail to adhere to the law. This principle requires not only that individuals have enforceable rights against data users, but also that individuals have recourse to courts or government agencies to investigate and/or prosecute non-compliance by data processors.

*CAN SPAM Act*

The CAN-SPAM Act is a law that sets the rules for commercial email, establishes requirements for commercial messages, gives recipients the right to have emails stopped from being sent to them, and spells out tough penalties for violations.

We collect your email address in order to:
      • Send information, respond to inquiries, and/or other requests or questions
      • Process orders and to send information and updates pertaining to orders.
      • Send you additional information related to your product and/or service
      • Market to our mailing list or continue to send emails to our clients after the original transaction has occurred.

In accordance with CANSPAM, we agree to the following:
      • Not use false or misleading subjects or email addresses.
      • Identify the message as an advertisement in some reasonable way.
      • Include the physical address of our business or site headquarters.
      • Monitor third-party email marketing services for compliance, if one is used.
      • Honor opt-out/unsubscribe requests quickly.
      • Allow users to unsubscribe by using the link at the bottom of each email.

If at any time you would like to unsubscribe from receiving future emails, you can contact us by email at AnneIrene@novamedia.nyc

** Contacting Us

If there are any questions regarding this privacy policy, you may contact us using the information below.

novamedia.nyc
481 Van Brunt - 7D 
Brooklyn, New York 11231
USA
AnneIrene@novamedia.nyc

Last Edited on 2018-10-26

