* Jacques Bertrand 

Born and raised in Paris, Jacques left the city at age 19 for the south of France where at med school he discovered the design of the human body.The functionality of the lungs, the power of the heart, the connectivity of the muscular system, and all the body's coherency inspires his work in VR. Back in Paris, he began studying at Ecole Bleue, mastering architectural design and experiencing the world through his deep understanding of the discipline. Along the way he became an expert in Blender, the most complex 3D software environment driving virtual reality asset creation.

In the summer of 2017, Jacques arrived in Brooklyn and quickly became one of Nova's founding members. Thanks to his intricate understanding of brand creation, the story of Nova deepened. Its 3D logo and graphic charter were born, and its image solidified. Novamedia.nyc features Jacques' hand-crafted visuals, each inspired by his understanding of design, advanced technology, and extended reality as an emerging market.

He recently, under the Nova brand name, designed each of the characters for a Google-backed immersive 360 experience called Armonia. Only as XR begins attracting more artists of his caliber will it blossom.

* Joe Mecca
After graduating with a degree in marketing from Purdue University, Joe returned to the northeast to work for Clear Channel as an account executive, selling sponsorships direct to brands. With an average of $1 million in sales per year, Joe led execution of mutli-platform campaigns (events, radio, web, mobile, video) and was the point of contact for clients. His role evolved into innovating tech integrations for programming and commercial content, before departing for extended travel to Europe and the Middle East.

In 2016 he again returned to New York and tried virtual reality for the first time. Instantly recognizing it as the future of media, Joe began a virtual reality studio, Nova Media, out of his apartment, and without capital. While assembling a team, Nova bootstrapped its business, producing and developing XR software for individuals and multinational brands. Today, Joe and Nova continue to create bleeding edge content from their studio in Red Hook, Brooklyn.

Among the qualities that make Joe a natural fit for the CEO position are his ability to identify talent in others and motivate them to produce for the company within the realm of their skills and interests. Philosophically, his belief in the power of the mind endlessly empowers him to cast a positive outlook through circumstances both bleak and favorable. 

He has been leading media campaigns ever since his time at Purdue, where he wrote for the Greek Newspaper. He went on to be the sales director and publisher, expanding circulation from 6,000 to 17,000 weekly, growing sales from $10,000 in annual revenue to $25,000.


* Kyle Kesses
Six months after graduating from Fordham University, Kyle became a writer and on-camera broadcaster for the New York Yankees. In his final season, as part of a 5-person production team, he wrote and voiced an Emmy-winning episodic series in 2016.

During extended travel through Latin America, he wrote his first manuscript, a 7-part book of short stories, each chapter introducing the reader to characters who are meeting for the first time. The book exists among their homes, minds, and transience as they interact with death, lust, love, violence, and fear.

Returning to New York, he met Joe at the start of 2017 and discovered VR. The experience resonated and sent him on an ensuing research journey through the history of media and the evolution of mass human connectivity, a journey that led him back to Nova. He became the team's writer and next co-founder, establishing its marketing philosophy and passion for human-to-human connection.

With an affinity for language and voice, Kyle simplifies complex concepts into comprehensive writings, bridging many divides among artists, engineers, and businesses.

* Thomas Binetruy 
