* Web Text 

[Begin: 4:13 PM Sept 18]
[End: 

Start today with Public Relations part of the website. Begin with Kristin's writing/LinkedIn page. Intro to one of her articles.. I developed the post below in 2014 to argue the case that public relations is more than media relations. This is not to say that media are not important. In fact, I spend much of my time at the Logos Institute for Crisis Management & Executive Leadership working with executives to be more effective in their interviews and presentations - with press or other important stakeholders.

** Public Relations
Don't simplify PR as media coverage

1) Pitching 
2) Managing Inbound requests 

I also believe whole heartedly that it stands for personal relationships, which are cultivated and sustained through strategic communication.

PR is technical stuff and at the heart of it are real people.

Dove was able to connect with the brand with global stakeholders in a powerful way that went far beyond products.This is the focus of public relations planning. 

It helps support personal relationship on behalf of companies, brands and leaders by saying the right thing, in the right way, at the right time, to the right stakeholders.

The importance of brand awareness – what your company is putting out and more importantly, how it will be received

JetBlue was a pioneer in this space, turning to YouTube in 2007 after bad weather grounded passengers on Valentine’s Day for hours and spurred the cancellation of more than 1,000 flights. According to a case study published in AdWeek, “that early use of a social channel, along with JetBlue’s general openness and willingness to take responsibility, helped it soar above the media circus and resume its steady course as a consumer favorite.”

...

[Begin 12:56 AM on Sept 18]
[End 1:30 AM Sept 18]

I am working 10 hours on website text this week. Here are the areas of the site that need the most work 

** Community Page 
The text for this page is ready to be posted (and will expand as we log studios on trigger). Need to schedule meet with JB to add company logos and arrange them. 

** Medical 
I will take some of the text from the XR Medical "Market Intro" doc and push it to our "Medical" section. 

** Retail  
Do the same with some of the text from the XR Mall business plan, push it to the retail section. 

** Collaboration 
Source Arcane Reality, Gaddie, Michael Saunders, Bracey, Jon Clinken, Nermeen for these concepts: 

1) Producing a project for a client requires collaboration with partners 
2) Creating the scope of the job 
3) Reaching out to trusted studios, devs, designers, etc. 
4) Collaborating on-site in Red Hook
5) Working with them as we would a client

** XR Marketing 
This will be a combination of our Nova digital strat and our marketing strategy embedded in the XR Mall business plan. Also to be included is payment systems and the way they will influence in-app purchasing in VR. 

** Public Relations 
Re-write this text. Imagine how PR branches will use VR (Source knowledge from Yanks PR team and from Kristin Johnson)    
https://www.linkedin.com/pulse/pass-pitch-defining-value-pr-kristin-johnson

** A frame 
Should be added to our programming site. Set up 1 hour with Thomas to create the 

** Resource Center 

** Basic Knowledge 
Re-written 

** Publications 
1) Market intro for XR Medical
2) Market Research part of XR Mall

** Design 
Meet with Jacques and take inspiration from XR Mall Design strat

** Develop
- Blockchain 
- Cloud computing 
- Live Stream 

** Deploy
Needs a lot of work 
