* Web Text 

** Design 


[start 6:40 - 7:20]
[start 7:40 - 

*** Intro 
The Virtual World is introducing a new brand of design. For the first time we are integrating the principles of real-world architecture with the limitlessness of digital software. As we build customized Virtual Worlds spanning across industries, we're are realizing the limitlessness of this platform. We're also coming up against challenges never-before-encountered. We start small and end big, begin with a viable concept that can scale. 

*** Concepting 
This is the first phase of VR design, the foundation of the project. Here we consider: 

*1) The Brand's Identity:* What problem is the brand aiming to solve by expanding into VR?

*2) The Audience:* Who is the brand aiming to reach? 

*3) Reaching that Audience:* On which channels and platforms is that audience likely to exist?

*4) The User Journey:* Based on answers to the above questions, we determine the details of the experience, the user journey. How does the experience begin? What does the user see, hear, and feel? What actions are they prompted to take? What is the lasting memory that stays with them once it's over? 

In VR we can build innovative digital worlds with their own physical laws, or we can build simple 3D enhancements of the brand's existing strategies. This is the balance we must strike in VR design.

*** Designing Physics
The finest VR programs are built in collaboration between 3D designers and 3D developers. The possibilities of VR allow the design team to think in limitless terms, yet they must consider the more complex their designs the more resources needed during integration with the development team. 

Designing a Virtual World is telling a story through an experience of shapes, colors, lighting, and movement. Throughout the experience the user will move through a progression of digitally designed spaces. Each of these can serve as their own marketable assets. Consider these spaces akin to the rooms of a home. The price of building the home will increase based on the increase in demand for resources.  

*** New Design Components 

*** Our Process

Concept is really important 


the design part of the website needs to explain to the client the process of what happens when we work for them. it must explain the possibilities of design in vr. Design is a broad term. some things are designed event though the final results are not a "design" 



*** Interface 

*** Architecture 

*** Design 

considering the user story is the first part of the design process. according to this user story, we design the world.

1) concept
2) user story 

Then you start designing the concept according the user story. there are many different layers of design. 

1) Architectural deign 
- there are also designs within this architecture
- There are similarities with the architectural design and the real world and there are differences as well.  

2) Graphic design 

1) what is design 
2) what is design in vr
3) what is the process

*** Nike 
1) Realized the logo was a great structure for a vr architecture 
2) we created the models and imagined their use 
3) 

**

* Intro to vr design 

Designing for vr is something different. the inifinite gallery for example with the glass above the ceiling of the gallery. in vr this is no necessary. but for immersive purposes, we needed the user to trust something so we must add these parameters. sunglight, rainfall, shadows. You need to be aware of all the possibilities and balance them out to create the right experience. the right experience answers the user story and the concept that was chosen before. you need to konw where to go and where to stop. You tell a story with your design. as an architecture can be a stroy, you tell the story through the shape and you lead the story with your architecture and designs. the architecture of the experience leads you from one platform to the next. Not only does this guide you through the expierence, you also feel the essence of the brand through the design. these sections through which you walk are purchased. this is the inventory or real estate purchase in vr. to tell a story with architecture you must focus on the concept, sensitivity, the shapes, light, texture possibilities. the important thing to understand is that it is limitless. you don't need to again be inside an architecture resembling brick/mortar or the real world. 

** physics simulation 
1) you're entering a world of object, design, and architecture 
2) you have control over the physics.
3) smoke, particles, rainwater, flow of traffic 

** design elements added in vr 
1) no gravity 
2) light is controllable  
3) freedom of movement needs to be understood 
- this is a form of expression 
- when partnering designers realize the possibilities it will spark their creativity 

** our process
1) we start with a concept
2) design is related to the marketing strategy with social media, etc. 
3) when we crate the design concept we think about how to reach people and hold their attention 
4) how do they share it

[lets pickup here with the parameters in jb's design strat]

you have to take all of these parameters into consideration to enhance your desig. 

1) what is in the design - landscape 

2) you inside the experience 

3) what it causes the user to imagine

You can create design and then these parameters will

1) functionality 
2) efficiency of the application itself 
- you have to acknowledge it's limit. In the mall you have 3D models and you can step inside. You can't design something totally crazy or merge too many concepts together because there is performance to consider. You may have high poly or low poly 

** Audience 
The audience of people who use VR can be divided into four broad categories. 

1) Innovator (bracey) 

2) Student (design) 

3) Tech enthusiast family 

4) Gamer (steve) 

[Begin 7:00 PM Sept 18]
[End: 7:30 PM Sept 18]

** Design text with JB on Skype
The importance of Design in Virtual Reality 

*** Jb has written Design text to be edited 
The shopping center as
that intelligent living organism

The mall could become a commercial cell developer, creating a living organism. In the analogy with the living organism we retain the fact that it is evolutionary, that each cell can die or be divided or even depend directly on other cells and even interact with each other in the way they interact with each other. the living world. the organism at the origin of the commercial center would be the brain, the sectors of activity of the organs, and the consumers of the cells. All of them forming a living being where everyone is vital.
 Some cells could move within the center, some could be ephemeral (pop-up retail space), some would be fixed and would form the backbone of the shopping center. A framework that would act directly on the other "members" of the center themselves composed of cells with different activities (without creating a segregation of activities within the member)
We would thus see the birth of a small town, a small living being that can evolve morphologically and functionally over time.
Thus we would place the commercial actors (of different scales) as active customers of the commercial center itself. That is to say, a large group could rent a trading cell that it would place in the center at its convenience as well as temporarily. (even the premise of commercial space or ephemeral marketing) It could even decide to make a partnership with another actor of the center to promote a product together. (Example a ready-to-wear store makes a partnership with Samsung to be able to view on either the entire collection with a virtual reality headset)

Consumer Advantage:

- Its commercial center does not have the same morphology during the year, that is to say that the aspect of the commercial center respond directly to the market environment, and to the seasons (like any other organization alive) So we do not get tired anymore.
- It would be in position (thanks to the technology and the applications) to promote itself by a vote the cells that it wishes to be born within its commercial center (the cells being of different nature, relaxation, sale, various activity .
- Its close link with the activity of the shopping center makes it more important with regard to tradesmen (a cell behaving badly with the clientele is likely to die) analogy with the cancer cell of an organism which is killed rightly by other cells.
- By this, all consumers (individually comparable to the smallest cells in the set) become by their numbers a type of cells very important and powerful.

Commercial actor advantage:

- Commercial players would have the freedom to partner with other brands to promote their products more effectively.

- The possibility of temporarily extending their activities allows them visibility no longer at a single place in the commercial center but at their goodwill in several places. (The customer who does not pass their flagship can pass their beautiful cells and then head for himself to the flagship.

- Small players or local entrepreneurs could also be customers of the shopping center by renting cells at attractive prices, thus reducing the risk of failure. (If the contractor fails the cell is tidy and available) and expanding the business areas within the center.

Advantage agency shopping center:

- Low investment because the center and evolutive and all the cells is not necessarily created from the beginning (therefore lower risks)
- He can also manage internally to act on the cells and the frame, (by the same analogy he would be the brain of the commercial center)
The shopping center would become a kind of flagship mall that will attract flagship (large group) and smaller activities (catering, crafts, culture)
- It has through the vote of consumers on the cells they want to appear in the center, a direct return on the health of its center.

...

[Begin: 4:13 PM Sept 18]
[End: 4:35 PM Sept 18]

Start today with Public Relations part of the website. Begin with Kristin's writing/LinkedIn page. Intro to one of her articles.. I developed the post below in 2014 to argue the case that public relations is more than media relations. This is not to say that media are not important. In fact, I spend much of my time at the Logos Institute for Crisis Management & Executive Leadership working with executives to be more effective in their interviews and presentations - with press or other important stakeholders.

** Public Relations
Don't simplify PR as media coverage

1) Pitching 
2) Managing Inbound requests 

I also believe whole heartedly that it stands for personal relationships, which are cultivated and sustained through strategic communication.

PR is technical stuff and at the heart of it are real people.

Dove was able to connect with the brand with global stakeholders in a powerful way that went far beyond products.This is the focus of public relations planning. 

It helps support personal relationship on behalf of companies, brands and leaders by saying the right thing, in the right way, at the right time, to the right stakeholders.

The importance of brand awareness – what your company is putting out and more importantly, how it will be received

JetBlue was a pioneer in this space, turning to YouTube in 2007 after bad weather grounded passengers on Valentine’s Day for hours and spurred the cancellation of more than 1,000 flights. According to a case study published in AdWeek, “that early use of a social channel, along with JetBlue’s general openness and willingness to take responsibility, helped it soar above the media circus and resume its steady course as a consumer favorite.”

...

[Begin 12:56 AM on Sept 18]
[End 1:30 AM Sept 18]

I am working 10 hours on website text this week. Here are the areas of the site that need the most work 

** Community Page 
The text for this page is ready to be posted (and will expand as we log studios on trigger). Need to schedule meet with JB to add company logos and arrange them. 

** Medical 
I will take some of the text from the XR Medical "Market Intro" doc and push it to our "Medical" section. 

** Retail  
Do the same with some of the text from the XR Mall business plan, push it to the retail section. 

** Collaboration 
Source Arcane Reality, Gaddie, Michael Saunders, Bracey, Jon Clinken, Nermeen for these concepts: 

1) Producing a project for a client requires collaboration with partners 
2) Creating the scope of the job 
3) Reaching out to trusted studios, devs, designers, etc. 
4) Collaborating on-site in Red Hook
5) Working with them as we would a client

** XR Marketing 
This will be a combination of our Nova digital strat and our marketing strategy embedded in the XR Mall business plan. Also to be included is payment systems and the way they will influence in-app purchasing in VR. 

** Public Relations 
Re-write this text. Imagine how PR branches will use VR (Source knowledge from Yanks PR team and from Kristin Johnson)    
https://www.linkedin.com/pulse/pass-pitch-defining-value-pr-kristin-johnson

** A frame 
Should be added to our programming site. Set up 1 hour with Thomas to create the 

** Resource Center 

** Basic Knowledge 
Re-written 

** Publications 
1) Market intro for XR Medical
2) Market Research part of XR Mall

** Design 
Meet with Jacques and take inspiration from XR Mall Design strat

** Develop
- Blockchain 
- Cloud computing 
- Live Stream 

** Deploy
Needs a lot of work 
