
* Infinite Gallery WEbtext

Showcase in the Infinte Gallery!

Bring your art into Virtual Reality.  Tell your story in the infinte gallery.  Displays your designs like never before.  Sell directly to consumers by linking payment methods to your gallery.

 
 Much like in the late 90's and early 2000's when Paypal and other online currency exchange programs created a means through which the user could buy products right from home, your guests will now be able to purchase paintings from directly inside VR.  

 100 years ago F.W. Woolworth adjusted the way customers interacted with products. Throughout the history of American drug stores, whether it was a can of soda or container of toothpaste, the customer had to request the product from the clerk. The clerk would then go and retrieve the product from the back of the store. Then, in the early 20th century, Woolworth turned this concept inside out at his "five and dime" stores around the country. He brought the products out from behind the counter and displayed them on shelves, so the customers could touch them, hold them, and develop a heightened connection with them. This little idea changed retail forever. Going forward - and to this day - this format is the default arrangement in retail stores around the worold.

Virtual Reality is the F.W. Woolworth of the internet, bringing all the products from behind the screens to our hands to be held and understood stood more deeply.  


** Philanthropy

 We provide education and access to those with less opportunity.  May it be teaching Red Hook West Housing Project's youth how to code, or brining internet and PCs to under developed villages, we are on determined be the change that betters the world.   
