***** *Blockchain*
    
A distributed database that maintains a continuously growing list of ordered records called blocks. Each block contains a timestamp and a link to a previous block. By design, blockchains are inherently resistant to modification of the data — once recorded, the data in a block cannot be altered retroactively. Through the use of a peer-to-peer network and a distributed timestamping server, a blockchain database is managed autonomously. Blockchains are "an open, distributed ledger that can record transactions between two parties efficiently and in a verifiable and permanent way. The ledger itself can also be programmed to trigger transactions automatically

VR on the Blockchain  

Kick it with me a minute here as we explore how a decentralized business model for a Virtual Reality experience powered by blockchain.  Simply all value of the app will be represented in tokens, and here is a gentle introduction to digital tokens.    Over the last few years investments in digital currency start-ups broke only 1 billion US dollars.   Yet, in the last four months 250 million  additional dollars were raised by tokens, as in crowdfunding on blockchains for the same currency that is used inside the app.   With the tokens easily converted to local currency they have real value.  However, it is probably just a few pennies of value today for user, but if the app continues to succeed then the value of the tokens will increase.   Everyone is directly incentivized to participate and deliver quality.  

So if we build a VR on a blockchain, we’d be looking for the people’s contributions to improve the world – or maybe even build it entirely.  In ways, similar Second Life, but as far as we know though Linden Labs is bringing the virtual world to virtual reality there is no word on it being a blockchain build, and why would it be?  They already have their community; this would be something designed from scratch.   The important take away and reason for the comparison is that -  The users would contribute the content.   Traditionally, especially when thinking about social media, we think about creating and sharing text, posts, photos, GIFs, Memes, videos and such.  However, in virtual space content may very well be your mere presence and participation – or you can make an entire building with a moat around it.    We the people and our actions are the content in VR, as our body is part of the media and our decisions drive the narrative.   We are the story.      

Being a part of the story allows us to strengthen out community, which is the greatest challenge online.   In Virtual space the building of community will be different and the best considerations is the examples we already have.   If you think of the VR environments today that have social elements, like The Rec Room, Alt Space, Destinations, Hover Junkers, we’re playing mini-games, having conversations, and generally just horsing around.   Its fun to hang out with other people, even if they are strangers.   Sharing the experience heightens the experience (or in some cases, is the entire experience). Hover Junkers is serious fun, I find myself ducking, jumping and calling out war cries from the center of my living room, but only if there are other participants.  Shooting the sandman is OK but If there are not other people to point and aim my grenade launcher at, I quickly leave.    The Rec Room is great for shooting basketball hoops and playing paintball, but if no body is there to toss the ball back when I miss my shot or chat with me about the new updates in the world, I find myself rather board.  I’ll hang alone for some time and adjust my avatar’s wardrobe and hairstyle for optimized virtual selfies, but that only takes me a few minutes, then I log out.   Destinations is the epitome of new-age digital exploration, virtual pioneers wandering unknown lands.  Again this is plenty more interesting with a friend to laugh along side you and wander Where the F are we?. 

We “use” the VR gear and “play games” but as I see it we are exploring the new frontier of cyberspace, not merely using hardware and playing games!   Everyday it expands.  Every world built is a new land to mine for fun.  But what if our exploration rewarded us with more than experience but a form of quantifiable gratitude for the contributions of exploring?   This would be much like the explorers of the 1500s who received a percentage of the commerce that between lands they discover and their patronizing nation.  We simply reward findings that are beneficial to the community.   

Imagine a world that periodically released more clues, more assets, more tools and tricks for you to play with.   The more you participated the more credit you earned and the more access you received (assets/tricks/et cetera).   Your credibility and your inventory would both go up, which are worthless in objective reality, but in this blockchain VR world have value.  If your experience progressively got better with your continued participation you’d be regularly incentivized to participate.  This is how social media claims to work today “we are collecting data to improve your experience”.  Which we all want, and maybe they are improving it with the data collected, but the amount of improvements compared to the data mined from us is a tough calculation to make and probably not in our favor.   Blockchain is open source and we see all the details and if we do not like the way things are working we copy and paste the code and rebuild elsewhere!   We have the chance to build a new world, fully democratic, by making a VR powered by blockchain.

What would that world look like?  How would we design it?  I’d start by mining the universities for their most enthused and brightest.   Seniors will soon have free time on their hands and be interested in new opportunities.   We can do a call for designers, graphic artists, animators, sketch artists, UX, software engineers, developers, programmers, network engineers and on until we have enough smart people to produce our frame work. 

We only need to build the foundation, design the rules and provide the tools for the community to flourish.   If we let the participants run free, as they are part owners of the world, too, then we will achieve more.  With the first working iteration up and available for people we will learn how to improve, just like any first draft or working prototype.  If we release our VR blockchain and begin to get a real consensus for mechanisms independent of third parties who have money on their mind.  

Because of the open web technologies such as Web GL (Web Graphics Library) to render 3D via the browser we uplift design, distribution and experience, and can do so in an independent economy based on cryptocurrency.   

Essentially, virtual worlds and their economies could be bootstrapped from scratch by anyone connected person across the globe. 

Today we have a few million people using VR/AR headsets and that number will steadily grow over the months and years to eventually follow the same market trajectory as the smartphone.   In Steampowered game store, which is up over 10 million users per day, we can promote the project, share in forums and stir up conversation amongst the idea audience – innovators and early adopters.    Well, some of them are just gamers, but they are a great audience to get involved too, because they have an intuitive understanding of how to use VR.   We release the game for free, obviously.  Not just because it is good for promotion but because much of the allure to blockchain enthusiasts is the inclusiveness the communities.   Then, we can surely track the stats, but those are open to the public.  We will maximize the tools with regular maintenance and the rest is up to our community.   There is little or no censorship, and when building in 3D space that can be a frightening notion. 

Soon, people will be building homes like in Simcity, write pages and blogs about their favorite topics to share in the downtown library or pin up in the main square, artists will sculpt art, design cars to race and essentially build whatever they wish to have in their VR space.   Our job would merely be to create the tools for doing so.     If we let the people build the environment, how could they have any complaints?  The early settlers will set the standards and rules of the land, based on how much each contributes.    There will be little or no censorship due to the nature of blockchains. 

In the future, regulators might write laws forcing limits on what we can build, where when and how.  However, can you enforce these regulations on a decentralized network?   A growing VR blockchain will be forever preserved as a wild west and yet the ultimate democracy.    

VR blockchain would serve as an environment of true democracy.  We haven’t had true democracies in our physical world because it is not practical to count every person on every decision, it is simple not manageable with the tools we have and the interest people take.   But a VR on the blockchain is different for two reasons.  First, we have the computational ability to track and count everyone’s voice.  Second, the people are taking an active interest, at least to stat, and not just being born into the land they live, as we are today in the physical world.  

The doors would be open to anyone around the world.  Someone from Eastern Africa can be working side by side with someone from Ireland to create a new landscape.  And the owners of that landscape aren’t the East African and Irishman, but everyone, as the world would be free for users.   The blockchain is giving us an Internet of Assets (IoA).   

This decentralized form makes for a complex legal future.   What you can count on is that we will not have built the only VR on the blockchain, there will be many!   Just like apps today, thousands of apps will be successful and thousands will not amount to anything.   This will be true again with Blockchain VRs, but with one major difference.   Instead of getting in on Uber early, or Facebook while it was edu-only making you trendy and in-the-know, it would make you actual money.    Getting involved early would be rewarded greater than getting involved later and your wallet will notice.  

A VR on blockchain can form the ultimate democracy with an independent economy and freedom from the regulation of any governing body outside of itself.   We can build new worlds, not just physically-virtually, but economic and power structures are shifting, too.  Humanity is evolving and tomorrow is only the beginning.  

***** *Cryptocurrency*

A digital asset designed to work as a medium of exchange using cryptography to secure the transactions and to control the creation of additional units of the currency. Cryptocurrencies are a subset of alternative currencies, or specifically of digital currencies.

# How ^ makes XR
