*** Publishing
**** Distribute
Our recommendation is to approach distribution similar to the approach of any other content you might create. The key is still putting the correct message in front of the correct audience at the right time. 10 million people in the US use VR. As early adopters, they will influence 50% (or more) of the market.   

[[url of early adopter chart]]

***** Promotion
****** Paid
- advertising space
- Native adverts
****** Owned
- homemade
- Social media handles
- SEO
****** Earned
- journalist sponsorship
- Partnerships
  + Studios
  + Publishers
  + Influencers

***** Audiences
****** Early adopters
They influence 50% of the market.  [to format graph]

[[image of people]]

****** Students and Early Influencers 
18-34, II $100k+, frequent traveler, experience-seeker, anxious to learn, highly impressionable, great networker, Fields of engineering, computer science, art + design, etc

[[image of people]]

****** Early Adopters + Innovators       
18-34, II $100k+, frequent traveler, influential, good networker,  Works freelance, at start-ups to or on project development teams, older Millennials coming into money and support only themselves. 


[[image of people]]

****** Youth + Young Families 
8-17, 34-49 HHI 200k+, frequent traveler, disposable income, educated, open mind With children in the house and careers in technology.  

****** Gamers

[[image of people]]

******* Data Review
- biometrics
- Analytics
- Distribution

# Side Panel close

**** Activation
- Pop up shop
- Permanent installation
