***** Photogrammetry

Photo detection, using the 2d features and then recreating 3d models with texture by shootring many photos.




****** *How it works*
******* Take photos
The most common and accessible is moving the camera around the subject.  Move around the object,  full lop in, raising your camera angle in increments of 5-15% degrees.   The more complex shot requires smaller incremental increases.  You need at least 2 or more photos for any point, and a 40% overlap is a good rule of thumb


automated turn table.    to work proprly.  perfect flat backgrund/  soft light from direction of the camera., jsuch as LED.  any clamping needs to be cropped out.  linear polarizing to light and circular polarize to lense, this will eliminate most highlights.

even light.   cloudy day or in shade.   eye level, middle, below and detailed shots will be put into the software and then look for tracking points.    

Open CL - listeed graphics card,  use C, then step back one core?   

Software you'll need:
Visual SFM (CUDA version if you use nVidia)
http://ccwu.me/vsfm/

CMVS For Windows
http://www.di.ens.fr/cmvs/

Meshlab
http://meshlab.sourceforge.net/

Here is the rock in full 3D after cleanup and retopo.
https://skfb.ly/Cxxp

If you'd like to use my photos you can get them here (259MB)
https://www.dropbox.com/s/g9rxzs59lt5...
s
This is the original tutorial I followed which has a ton of information, but I wanted my videos to get right to the point.
http://wedidstuff.heavyimage.com/inde...
 
( translucent, reflective, shiny, transparent will not work,  catching algarityhms will fail)

******* Software to detect common points
******* Reconfigure geometries and textures
******* export to engine
