

** Community

*** The Camp David
 Our friends at The Camp David are a creative co-working space in Industry City, Brooklyn.  They have an exceptional space with top-notch amenities rannging from content studio, to gym access, concierge, full-service cafe and more.

They are interested to bring exceptional VR content to members and we offered to help them connect with top developers, studios and though-leaders in the XR space.   

To learn more about how you can get involved, please reach out to Christine at Christine Oakes <christine@thecampdavid.com>

*** Ethiopia

**** About
Leyk and Hanna are.....

Reach out to them at:
| Phone    | +251 96 218 0324 |
| Telegram | @Leykb           |

**** Testimonials

These two are absolutely fantastic hosts.   In my many travels I haven't met a couple quiet like them, knowledgeable, interested, inspired and dedicated to teaching us about Ethiopian culture, history and modern experiences. Thanks a million!  Can't wait to visit again :)

/Reach out to Joe at mecs13@gmail.com for more information about his experience/

 

**** Fun Facts from Leyk an Hanna about Ethiopia

Did u know that Ethiopia has 13 months?

We fed 1600 homeless people today and donated clothes and hygiene products

