* Design   
  
Design is the intermediary between inforation and understanding. 

** Process 

The pre-production process is the blueprint for development.  Clearly defining goals and success metrics shepards success.  Defining the objective and limitations focuses research and increases effeciency.   Prototypes will iterate faster and technical debt will be minimized.  Organization is the father of creativity. 

*** Parameters
Setting parameters lays a foundation to structures strategy.    Set a clear and simple objective.  Clarify deadlines, resources and performance metrics.  These parameters keep the vision clear, resources optimized and the team on task.  

*** Research
Research creates new knowledge.  We partner with academia by providing XR world designs, interfaces and stories to live out in their XR productions.   

Seek. 
  Find. 
    Internalize. 
           Surmize. 
               Apply. 
                 Refine.
                  Innovate.

*** Prototypes




** Strategy

*** Budget   
Budget can drive scope or scope cand drive budget.  It is far better have a small experience working smoothly than a big experience causing headaches.  You should budget for $50-$100 per hour of labor, high to low level programming, respectively.  Defining the budget enables us to provide you with a financial strategy and options.  See examples here:  :F


Hotels: Brown - Financial Strategy
http://github.com - automatic!
[GitHub](http://github.com)


Festival: Pepsi - Financial Strategy
http://github.com - automatic!
[GitHub](http://github.com)

Music: Pandora - Financial Strategy
http://github.com - automatic!
[GitHub](http://github.com)

Relocation: Dwellworks - Financial Strategy
http://github.com - automatic!
[GitHub](http://github.com)


*** Scalability
According to the budget and the ambition of the project, we advise progressive development, starting with an MVP.  Defining the multi-year plan up front is necesarry to scaling at the lowest possible cost.   

XR techologies are evolving at an exponential rate.  To scale efficiently plan, test and iterate with fluidity. 

*** Communicate Athmosphere 
The global feel is expressed in 3D renders, models, images, and spatial audio.  XR is a multi-senspry experience.  Immersion is earned through compelling visuals, inutive interfaces and 3D audio.  These create spatial cognition and a sense of "presence". 


*** Comfort 
Comfort is everything.   Presenting the player with an environment and an experience they want to return to is your number one objective as a designer.  The user experience is everything, and their comfort is in the developers' hands.   There is a strong psychlogical need for comfort, especially when travelling somewhere new. 

*** Interface
Intuitive interfaces consider layer dept, and transparency.
It is really important to consider layer depth and trensparency in VR.
The field of view is 360 degrees from the user perspective but another parameter is the depth, information can appear at different depth and transparency could make multiple visible at the same time. 

*** Control
following the focus of your eyes, using the voice, or hardware controllers. 
Basicly you have to forget the way you control, it has to be natural so that you focus on the result of the control and not how to execute it. 
Action has to be really fast, and the less step as possible. 
For example you can drag and drop with your eye but you can't close your eyes to indicate a click otherwise you loose the immersion. 

*** 3D audio

Audio, musique, environement sounds are really important for the user, anywhere you are, anything you experience, you hear noize even without knowing it. The reverse, a absolute silence is actually strange,
Music and voice coming from different perspectives can guide the user, you go clother to the sound or you run from the sound. 
Like music in movie, it will increase the power of sensations,

*** Movement 

Movement is a complexe question in VR, the user is not able to walk for hours, but the world is hours walk big.  Are you building something that people is in control? Or are you moving the character in VR? The approach you’ll take in the movement will influence your VR experience. 


*** World

*** Interface'

*** Story


iConcept development
- game designers
- subject matter experts
- instructional deigner


*** Blender:

Blender is a free, open source 3D modeling software tool - a complete squite supporting the full 3D creation pipeline from rigging to animation, simulation, rendering, compositing, motion tracking, video editing and game creation. Blender is a versitile and powerful tool for design.   


*** How do we use it in VR? 

We use Blender in XR to model objects and environments. ontrol of textures, lighting, size, color, shape and so on influencea players' sensation and mood.

Design is key to forget you are consumig media and having a sense of presence.  


optmizes VR's potential.   


Desig concepts 

To model VR objects.   to create textures.  deisgn conpeties and world design.  create the look and the feel the sensations, envirnoment you're in.   all the aestthetics.    

create complex 3d models then import them to a game engine.   You can easily and better inderface.

See it before you buy it.

Hold it before you buy it.

Use it before you buy it.


Touch feel and play with designs that would be in a VR headset but on 2D screen.  

 tool to model 3d, open source, free


computer aided design


how all the piece come totogether.
****** educational piece

- use VR
- It lets you understand how you create the material, how you edit the process, how you cut, and 

media will be *interactive*.  Visitors will engage their environment, chage the world around them, and be a part of the story.  Thiiss engagement drastically increases impact

- The experience is *netowrked* meaning it is connected to other real people. You and your friends will travel the customized worlds you design /together/.


Benefit
Uniwuw advantage/ 
- could not knw this feeling without beining in VR


seeing theh shadw and the floor 

10-15 diferent renders for this roject.
do reallly big douments for arhcietuers 


-  Bust stop

* Development

** Introduction

 The VR we develope is *Programmable*  The virtual expereince can be manipulated through inputs, such as code, player interfacing or phsyiological behaviors.  

Virtual Reality is an *interactive* software simulation, with positional tracking and player input.  Find below some of the many disciplines that make XR (virtual reality).


** Game Engine
A *game engine* is a software framework used to create interactive 3D media (XR).  We build XR in game engines.  Game engines enable all the features of the internet from social sharing to payment.  

Game engines equip developers to custom design virtual environments, program players, goals and rules as applications shared and experienced throgh personal computers, mobile dvices and gaming consules. Game engine framework's core functions are to render 3D graphics, engineer physics/collision (and response systems) manage memoreym shread, and graph scenes.   

Nova economizes the process of virtual reality (XR) development by adapting game engine builds (software executable) to create new VR expereinces.   By developing with foresight producers save time and money.   

Game Engines enable comprehensive developmenwith all the features of the internet from collaboration to payment, in 3D.

*** Program examples:
**** Virtual World Build
text descrion (Technical, metaphysical, benefit)
**** Infinte Walker
**** XR Color
**** XR Music

***** KK 1 sentence description :KK: :WS:
- for all four programs
- 10 work max
- text descrion (Technical, metaphysical, benefit)
ma
* Artificial Intelligence

Artificial Intelligence is intelligence demonstrated by a machine.   The branch of computer sciences that studies AI research studies and developes machines to perceive the environment and make adjustments to influence the likelihood of success at achieving goals.  Machines are designed to mimic "cognitive" functions associated with human minds, like "comprehension", or "deductive reasoning".


Artificial Agents enhances VR through 
- Personalization 
- Generative design
- Contextual awerness
- Data indexing
- character engines


*** Personaliztion
**** What it is
**** how is used in vr
**** why thats good (makes them money)

*** Generative design
**** What it is
**** how is used in vr
**** why thats good (makes them money)

*** Storefront navigation

At the front of a store, or in a virtual world, you will ask an AI "butler" or "host" for information about the local area.  These bots will grow more and more expert in communicating with patrons and visitors.  Think about friendly chatbots on a website, but personified as a character.

*** Contextual awerness

*Contextual awareness* allows the machine to compare the query to known information.  For example, google maps knows your location.   If you press the blue dot (ask where you are) it compares this request to its knowledge of the map.  The computer has a small degree of contextual awerness.   

In Virtual reality When a AI character knows it's surroundings it will play more thoughtfully, making for better competition/collaboration and game play.  AI characters train through trial and error.  They record the context of the successes and failures and adjust to optimize likelihood for success.   

***** BS   how can we use this information in VR? :SS:
---- You can use this information for 3D shopping. remote focus groups for shopping.



We synch with the player's cell phone and they post their experience to social media.


**** BS AI with VR an Social? :SS:

*** Data indxing

Artificial intelligent algorthms to better index user data.   If information is better categorized it will be better read and understood.  We'll comprehend larger and large sums of data, especially very intimate information VR can fascilitate, such as body movements and emotional states.  

A semi-technical explanaition of the process is to track, collate, distill and visualize.

By visualizng the data of VR players through   indexing you wholistically understand the user's experience. The AI creates visuals of comple data in 3D, so you can move around and scale the data in real-size.  This engagement significantl increases comprehension.  

*** Character engines

In Virtual Reality (XR) develops "character engines" into the experience.  These engine the characters behavior and desicion making.   By programming learning algorythms your characters can remember information about you, your game play, and whatever else we teach it to... within reason.  They can be your virtual friends.

Intelligent characters make for better game play.  The user's experience is familiar and personalized.   When you allow visitors to customize their ento the way it did on the internet just after the .com boom. This is the first step toward selling your products directly through VR. You'll be able to sell anything you'd sell on the internet. 
vironment, feel ownership.  Intelligent characters increase experience affinity and replay-value.


**** Programs of Interest

- Live forever audio capture
- Professional Services

** Natural Language Processing

*** What the technology is
*** How it is integrated in VR

We will talk with the concierge — not with commands, menus and quirky key combinations —but using our own human language.   This is Natural Language Processing, a foremost technique for human-to-machine discussions.   

* Biometric Software

Biometrics refers to metrics related to human biological characteristics, including physiology nd neurology. In virtual reality biometrics are used to measure interest, entertainment and intent.   

By monitoring physiological cues such as skin galvenization, eye dialation, heart and breathing rate, computers infer and escrapolate further details about the player and their experience.

This enables us to remove the many errors and barriors that stand between user and feedback.By using bio-measurements we improve the storyline and pin point player's interest, displeasure, fatigue, excitement and much more.  

The seven primary emotions monitored in traditional commercial software is happiness, sadness, anger, contempt, fear, disgust, and suprise.


***** KK lab Live on biometric applications
      SCHEDULED: <2018-03-16 Fri>
- hwo do we use these physiological cues to improve expereinces
- quantifiably, why does this information matter?

* Blockchain 

A "block"-"chain" is a distributed database (or ledger) that maintains a continuously growing list of ordered records.  Some major blockchain features include: 

- Secure, private transactions
- Microtransactions
- Public, imutable record keeping
- Democratized administrative controm 
- General platform stability


Features, such as "smart contracts" allow us to host concerts in VR with secure micro-transactions.  An inumeral amount of people can attend concerts and experiences live with musicians and artists.  On a blockchain, you can charge them based on network contribution.  

Blockchain tech allows the users to exclusively own and control them content and platform the build.  


***** KK lab live blockchain and vr- very high level (elemenatary words and concepts) 
      SCHEDULED: <2018-03-16 Fri>
- highly technical
- describe the tech archeteure in paragraph form on a VR on the block chain

* Iot

The Internet of things (IoT) is the network of digitally conntected devices,such as home appliances and vehicles, that are conntected to the internet.  These devices are equipped with sensors and operating software, enabling remote access and managment.  For example, adjusting your beach house thermastat from upstate, or  recieving a text message notifying you the plants need watering (because your botany sensors noticed drought.  

Simulations of physical tasks allow for us to practice, minimize risks and scale profit margins.   Imagine remotely controlling construction machinerary.  By being in the simulation, apprentices can train without the risk of hurting themselves.   Experts can control machines remotely, cutting down on transportation costs.   Through the VR simulation one can navigate the controls to operate an actual piece of machinerary just as effectively as if he were int he machine itself, but from the other side of the world.  This is the "internet of things", which will quickly evolving into the "Internet of Everything" (IoE) and then the "Internet of Humans" (IoH).


***** KK lab live on simulations connected to physical world shit
      SCHEDULED: <2018-03-23 Fri>
- focus on how simulations save time and money

* Haptics

the communication of devices thhrough touch and feel, as a reaction to an action.  This is the science of applying tactule sensations to controllers to interact with computer applications.   


Add a visceral dimension to virtual expeirences and 3D environments, most frequently by applying vibration, or electrostatic shock.  By using ex-devices, like gloves, vests, shoes and so on, the player receives non-verbal, non-visual feedback from the computer. 

Virtual experiences that train seurgeons and athletes rely on haptic technology to train muscles to maneuver with better presicion.  Our hands determine hardness, shape, tempertaure, texture weight and more.  There is a lot to be undetstood through touch and haptics development is a major contributor to immersion.  


***** KK Lab Live on how haptics engage senses  
      SCHEDULED: <2018-03-23 Fri>
- and how those senses influence perception, desicion making, retention (learning)
- write as if it is all currently happening, not as if it soon will
- shout out companies doing awesome stuff

* Photogrammetry:	

Is the scanning, computing and rendering of 3D models through 2D photographs and distance differentiators.   By taking several hundred photos of an object from strategic angles we redesign and texture photorealistic objects and environments.

Photogrammetry conveys real spaces as digital simulations,  Think "immersive realism".

Re-creating real environments in virtual reality enables us to simulate travel and fascilitate training.  By maping locations 

**** Related Products:	
- Bloomaway
- 




*** What the technology is
*** How it is integrated in VR








***** KK Lab Live - how phtogram is being used in XR
- objective: communicate photogram's best applicatio gns in XR
- 1-4 examples of industry uses, max
- intro half technical half metaphysical
- body 75% technical, 25% creative charm
- conclusion metaphysical
--  ^^ test this approach o



related blog

* Cryptocurrencies

Global, anonymous, cash

... if you know what you're doing.   

Cryptocurrencies are a digital asset, secured by cryptography and designed to serve as monetary currency.   "cryptos" are renown for fast, secure, peer-to-peer transactions, developed on "blockchain" technologey.  

As a digital medium of exchange cryptourrencies are a convenient solution to buy or sell property digitally. Cryptocurrencies empower virtual worlds to have an economy. 

In 2001 economist Edward Castronova estimated virtual world EverQuest's gross national product (GNP) at $135 million.  Per capita, richer than India, Bulgaria or China.  Today virtual goods market is estimated well over $15 billion. 

The benefits of using crypto-currencies are security, speed, low fees, anonyminity, and more open markets. 

* Cloud computing

Cloud computing is the remote storage, access and control of computers.   A "cloud" is really just a server, and storing in the cloud merely means you are storing your data on someone elses' hard drive.  For example, iCloud is storing you data on Apple's hardware, instead of your own (locally).







** JB cloud computing graphic
- idea starter https://xenlife.com.au/wp-content/uploads/What-is-cloud-computing.png


*** What the technology is
*** How it is integrated in VR
*** Why they care (it maks them money)
	⁃	
	⁃	— Allows for remote storage
	⁃	— networked gaming
	⁃	— stream the VR game from someone else computer to yours
	⁃	— games are putting them all in the cloud, will run more smoothly
	⁃	— try an app before you download it
	⁃	— 
	⁃	
	⁃	

* The Web XR:

*** What the technology is
*** How it is integrated in VR
*** Why they care (it maks them money)

	⁃	— open and free platform
	⁃	— allows for more lightweight experiences
	⁃	— web XR framework, and can build anything in it
	⁃	— in unity you need to build from nothing.
	⁃	—
	⁃	
	⁃	

* Finite state machines

finite state machines are made of explicite states.    Imagine a simple video game character can be be in five different finite states, standing, walking, running, attacking, defending.   Each has its own commands and logic framework, when entering, enduring, or departing the state. States have rules tha indicate when they can transition and how.  For example the character must go from "standing" to "walking" before it can enter "running".

A "running" character will be less aware of their surroundings, while the "standing" character will be programmed to be more obervant for another character's attack.   Maybe the character can only enter "defending" for a short period of time, requiring it to enter "attacking" mode, or be injured.   

 Finite State Machines (FSM)s provide broader game-play and character engagement.  FSMs give game-play more depth of character, game-play possibilities, and longer time-in-play rates.  The more engaged a player is the more they will explore, chat, shop, play.   
9i
* AI

* Haptics


Tredmils give you movement without optical tracking sensors.  Your space is not limited, enabling broad spatial place in narrow spaces.  This inscreases safety and physical activity.   Tredmils enhance immersion.   

The subpack is a haptic vest which replicates bodily feelings one would experience in VR.   If you're playing Call of Duty and get shot your vest punches your point blank.  
subpack 
	⁃	   — — real time feedback, more immersion, 
	⁃	   — — elicits deeps emotions
	⁃	   — — stronger brand connection
	⁃	   — — experience things you could not feel in real life
	⁃	   — — raises the interest and intrigue
	⁃	        —— >   more play time more sales, increased sharing, better usability, retain a market for the product, better monetizati
	⁃	— controller feedback
	⁃	    — better relate to it.  better learn, better understand.  —   more you know, the better decisions you can make, the more you care,— passive subtle learning.   speak to them subconsciously.   gamification.   all he needs to win is pepsi (soda drinker pro)
	⁃	
	⁃	

* optical tracking 

*** What the technology is
*** How it is integrated in VR
*** Why they care (it maks them money)


	⁃	— tracks the person in the room and 
	⁃	—  more immersion.
	⁃	— less accidents, safety
	⁃	— enables spatial cognition
	⁃	— enables mixed reality
	⁃	— assists with proper movement
	⁃	— can gage your interest level 
	⁃	— computer vision integrates the surrounding area.   opens up to new methods.   
	⁃	if you are teleporting you cannot do anything that is balanced bath, and by tracking he movement
	⁃	—  
	⁃	
	⁃	 fr
	⁃	Eye-tracking
	⁃	  — gage interest
	⁃	  — match attention with intention
	⁃	  — measure awareness, interest, focus, potentially intent
	⁃	  — measure effectiveness 
	⁃	
	⁃	
	⁃	AI Engine
	⁃	
	⁃	
	⁃	give them the versatility to chose a pasificis or a more aggressive route we can gage a lot about a person, their intereste, their demographic, 
	⁃	Bio-metric feedback
	⁃	
	⁃	
	⁃	
	⁃	
	⁃	** PRODUCT:
	⁃	
* motion tracking 



*** What the technology is
*** How it is integrated in VR
*** Why they care (it maks them money)

	⁃	— capture a real persona and put them as a NPC
	⁃	— enables real human movement for a npc.  
	⁃	— make a more realistic environment , more immersive, (not someones interpretations- -  looking at something you recognitive not just a bunch of polygons
	⁃	
	⁃	Projection mapping - 
	⁃	** the inverse of virtual reality
	⁃	
	⁃	—a strong connection to physical world objects like a building.  people work in it, see it everyday , grandfather helped build it
	⁃	— it is the art canvas
	⁃	— inverse a game engine vr/ar experience as a promotion
	⁃	— interactive tool, lets people engage
	⁃	— education tool.   
	⁃	
	⁃	
	⁃	
 -  - - Token sale of Vibe hub
	⁃	
	⁃	
	⁃	
	⁃	
	⁃	
	⁃	PRODUCTS:
	⁃	
	⁃	Why would someone want an anonymous company 
	⁃	— t protect their crypto
	⁃	— avoid paying unwanted third parties
	⁃	— benefits of anonymity,  security and safety from malicious players
	⁃	
	⁃	AR Branding 
	⁃	 — points for 
	⁃	— receive information (sponsored by brand content) and it will provide you with convenience and education and —> 

* Gaming industry:

- mobile 

platform membershare and size?

Which can we push VR games to.

Profile of the gamers.

Testimony on the future of XR by gamers

use gamers gate

Videogame junkies is a big game reviewer.

List of game industry influences.

In the likes of the gaming indsutry, we are indy


- made for competition
-- team based, co-=operation, communication and planning
-- strategy
-- social
-- unchartered experiences
-- communication
-- ranking/tiers 
-- playability
  + mechanics that work (unique mechanics) 
  + differnet 
-- balance
  + 

** spin off culture of the games
*** Community

*** Fan Art

*** Lore / Theories

*** Music


** Replay value
 - the dungeons are randomly generated. 
 - different endings
 - differnet gae play
 - variety of characters
 - variety of characters 
 - 

* Spatial OS

-yarm
/Who is using it? Automaton for their upcoming game Maverick's: Proving Grounds, Abyssals being developped by some Improbable developers, MetaWorld by HelloVR, Avalon by Lil Sumn Games, Worlds Adrift by Bossa Studios, Geekzonia by Eventual and Soluis, Shattered Lives by toxicbrain, Vanishing Stars by NINPO, Seed by Klang Games, Lazarus by Spilt Milk Studios, Forsaken Legends by Holy Fire Games, Rebel Horizons by Entrada Interactive, 
-https://improbable.io/games/blog/unity-and-spatialos-and-spiders
-(I can't find it at the moment but there was one for Maverick's: Proving Grounds)
How much can it store? It should be able to store as much as you need it to
What's is it built on (how is the program built)? It's an SDK to be used in clients
Can you access it from anywhere? Cloud, should be able to acces from anywhere
What's the speed? Should be faster than if you had to runt he game on your own system
-"This means that the simulation is not limited to what a single flocking worker can do. Indeed, our local deployment used only 200 birds, but when we spawn a flock of thousands of birds in the cloud, SpatialOS automatically runs 3 instances of the flocking worker to handle the workload." <- From a description about "workers" in games made in SpatialOS, example of how "workload" is handled
What languages does it support? Unity can be used as the client on which to build the game and to simulate the physics, Unreal Engine, C++, Java, Go, C#, Objective-C, NodeJS
-"There can be thousands of players and spiders in the world, but SpatialOS sends each client updates only for the entities that the player can see, and only the components relevant to the visualisation. For example, the client gets the position and rotation of the spiders, but not their AI state, since that is used by the AI code that runs in a logic worker in the simulation layer." <- From a description of the code for the game Abyssals being made in SpatialOS
-"There are many advantages to creating workers in this way. C++ is a stable and well-integrated language. Thousands of off-the-shelf SDKs could be easily integrated, to help achieve anything from pathfinding to protein folding. Using the C++ API as a starting point, it is possible to create a reusable framework for new workers in any programming language that has a C++ API or C++ bindings." <- From a description about "workers" in games made in SpatialOS
-https://github.com/improbable-public/abyssals/tree/master/workers/unity/Assets/Gamelogic/Src
How are products exported? https://docs.improbable.io/reference/12.1/shared/deploy/deploy-cloud
What hardware is required to run it and games made on it? https://docs.improbable.io/reference/12.1/shared/get-started/requirements
Does it have an app? No mobile app, just the SDK/development platform

Relevant/Important Links:
https://improbable.io/games/blog/were-building-a-starter-vr-project-for-spatialos
https://docs.improbable.io/reference/12.1/index
https://improbable.io/games/blog/the-future-of-the-game-engine
https://improbable.io/games/blog/grpc-web-moving-past-restjson-towards-type-safe-web-apis

-Develop games in Unity or Unreal Engine with SpatialOS SDK: https://improbable.io/get-spatialos
-Web App Development

"Couple the power of SpatialOS with a dedicated team of designers and artists, and suddenly youíve got the groundwork for a massive, multi-client, production-ready online game that supports thousands of simultaneous players, in a matter of weeks."?
  
* Robotoics

* Holograms

* Projection Mapping

* Volumetrics Display





## KK research sources
- Find 10 research documents PDFs from credible sources
- save them in a single folder.
- they will be linekd to on our "resource center"
- idea starters for keywords include : Virtual currencies, virtual eonomy, vr growth, economic impact of virtual worlds, 


* Spatial OS

-yarm
/Who is using it? Automaton for their upcoming game Maverick's: Proving Grounds, Abyssals being developped by some Improbable developers, MetaWorld by HelloVR, Avalon by Lil Sumn Games, Worlds Adrift by Bossa Studios, Geekzonia by Eventual and Soluis, Shattered Lives by toxicbrain, Vanishing Stars by NINPO, Seed by Klang Games, Lazarus by Spilt Milk Studios, Forsaken Legends by Holy Fire Games, Rebel Horizons by Entrada Interactive, 
-https://improbable.io/games/blog/unity-and-spatialos-and-spiders
-(I can't find it at the moment but there was one for Maverick's: Proving Grounds)
How much can it store? It should be able to store as much as you need it to
What's is it built on (how is the program built)? It's an SDK to be used in clients
Can you access it from anywhere? Cloud, should be able to acces from anywhere
What's the speed? Should be faster than if you had to runt he game on your own system
-"This means that the simulation is not limited to what a single flocking worker can do. Indeed, our local deployment used only 200 birds, but when we spawn a flock of thousands of birds in the cloud, SpatialOS automatically runs 3 instances of the flocking worker to handle the workload." <- From a description about "workers" in games made in SpatialOS, example of how "workload" is handled
What languages does it support? Unity can be used as the client on which to build the game and to simulate the physics, Unreal Engine, C++, Java, Go, C#, Objective-C, NodeJS
-"There can be thousands of players and spiders in the world, but SpatialOS sends each client updates only for the entities that the player can see, and only the components relevant to the visualisation. For example, the client gets the position and rotation of the spiders, but not their AI state, since that is used by the AI code that runs in a logic worker in the simulation layer." <- From a description of the code for the game Abyssals being made in SpatialOS
-"There are many advantages to creating workers in this way. C++ is a stable and well-integrated language. Thousands of off-the-shelf SDKs could be easily integrated, to help achieve anything from pathfinding to protein folding. Using the C++ API as a starting point, it is possible to create a reusable framework for new workers in any programming language that has a C++ API or C++ bindings." <- From a description about "workers" in games made in SpatialOS
-https://github.com/improbable-public/abyssals/tree/master/workers/unity/Assets/Gamelogic/Src
How are products exported? https://docs.improbable.io/reference/12.1/shared/deploy/deploy-cloud
What hardware is required to run it and games made on it? https://docs.improbable.io/reference/12.1/shared/get-started/requirements
Does it have an app? No mobile app, just the SDK/development platform

Relevant/Important Links:
https://improbable.io/games/blog/were-building-a-starter-vr-project-for-spatialos
https://docs.improbable.io/reference/12.1/index
https://improbable.io/games/blog/the-future-of-the-game-engine
https://improbable.io/games/blog/grpc-web-moving-past-restjson-towards-type-safe-web-apis

-Develop games in Unity or Unreal Engine with SpatialOS SDK: https://improbable.io/get-spatialos
-Web App Development

"Couple the power of SpatialOS with a dedicated team of designers and artists, and suddenly youíve got the groundwork for a massive, multi-client, production-ready online game that supports thousands of simultaneous players, in a matter of weeks."?
  
* Robotoics
* Holograms
* Projection Mapping
* Physics Engine
* 
