* Abstract:  
Virtual Reality addresses two of the greatest challenges in automotive sales. Through holiday sales, updated  features, and new off-roading capabilities, we’ve watched for years as the automotive industry has worked to attract buyers to the showroom. While there will never be a replacement for getting a qualified buyer’s hands on the wheel and feet on the pedals, Virtual Reality brings a three dimensional automotive experience to the buyer’s home. 

* Features: 
First we capture dozens of photos from various angles of both the interior and exterior of the car. Then, by splicing these images together through an image-creation technology known as photogrammetry and installing them into Unity (the VR game engine), we enable the user to put on the VR headset and look at the vehicle as though it were parked right there in their living room. The user can walk around the car, seeing the front, back open the trunk, and lift the hood to examine the engine in Virtual Reality. Once they’ve understood the experior of the vehicle, they’ll be able to open the driver-side door and sit behind the wheel, adjust the seat, and turn around and peer through the back windshield. Once they turn the key to start the engine, they’ll cap off this real-life simulation by going for a test ride through the streets of any city or town they chose. 

** Benefits: 
Display the vehicle to the buyer without asking them to leave their home. 
Allow the user to adjust the color, model, or make of the car on demand.
Initiate an enhanced emotional connection between the buyer and the vehicle before they even arrive to the showroom
Help them understand which vehicle they’re most interested in, saving time and building decisiveness before they arrive on the day of purchase.  

* Features 
There is only so much room on the showroom floor, and often a buyer is interested in a vehicle that the dealership does not have in stock. A lot of sales are lost within this restriction. Think about how often a potential buyer walks out the door because the color, make, or model they had in mind wasn’t available on the day of their visit. VR reduces this threat by offering an on-site solution in which the buyer is able to put on the headset and view and test drive any vehicle they wish, regardless of whether it’s in stock. 

** Benefits: 
Adjust the color, make, or model of the vehicle with the click of a button. 
Allow the buyer to test-drive a similar vehicle as the one they wish to purchase and show them the photogrammetric details of the exact version they like most. 
