* World PEace

Virtual Reality will democratize experience as the internet democratized information. The leap we've made in tele-presence technologies with "VR" is emptions and viscerally connecting people.  As this technologey improves and simulations become further indistinguishable to the subconcios [ressearch that supports simulations indistinguishable from non] peoples will sincerely understand what it is to walk in another human's shoes.   

We are not yet able to provide an experience of real authenticity, but we are getting closer.   Major breakthroughs every month 

: connect to twitter # 

As modern 360 (spherical) camera displays develop spatial and networked abilities, game engines provide more robost visialand tooling, we will create life-like simulated learning expereinces. 

The internet globalized us. Today, we feel stronger connections to people we have never met before despite them being from very different lands, cultures and beliefs than our own. We relate to them better. We are realizing we have more in common than different. Only now do we see traditional media and power structures too often promoted our differences and portray the "others" as competition or enemies.

This story they tell us isn't exactly true, and we know because of the democraization of information.  

Expereince is next to be democratized.  We will all have the freedom to create any experience as we do today a webpage.   

What used to require you travelling the world you will learn form your living room (to some extent, anyways.  Nothing replaces the real thing.)  

No matter the propaganda people will chose what they've learned first hand.   How could you support a war on Palestine after you've walked the streets of Ramallah and broke break with local Palestinians?   Wars will lose support and death-profiteers will be out of business.   

Something like /Do unto others/ or /Do what thou wilt shall be the whole of the Law.  Love is the law, love under will./

If experience is fully democratize we can realistically co-exist with everyone around the world, not only the people we are physically near. With the help of virtually real experiences, we can bring world peace.
