* Objective: 
make an MVP mindfulness VR app that provides therapeutic wellness for a hospital to gather data and testimonials

* Strategy:
- Create XR mindfulness VR MVP in which the user is immersed in greenery and natural environments
- distribute on-site and in app store
- read biometric feedback
- produce 2d testimonials
- recommend evolution of MVP

* Tech Architecture
- Jacques' design uploaded to "jaqgraphichannel" on slack at 9:27 AM on Jan 21 (Unity Diagram)

* Market Research 

According to the "Scientific American" Journal, Just three to five minutes spent looking at views dominated by trees, flowers or water can begin to reduce anger, anxiety and pain and to induce relaxation. Throughout human history, trees and water have signaled an oasis, and flowering plants have been a sign of possible food. Open views deter surprises by predators, and shaded alcoves offer a safe retreat. In 1995 Cooper Marcus and landscape architect Marni Barnes received a grant from the nonprofit Center for Health Design to analyze the physical layout and daily use of several hospital gardens in northern California. In 32 hours of observations, which included taking detailed notes and interviewing users (who collectively made 2,140 visits), the researchers noticed several patterns that have been borne out in subsequent studies of other sites. According to Marcus, the more greenery versus hard surfaces, the better. He said, “We found that a ratio of at least 7:3 seems to work best."

...

Reading Notes below:

Wellness VR experience

Includes:

 hospital garden: paths, sun-dappled lawn and gnarled roots of a branching shade tree
He loves to be out in the garden feeding the birds and squirrels. Hortacultural therapy

In a recent survey of 100 directors and architects of assisted-living residences, 82 percent agreed that “the design of outdoor space should be one of the most important considerations in the design.” American Society of Landscape Architects

Ulrich and his team reviewed the medical records of people recovering from gallbladder surgery at a suburban Pennsylvania hospital. All other things being equal, patients with bedside windows looking out on leafy trees healed, on average, a day faster, needed significantly less pain medication and had fewer postsurgical complications than patients who instead saw a brick wall. published in 1984 in the journal Science by environmental psychologist Roger Ulrich, now at Texas A&M University

Just  three to five minutes spent looking at views dominated by trees, flowers or water can begin to reduce anger, anxiety and pain and to induce relaxation

Throughout human history, trees and water have signaled an oasis, and flowering plants have been a sign of possible food. Open views deter surprises by predators, and shaded alcoves offer a safe retreat.

The more greenery versus hard surfaces, the better. “We found that a ratio of at least 7:3 seems to work best,” Cooper Marcus says. Less greenery signals a “plaza or shopping mall courtyard” and is not as relaxing.

mention of inspiration behind central park 

Keep it green
Lush, layered landscapes with shade trees, flowers and shrubs at various heights should take up roughly 70 percent of the space; concrete walkways and plazas about 30 percent.  

Keep it real  
Abstract sculptures do not soothe people who are sick or worried.

Keep it interesting
Mature trees that draw birds and chairs that can be moved to facilitate private conversation foster greater interaction.

Images of tree-lined streams, fields of grain flanked by stone walls, and meadows full of flowers

"Nature images ... result in less pain and lower diastolic blood pressure,"

Meanwhile, the new ER features nature scenes, such as water falls and mountains, he said.
