
** Tourism destinations
National ministries (tourism/trade divisions) are developing content that let’s us soar through
the sky like an Olympic ski jumper (Korea Tourism Office, ~$100k), hang out back stage with
Sir Paul McCartney (Visit Britain, ~$1.5mm) or swim the crystal clear Caribbean alongside sting
rays (Cayman Islands, ~$300,000). These organizations are finding immersive media engages
travelers and influences agencies more effectively than any media prior, and has more robust
analytics to prove return on investment.
«Before, travelers just had a brochure or information on the
website to inform their choices. Virtual reality allows them
to get a true sense of the hotel and the excursion the can go
on It’s been a real game changer for us all»
- Marco Ryan, Chief Digital Officer, Thomas Coo
Reading Notes below:

Wellness VR experience

Includes:

 hospital garden: paths, sun-dappled lawn and gnarled roots of a branching shade tree
He loves to be out in the garden feeding the birds and squirrels. Hortacultural therapy

In a recent survey of 100 directors and architects of assisted-living residences, 82 percent agreed that “the design of outdoor space should be one of the most important considerations in the design.” American Society of Landscape Architects

Ulrich and his team reviewed the medical records of people recovering from gallbladder surgery at a suburban Pennsylvania hospital. All other things being equal, patients with bedside windows looking out on leafy trees healed, on average, a day faster, needed significantly less pain medication and had fewer postsurgical complications than patients who instead saw a brick wall. published in 1984 in the journal Science by environmental psychologist Roger Ulrich, now at Texas A&M University

Just  three to five minutes spent looking at views dominated by trees, flowers or water can begin to reduce anger, anxiety and pain and to induce relaxation

Throughout human history, trees and water have signaled an oasis, and flowering plants have been a sign of possible food. Open views deter surprises by predators, and shaded alcoves offer a safe retreat.

The more greenery versus hard surfaces, the better. “We found that a ratio of at least 7:3 seems to work best,” Cooper Marcus says. Less greenery signals a “plaza or shopping mall courtyard” and is not as relaxing.

mention of inspiration behind central park 

Keep it green
Lush, layered landscapes with shade trees, flowers and shrubs at various heights should take up roughly 70 percent of the space; concrete walkways and plazas about 30 percent.  

Keep it real  
Abstract sculptures do not soothe people who are sick or worried.

Keep it interesting
Mature trees that draw birds and chairs that can be moved to facilitate private conversation foster greater interaction.

Images of tree-lined streams, fields of grain flanked by stone walls, and meadows full of flowers

"Nature images ... result in less pain and lower diastolic blood pressure,"

Meanwhile, the new ER features nature scenes, such as water falls and mountains, he said.
k
«…[Virtual reality] let’s our travel trade and media partners
experience our destination in a new and unique way that
has not been possible before»
- Marsha Walden, CEO, Destination British Columbia
…[Virtual reality] let’s our travel trade and media partners
experience our destination in a new and unique way that
has not been possible before»
- Marsha Walden, CEO, Destination British Columbia
