
**** XR Boiler Room
Music is often an integral part of social gatherings - whether getting together with friends at a party, going out in the city on a Saturday night, or attending a live event. XR Boiler Room offers users the opportunity to gather for similar purposes inside the new virtual world. People from any location in the physical world can enter Virtual Reality and - through 3D audio - experience any of these music-centric environments. 

**** XR Studio
In XR, recording artists, sound engineers, and DJ's have the opportunity to gather in the Virtual Space and share, mix, and blend sounds together. Regardless of experience level, XR Studio is a place for people who enjoy blending and creating sounds together to make art. 

**** XR Concerts
Fans who are passionate about particular bands may not get the opportunity to see them perform on their world tour - tickets are too expensive, shows aren’t close enough to home, or the venue is sold out. In VR the fan can virtually attend a show anywhere in the world through their VR headset. With 3D audio and access to sold-out stadiums, VR melts the barrier between home and the venue.
