
**** Interfacing with VR 

The Infinite gallery is an original VR interface through which businesses can display their content on the walls of an unlimited virtual space. Whether it be the story of your company's history or images of your company's products, we'll use this means of interaction to help you create your own linear VR experience for your customers. 

 * Welcome Inside

Once the user enters the Infinite Gallery, they'll find themselves inside a space resembling the decorative walkway of a museum. Dependent on your customized version of the Gallery, the the user will then control their own motion through the walkway (via eye or wrist movement, controller commands, or a touchpad). As they move, they'll rely on their own head and eye movement to turn and view the content displayed on the wall. Just as in the real world, the user can look up, down, side-to-side, and even dictate the pace and direction of their own movement. 

**** Display Anything

Appropriately, the amount of content that can be displayed inside the Infinite Gallery is unlimited. Whether you'd like to display 5, 500, 5,000 or more pieces of information, the user will seamlessly cycle through the infinity loop and view the content you choose to show them. 

We've found this VR interface applicable for various forms of artwork - providing value for photographers who wish to display their content three-dimensionally and even for virtual artists who create VR-ready content from scratch. 

**** Business Solutions

Some of the most accessible ways in which the Gallery is used among businesses are by displaying company products on the Virtual Walls or by decorating the space with visuals of company history. In the case of company history (or any linear story), 3D audio is a feature that greatly enhances the user experience. 

Like many of our interfaces, the future applications of the Infinite Gallery appear unlimited. As the Virtual World continues developing and expands both upon itself and within our society, the Infinite Gallery will become a natural marketplace for businesses. Much like the evolution of ecommerce on the 2D screen, customers will be able to choose (and process their payment for) the products available on the walls of the Infinite Gallery. 

Reflecting further on the evolution of commerce, F.W. Woolworth initiated a similar psychological adjustment at the beginning of the 20th century, changing the way customers interact with products in brick and mortar stores. Throughout the history of American drug stores, whether it was a can of soda or tube of toothpaste, the customer had to request the product from the clerk, who would then go and retrieve the product from the back of the store. Woolworth turned this concept inside out with his "five and dime" stores. He brought the products out from behind the counter and displayed them on shelves, so customers could touch them, hold them, and develop a heightened connection with them. Going forward - and to this day - this format is the default arrangement in retail stores around the world. 

Among many other applications, the Infinite Gallery facilitates the evolution of ecommerce in a similar way - bringing the products off the 2D screen and in to the hands of virtual customers. 
