 
*** Bloomaway

With the first step into Virtual Reality comes uncertainty, so we created Bloomaway. It's seamless virtual navigation powered by user intuition. 

**** Seamless 
Bloomaway smooths the transition into VR. By eliminating controllers, this internally developed software responds to manual action and optical focus, empowering users to dictate pace and destination. 

**** Virtual 
Dizziness in VR results from scene shifts within the user's vantage point. Bloomaway's response is to load environment transitions outside the user's sightline. See the map, touch the destination, turn 180 degrees, and you've arrived. Dreamscape across nations and overseas with touch a sight.

**** Transport 
Bloomaway reduces business travel expenses (like those associated with employee relocation), displaying properties, schools, car dealerships, city buildings, and providing general area orientation inside the virtual world. While some experiences cannot be replaced with VR, others merge with it to reduce travel requirements and maximize time efficiency. Bloomaway brings parts of the world into VR and takes you there. 
