* Partnership
** Demo
There is no substitute for experiencing virtual reality content.   If you have a key pass, enter it here to begin a demo experienc [TXT BOX]

** Past Productions: 

*** Taiwan
**** Situation: Taiwan is of the lesser known Asia destinations but has an amazing culture to share.  We needed to stand apart from the rest of Asia.  Knowing we will not brand bigger than China or Japan in the short-term, we complimented them.

**** Strategy: (1) Bring a credible message about culture, food, beauty and other features of the destination. (2) Transfer the earned trust and credibility of a known personality to highlight “Why Taiwan”. (3) Share from a first person perspective. (4) Develop PR exposure through creative engagement

**** Production:  Travel expert, Pauline Frommer, brought the travel show to Taiwan.  We created an array of content to share across multiple distribution channels.  Integrate with entertainment darlings and showcase the culture through event partnerships in Bryant Park.   

**** Results:  7% increase in US visits year over year.  Renewed production program at a 45% increase in investment.   12% over-delivery of media commercials.  10 million media impressions through “earned media”.  Evergreen content to re-purpose indefinitely. 

(upon approval, will replicate the same text content for Hard Rock and Australia.  We will have 3 examples here)
*** Australia
*** Hard Rock

** Get Involved

*** Philanthropy
*** Apprenticeships
*** Build XR


* Resources

** Publishing 

Find here primary resources from the Nova XR team, diving deep into complex topics and emerging with insights how XR can be applied to both businesses and the arts. 

** Learning
*** How
We retain information best when we are actively involved, as we learn with our entire body.   Similar to “muscle memory” XR content enables embodied cognition for people to see, hear and touch in simulated situations that better training and catalyze comprehensive understanding.   

*** What
Anything you might learn from a video, you’ll soon more quickly learn I XR.  Think about training videos, tutorials and learning modules.  Pretty bland, huh?  Well, XR will take you from behind that desk and place in you in the field to learn.  Research sites, production plants, class rooms, space shuttles, and imaginably any place that would be a helpful environment to learn in, can be replicated and programmed for customized learning.   


*** Who
As with most technologies, the military and science centers have been for decades developing these tools to better place people in simulated situations.   Now, major brands and education institutions are further bringing XR into the hands of their employees and empowering entire teams of every-day folks to learn more, faster.    May it be to practice a dangerous feat, to collaborate on research, or to familiarize new employees, XR is being adopted across the board.   For more on industry applications, please visit our solutions Page.



** News
*** Curated (twitter feed)
*** Original (blog)
*** Featured Content
Every week our teams scout the internet and the streets to find what’s changing the game.  Here, we provide to you our favorite picks, and describe why they matter.    
 


*** Industry Solutions
