


We provide access to advance technologies.  We’ll help you understand, strategize and produce XR media.  Production services include design, development and deployment.   
    
    
*** Education

***** * Situated Learning* 

Situated learning is a theory on how individuals acquire professional skills, extending research on apprenticeship into how legitimate peripheral participation leads to membership in a community of practice. Situated learning "takes as its focus the relationship between learning and the social situation in which it occurs".
The perspective can be contrasted with alternative views of learning: "Rather than defining [learning] as the acquisition of propositional knowledge, Lave and Wenger situated learning in certain forms of social co-participation. Rather than asking what kinds of cognitive processes and conceptual structures are involved, they ask what kinds of social engagements provide the proper context for learning to take place".

***** * Emboied Cognition *

The theory that many features of cognition, whether human or otherwise, are shaped by aspects of the entire body of the organism.  The features of cognition include high level mental constructs (such as concepts and categories) and performance on carious cognitive tasks (such as reasoning or judgement).   The aspects of the body include the moto system, the perceptual system, bodily interactions with the environment (situatedness) and the assumptions about the world that are built into the structure of the organism. 
 


***** Basic Training:

This is a 3-month, light-load training course with weekly lessons customized to your business and goals.  

We'll come set you up witht the basic equipment and familiarize you and your team with xr hardware that can run virtual reality and other GPU-intesive programs.   

We'll meet weekly to cordinate the project's design and educate you on news, software, middleware and netowrking as it pertains to your business.  Every project is different and there is no catch-all solution to being educated.  Your feedback, leanring style and strengths drive the lesson plans.  We commit 10-hours a week, two collaboratively to work with you one on one, and the rest to developing your ideas.  This approach keeps you available to your tradiational responsibilities, while still captaining the ship.     
   

After 12 weeks we will deliver a full development specification, including the technical architecture, produciton timeline, expenses and financial strategy.

***** Intermediate Training

/coming soon/

***** Pro Training

/coming soon/

Educating:


