
** Consultation




We provide access to advance technologies.  We’ll help you understand, strategize and produce XR media.  Production services include design, development and deployment.   





 The skills required to produce 3d virtual media (XR) are broad and deep, but we'll keep you focused.  By internalizing the basics of xr hardware and xr software you'll be familiar with why the latest technological breakthroughs, and understand why they  are indeed breakthroughs.  With this, you'll innovative ways to improve your business that the competition is not yet equiped to think up themselves.   Arm yourself with knowledge and your business excel in this new wave of media technologies 

Only you can take the time to prepare yourself and you team to understand how and why to implament techologies such as XR (virtual/augmented reality) artificial inteliigence, robotics, block-chains /et cetera/.   We'd be glad to help.  

*** Training breakdown

**** Introduction 
• Installing hardware and software
• Downloading and playing apps
• Upgrading and maintenance

**** Hardware 
• PC and video graphics cards
• Recording and capture equipment
• Headsets, controllers and sensors

**** Software 
• 2D/3D modeling programs (Photoshop, Blender)
• Game engines (Unity, Unreal, Cry)
• VR web browsers (WebGL, Chromium, Nightly)

**** Theory 
• Optics, 3D audio, ultrasonics
• UX and UI (User experience, user interface)
• Business landscape (Facebook, Samsung, HTC, Steam, Play Station, et cetera.

**** Lab 
• New skills in practice
