* Objective:  
Familiarize Assignees with new city by creating a VR experience that enables assignees to feel the vibe of Seattle
* Delivery:   
June, 2018
* Audience:
- 22-30
- College Graduate
- Relocating to Seattle from another city in the US
- Hired by Amazon
* Strategy:
- Experience an assignment first hand
- Storyboard an experience inclusive of apartments, points of interest and neighborhoods
- Capture real 3D audio of locations
- Implement voice overs
- Integrate google map images for general location visuals
- Data capture as much as possible for genuine insights on assignee feelings/interests
* User Experience 
Colin is preparing to graduate from the University of Texas in May and has already been offered a job at Amazon, working at their headquarters. As he mentally prepares for a move to Seattle, Amazon has emailed him a file of his Virtual Tour of his new home city.  He can view this experience in VR or on his desktop.  Obviously the former is far more visceral, but both are options.  
At the University's media lab, Colin uploads his file on the VR-ready computer and dons the HTC Vive head mount. After a brief introduction, Colin skips the control orientation and is suddenly standing in Seattle-Tacoma International Airport.
Amid a 3D audio experience, Colin hears a voice in his headset. It directs him from the airport outside and into a car that drives him to Capitol Hill - the neighborhood he's most excited to visit. 
The voice guides him down Broadway and into a few of the apartment buildings he's considering as a new home. He's able to view the outside of the building, walk through the lobby, up the elevator, and even see the interior of a few different units. 
After finding the apartment he likes, the audio guide shows him the way to work. Along his walk to South Lake Union he catches a glimpse of the Space Needle. Once he arrives at his new office, he's able to see and experience his new work environment. 
With a quick survey for feedback at the end, Colin takes off the headset and sees his friend Alyssa standing in front of him, matching his big grin.
"What ya doing?" she asks
"I'm totally moving to Seattle" He replies.  "And I picked out the coolest apartment, in Capitol Hill!"
* Net Investment
$120,000
* Evolution of Development
Assignee feedback will allow us to improve points of interest and map key measures for their decision.    
We recommend the second iteration is the same location with the improvements identified through analyzing feedback and live-chat with a representative to answer questions in real time.  
The next location can be built for 2/3 of the initial investment. 
Scalability will come from automating the design process, repurposing the software for different location and replacing in the field workers with XR and robotics.


