**** Consultative Intro
***** Connect:
XR allows us to connect, share and engage more viscerally than ever before.  Humans have been systematically communicating since persian curries and greek rail systems in the 6th century BC(E).   For several hundred years, there was little advncement in horse speed or volume, but upon the discovery and understanding of electricty, we had an avanlanch of advancements in communication.   

Begining with the telegram and then the telephone, we shorted commuication over long distance to an explosive extent.  What took months could be done in minutes.   As we further adapted communication tools, we improved the quality, and volume, forging industries like radio and tv to communicate on a mass sale.  these mediums we capitalized and ontent became controlled by governments and money.  

 As hardware advanced, we learned to communicate directly on private netowrks of universiies (arpanet), businesses (another example) and then linking everyone into one web with single protocal and a simple set of rules, with the world wide web, in 1990.   This gave communication a far futher reaching infrastructure for all media.   Today, we've a new form of content, as digital information has evolved from audio, to moving images, and now into replciated environments, with CXR.

***** Understand
***** Expand
***** Explore
