Exploration of Virtual Reality presents an open ocean of opportunity for businesses. But many companies still don't understand the capabilities of this tool nor how to interface with it. So we created Bloomaway.

***** Bloomaway in VR

When you first step into VR you may not know what to do or where to go. This can feel similar to the way time and space and gravity are often altered inside a dream. Bloomaway is an interface that empowers users of all experience levels to move through Virtual Reality intuitively. It only works by relying on the user's attention (where they focus their eyes), intention (what they reach out to touch with their hands), and intuition (trusting that the scenes and sounds as presented within Bloomaway are clear enough for even the most inexperienced user to understand where they are and how to arrive somewhere else).

***** Benefits:
Reduces the learning curve in VR by eliminating the need for controllers, relying instead on natural hand movement. Our design responds the first instinct most people have when entering VR, the desire to touch what they see. Bloomaway is a fluid experience.

***** Navigate Locations
Since we know where a user is looking, we also know where they're not. Again, this seemingly simple concept allows for many practical applications. Since VR seems so real, anything that abruptly appears or disappears can become overwhelming. Bloomaway solves this issue by only having new elements load or change while separate from the user's sight line. This allows Bloomaway to take a user from New York to Paris without them even knowing they moved. Like a dream, we can seamlessly link one space to another.
