* Torus Presentation


physical representation of the flow that allows you in every way to interact with 3D model, light. screen info

The shape is becoming a circle 

* Torus: - be careful not to frame it in a way that says this is the only way to interact with the VR world. 
** TB we don’t want to patent everything about the Torus. We only want to patent the three main elements of the way the information flows inside the Torus. The shape is more a sphere than a Torus 
Similar to the way you interact with the mouse of a computer or the smartphone. That is the same way you interact with the information of the Torus. It is equally as intuitive. The information flows up and down and left to right. 
We don’t patent the way you interact with the circles because you can interact with it in many ways (eyes, hands, gestures, etc.). We only patent the flow of information. 


* In the Torus, the user’s perception of the understanding of the information (colors, shapes, words, etc.) begins at the center point of the Torus (where the user’s eyes are located). From there, the user’s perception of the information exists on the strength of a 3-part continuum of circles.

* Circle surrounding the user’s feet (bottom pole): Think of this point as an outline for the parameters in which the user can walk around (so they don’t walk into a wall in the physical world). This is one of the three circles in the continuum through which information flows. 
* Circle above the user’s head (top pole): Think of this circle as the north pole at the top of a globe. This circle is the second point through which the information for the user experience flows. 
* Circle in front of the user’s eyes: Beginning from the point at which the user’s eyes experience the flow of information (center of the Torus), information flows upward at an angle determined (customized) by the size of the Torus you’re within. As that information flows upward it begins comprising the third circle of information flow within the Torus. 

* on a 45 degree angle up from the center point (your eyes) and down from a 45 degree angle from that same center point (your eyes). The information is flowing from the top pole through this same 45-degree-angle-initiated point (your eyes) into its own circular flow and eventually down into the bottom pole.

Flowr - 3 major flow

Poloidal flow - half of a circle around you. Does not circle you in a particular direction but rather its function and value is in the fact that you always understand the shape of the movement of the information you’re seeing. The shape of the flow remains as you move. 
Toroidal flow - all around you.  flow when you’re inside the tours. Circles user from left to right. There is a horizontal circle. This is a flow you’d control information within a circle around you. 
Directional and dimensional control over information. If you want to pull something closer to you or move it to the side, you can do this through the Torus flow. This is the element that makes the torus three dimensional 


We want to patent how the information moves and how the user interacts with it. Make the information go further away from you on an axis. User interacting with it between two points - starting with it’s inception and concluding with its death. 

When we go in VR we are only one point. The best way to have all the info surround you is through a circle. 

Image of man inside of circle. 

There is a circle on the floor (or the place you have to walk so you can frame the area in the physical world and so you don’t run into a wall).

Then you have a third circle (above). 

All info arrives through top or bottom circle. 

YOu can interact with the information with nearly all of your surrounding. The only limit is the information that goes through you (is impeded by your body).

* Added Torus Description 10/14
** You arrive in Vr at one point. We'll map your surrounding by a grid - defined by the polar coordinates (which is 2 angles - an angle around you and an angle vertically)
** Every point surounding you at the surface of the Tours can be defined by 2 angles: angle relative to what's around you horiz an vert
** Also is the distance between your eyes and the things you interact - depth between you and the opbejcts 
**** You target objects through this grid (two angles and you depty perception). 
** Being in the Torus likens the individual to a light (like a star in the sky)
*** The light of the star interacts in every direction and at every depth.  
*** spacial information manager sim - allowing you to organize information in space in 3 dimensions in a way that encapsulates your head (b/c central point is your eyes)
