* Header:
Automobile

* Tagline
/Auto's xr revolution/

* Abstract:  
Through various holiday sales, updated vehicle features, and new off-roading capabilities, we’ve watched for years as the automotive industry has worked to attract buyers to the showroom. While there will never be a replacement for getting a qualified buyers’ hands on the wheel and feet on the pedals, Virtual Reality brings a three-dimensional automotive experience to the buyer’s home.

* Content: 
First we capture dozens of photos from various angles of both the interior and exterior of the car. Then, by meshing these images together through an image-creation technology known as photogrammetry and installing them into Unity (the VR game engine), we enable the user to put on the VR headset and look at the vehicle as though it were parked right there in their living room. The user can sit inside the car, walk around the exterior of the vehicle, and lift the hood to examine the engine in Virtual Reality. Once they sit behind the wheel, they’ll be able to adjust the seat and mirror before turning the key and taking the car for a simulated test drive through the streets of any city or town they chose.
