* Header 

Travel and Tourism

* Abstract

National ministries (tourism/trade divisions) are developing content that lets us soar through the sky like an Olympic ski jumper (Korea Tourism Office, ~$100k), hang out backstage with Sir Paul McCartney (Visit Britain, ~$1.5mm), and swim the crystal clear Caribbean alongside stingrays (Caribbean Island, ~$300,000). These organizations are finding that immersive media engages travelers and influences agencies more effectively than any media prior and has more robust analytics to prove return on investment.

«Before, travelers just had a brochure or information on the website to inform their choices. Virtual reality allows them to get a true sense of the hotel and the excursion they can go on. It’s been a real game changer for us all.»

- Marco Ryan, Chief Digital Officer, Thomas Cook

«…[Virtual reality] let’s our travel trade and media partners experience our destination in a new and unique way that has not been possible before.»

- Marsha Walden, CEO, Destination British Columbia

Interested in a Seamless Virtual Transport solution?  Check out BLOOMAWAY.
