Market Research:

* Sources
Global Web Index (GWI), a tech company that runs an ongoing proprietary data collection initiative on the digital consumer

* How many people own VR headsets and who are they?
-In June 2017, Sony claimed to have sold 1 million units 

- The statistic shows forecast unit sales of virtual reality headsets in 
2016 by product. It was predicted that in 2016 around 3.6 million units of 
the Oculus Rift would be sold compared to an estimated 5 million units of 
the Samsung Gear VR. The virtual reality market was estimated to be worth 
some 2.5 billion U.S. dollars in 2016, and is expected to grow to 
21.5 billion by the year 2020.

- By the end of 2016, 800,000 PlayStation VR units were expected to have 
sold, according to the research firm Canalys, along with about 500,000 
HTC Vive and 400,000 Oculus Rift headsets. By comparison, Apple sold 
3.3 million iPhones during the six months they were available in 2007 
(the phone’s debut year), according to Gartner. Sales rose to 11.4 million 
in 2008.

* Future of VR
HTC Vive X VR accelerator program has a $100M investment fund to build 
such unique content and already has over sixty investments. 
There are five accelerator locations – two in China, and one each in Taipei,
 Israel, and San Francisco (SF).

* What are people looking for when they book a hotel room online?

* Number of guests yearly

* Pictures of places helps sell/rent them

* What are hardcosts of installing VR
servers 
bandwith 
hardware 
insurance

* What else could hotel use VR headsets for?  

* How many press views would this get? 

* Create photogrammetry for local sites/attractions

* Vacancy rates
