

With the advancement of in-home entertainment, it’s been a constant challenge for exhibits and museums to draw folks away from their living rooms. Unlike the television and the computer, Virtual Reality is not yet a wide-spread in-home technology. As a result, companies are finding it advantageous to develop unique content in VR and display it at their place of businesses. When positioning VR this way, location-based entertainment companies are able to market it as a commodity, marking a point of differentiation from their competition. Once the customer arrives on-site, VR then becomes a tool that affords an entirely new means of interacting with the information. 

An industry that has benefited from this type of idea development are aquariums. 

Here’s how we’ve developed the customer flow in the past: 



**** Guest Experience 

A mother of three children notices on Instagram that the local aquarium has added an on-site Virtual Reality experience. She’s been on the lookout for a weekend activity, and decides to schedule the whole family for a visit to the aquarium next Saturday. When they arrive, the first thing her kids notice are mixed reality images showing guests swimming side-by-side with sea life. Her elementary-age kids loved pretending to scuba dive over the summer, and they're bouncing around at the thought of this virtual experience. 

She knows it'll be an education in spatial awareness and biology and create an emotional connection between her children and non-human species. Putting their name on the list that says the next opening for the VR experience is at 1:30PM, she tells the kids, "Perfect, we'll leave the cafeteria at 12:30 to give ourselves plenty of time." In the afternoon, all four of them are able to enter the VR experience together and experience the exhilaration of swimming beside humpback whales.
