
The age-old challenge: how do you really know if your ad worked? Generally, you don’t. You have insights, clues, and stats but are missing a key metric: viewer-visit verification.

By analyzing Facebook user login info and profile photos, we'll create, encrypt, and database a library of photos, cross reference it against the photos taken of visitors when they arrive at customs, and produce a number that represents your ad's success rate. 

**** Production

1	Custom design location's face-matching software
2	Integrate software into current IT Infrastructure
3	Verify ad viewers who visit the location
4	Analyze data
5	Improve creative and distribution choices
6	Hold media partners accountable for delivering tourism

**** Software Production	

Phase 1, Design 	[6 weeks] 	$48,000
Technological architecture and preliminary design. You'll be able to see a non-functioning example of the software 

Phase 2, Create 	[16 weeks] 	$186,000
Develop and test

Phase 3, Refine 	 [4 weeks]	$93,000 							     	     
Quality Assurance, user test, and deploy

**** Features 

We will Implement a software that verifies ad-viewers who visit your location through face recognition technology. This metric will allow you to increase advertising by an estimated 40% effectiveness, dollar per dollar.      

**** Benefits

It's a turn-key solution that will hold media partners accountable for quantifiably increasing visits. This tool has the ability to provide a 40% ROI solely through shedding awareness on ad effectiveness. 

**** Advanced Understanding

Based on our six months of consultancy and development, we will deliver
 a ~50 pages specification defining:

-The integration with the existing system
-The integration with Facebook facial data
-The database structure 
-The application UI 
-The application documentation

**** Evolution of Development

-Year 1

Right away we can review IT infrastructure and ad buying data to begin developing your specification. We will design both the preliminary stages of the facial recognition software and the ad strategy to populate our face matching database. The bulk of the work begins in year two.
			
-Year 2

We will build your Facematch software during a 16 week development process.  This includes full specification, production, and implementation. At the end of 16 weeks we'll be prepared to launch the first iteration of the software. The program will continue improving as we continue compiling data.
				
-Year 3

Using results obtained in 2018, you'll now be able to grow your application and enlarge your Face Matching database to gather more pertinent analytics. This could include integrating biometric software across other media content, increasing user base, and, allowing you to better-target the right audience and increase heads in beds.

