Turkish Airlines 2-page

* Objectie
** Draw attention to Turkisn Airlines' brand during the super bowl
** Further creatively promote THY during the super bowl (inclusive of SM) 

* Strategy
** Create an easy-to-win AR contest.  
** Promote it during the super bowl on social media and on a leader board in times square. Tie content to Dr. Oz and five senses commercial. Incentivize with an opportunity to win $1M of bitcoins and THY flights 

** How to participate
 Create an AR experience through which Super Bowl viewers use the AR feature on their pbone to track the flight of the ball on the screen
*** Ball appears through AR as Turkish Airplane
*** User who tracks the flight of a TD pass wins plane ticket
*** Display leaderboard in Times Square, tracking users who gain the most yards through ball tracking in AR

*Emphasize association of NFL players with Turkish 


Draw attention to Turkish Airlines 

With a call-to-action at the end of Dr. Oz commercial 

Inviting people to take a photo of their party and submit it on social media

For the chance to win 1M in Bitcoins or Free THY flights
