*** Education

***** * Situated Learning* 

Situated learning is a theory on how individuals acquire professional skills, extending research on apprenticeship into how legitimate peripheral participation leads to membership in a community of practice. Situated learning "takes as its focus the relationship between learning and the social situation in which it occurs".
The perspective can be contrasted with alternative views of learning: "Rather than defining [learning] as the acquisition of propositional knowledge, Lave and Wenger situated learning in certain forms of social co-participation. Rather than asking what kinds of cognitive processes and conceptual structures are involved, they ask what kinds of social engagements provide the proper context for learning to take place".

***** * Emboied Cognition *

The theory that many features of cognition, whether human or otherwise, are shaped by aspects of the entire body of the organism.  The features of cognition include high level mental constructs (such as concepts and categories) and performance on carious cognitive tasks (such as reasoning or judgement).   The aspects of the body include the moto system, the perceptual system, bodily interactions with the environment (situatedness) and the assumptions about the world that are built into the structure of the organism. 
 
