* World PEace

Virtual Reality will democratize experience as the internet democratized information. The leap we've made in tele-presence technologies with "VR" is eliciting sympathy better than any communication method prior. We are not yet able to provide an experience of real authenticity, but we are getting closer, and the major breakthroughs have already been made. The rest will unfold over the next few years as we advance from modern 360 (spherical) camera displays and the currently labor-intensive Game Engine builds to a more user friendly and always-ready model for sharing experience. We will continue to improve capturing emotions, remote rendering, mo cap and other areas that will increase the sincerity of a broadcasted VR experience. These advancements are to kick down the doors for a new era of human understanding.

The internet globalized us. Today, we feel stronger connections to people we have never met before despite them being from very different lands, cultures and beliefs than our own. We relate to them better. We are realizing we have more in common than different. Only now do we see traditional media and power structures too often promoted our differences and portray the "others" as competition or enemies.

How could we have known better without exhausting effort to travel the world? (which, I recommend, anyways) Today we work on projects together, share ideas and follow each others' day-today-day life, directly and without third parties filtering the content or the biases of a third party's agenda.

The connectivity of the internet democratized information. That was a major step. VR will democratize experience and allow us to understand each other better. It will be very difficult to support bombing a place in which you have friends, or have visited. No matter how much propaganda suggests exploding people is justified, wars will lose the support of the people because now those places have deeper meaning to us, personally.
If experience is fully democratize we can realistically co-exist with everyone around the world, not only the people we are physically near. With the help of virtually real experiences, we can bring world peace.
