
**** NYE
***** Description
In stereoscopic 3D virtual reality we will bring you to 10 iconic cities around the world. All you need is the internet.

Imagine teleporting from one city to another at a glance!

This New Year’s Eve you can travel the world without leaving your living room.

The streams will be centralized into a computer graphic game engine where you can access all 36 consecutive hours of New Year’s Eve festivities.

***** Production
****** Distribution
The WebVR: The future is clear, VR will be accessed through our web browsers. Anyone with YouTube or Facebook can access our New Year’s Eve content, but those with high fidelity headsets and WebVR will navigate the world as the truest pioneers.

All those who access WebVR and visit all 10 cities, will be entered to win a trip to the city of their choice (+1).

****** locations
We decided on these 10 locations based on our advanced and data-driven scouting report. The content will live live across twelve time zones.

If we had to bring the production to market tomorrow, the destinations would be: Bikini Taipei, Dubai, Istanbul, Kiev, Paris, New York, Buenos Aires, San Francisco and Juno.
***** Technology 
***** Monetization
***** Features 
***** Benefits
***** Evolution of Development
