* Header

Consultation

* Second

AR Beverage Solution

* Abstract


With AR, AI and IOT.  (Augmented Reality, Artificial Intelligence, Internet of Things), we are naturally and effortlessly interacting with a "smart world".

I look across the table at my bottle of beer. How cold is that beer? It's awfully close to the fire.  The temperature lists above. I can also see how many ounces are in the bottle and a link to the brewery's website. Visible, too, is a mini icon to rate the beer or even tweet about it.   

In the coming years you’ll be able to recreate this scene in the physical world. 

It's natural to think that there are no electronic components in your bottle of beer, no nodes, no copper, no semiconductors or metalloids of any type. But once your beer has computational abilities and an IP address, your insights may change.   

Augmented Reality is the hackaround. It represents computer vision that senses UltraSound, LiDAR (Light Detection and Ranging), and cameras for processing surrounding information and returning info from the other end of its protocol. 

Soon, via social media, we will know which of our friends are also drinking this beer in this same moment. We’ll send them a virtual “cheers” with the raise of a glass in front of our eyewear, and a nod. “Cheers! Phil!”  

The message will appear as a notification and the latest social media platform will say "Joe and Phil are enjoying a Six Point Brew together from Six Point brewery in Brooklyn. 

This is made possible with inside-out tracking, deployed in 2018 by three major hardware manufacturers: Sony, HTC, and Oculus. 
