* Kyle Uploading Text and Pictos to Admin
** 12:30 AM March 12

** Solutions 

*** Industry
uploaded all 13: header, text, picto 

*** Cross Industry 
Uploaded all 5: header, text, picto 

*** Learning Lab 
- Pictos not visible in Dropbox location (folder empty)
- Uploaded random pictos as placeholder and uploaded header, text

**** Resource Center 
Needs links to bulleted text to bring user to resources outside our site. (KK to do)

*** Publication 
- The titles of the visuals in Dropbox do not match the titles of the web arch ((1) Market Research, (2) Financial Stratetgies)
- Inside the Publication Admin were 7 folders. The Github folder tree was only contained 2 .orgs (Market Research and Fin Strat). 
- Action: uploaded the 2 .orgs + Relocation Fin Strat PDF (downloaded from Githu). 
- We have content for NYE Fin Strat but it's in .org form on Dropbox. Did not upload it to Admin page. 

** Services 

*** Design 
- Uploaded header, text, and picto for all 4 sections. 
- Text does not appear on website. 

*** Develop 
- Need this folder added to admin 

*** Deploy 
- All pictos uploaded
- Text for each of these needs improvement (JM To Do)
- "Advertising" does not have text 

** Nova XR 

*** About us
- text is not client facing 

*** Community 
- Uploaded header, text, picto for philosophy, philanthropy, rent space, photoshoot
- No image in "community" dropbox folder titled "shout out" (uploaded header and text)

*** Lab Live 
- No image for "Olympics in VR" but pulled from Art Director 
- 7 Lab Live pages uploaded 

*** Productions

- Australia: uploaded 
- Caymen: No text (JM To Do)
- Peru: No text (JM To Do) 
- Kelly: Uploaded
- Live Nation: No text (JM To Do)
- Hawaii: uploaded 
- Hard Rock: Uploadd 
- Potential Synergy: No Text (JM to weigh in...is this a summary of our logo redisgn for them?)

*** Partners 

- Investor: Uploaded
- Studios: Uploaded 
- Producer: Uploaded

*** Careers 
- All 5 added with text and picto

Need a "Find Us" on admin

*** 2 Bugs to report: 

1. Text not appearing under "community"

2. After clicking on rectangles in "Design" body of text does not appear

Nice work, guys. Plenty more to come 

