** Step 1
Familiarize with technology and pre-produce Unilever’s Pilot content. Once BGRS is fully
trained and understands the technologies, we will design the look, feel and general sensations
of our planned expereince. With an agreed upon vision, a script will be written and scenes will
be sketched. We will then introduce technologies and and develop a production schedule.

** Step 2
Produce and launch our Pre-Move Orientation Pilot. Assignees will journey on an
exceptionally high-quality simulation of the host city. They will shop the downtown, design
home interiors and visit schools to learn first hand what life will be like in Rotterdam. After
verifying a successful pilot by measuring the satisfaction of users, we will expand development
to additional select cities.

** 2019
Scale the pilot program to be multi-city, building on the measures of assignee satisfaction.
Further, we will implement a virtual AI guide to auto assist assignees as they explore. These
guides will be able to accurately respond
k
