
* XR Consultnacy 

/We simplify complex technologies/ 

** Executive Summary: 

Learn to access, apply and deploy XR media technologies. 

Extended reality (XR) is a term referring to all real-and-virtual combined environments and human-machine interactions generated by computer technology and wearables. It includes representative forms such as augmented reality (AR), augmented virtuality (AV) and virtual reality (VR),[1] and the areas interpolated among them. The levels of virtuality range from partially sensory inputs to immersive virtuality, also called VR.

** Services

We are dedicated to keeping you ahead of the curve and competitive.  We are on call 24 hours a day to provide you with solutions, insights and direction.  

- Customized educational content
- Installations
- In-person and in-VR training
- Design 
- Production
- Development
- Testing
- Publishing

$120 per hour

*** Billable hours include:

- Research and reports
- Correspondents
- development and testing   

Tech enthusiasts around the world, with disposable time/income, will engage your world.      Create, share, sell, whatever, however, in VR.  Begin by completing: Creative Specs.

** Agreement:


	This Agreement is made this ______ day of ____________________, 2017, by and between _______________ (the “Company”), ___________________________________, and Nova Media LLC (the “Consultant”) of 461 Mountain Avenue, North Caldwell, New Jersey.

WHEREAS, the Consultant is to perform consulting services, strategic planning, production education, and hardware training.

WHEREAS, the Company desires that the Consultant provide advice and assistance to the Company in his or her area of expertise; and

WHEREAS, the Consultant desires to provide such advice and assistance to the Company under the terms and conditions of this Agreement;

NOW, THEREFORE, the Company and the Consultant hereby agree as follows:

*** 1. Consulting Services


(a) Subject to the terms and conditions of this Agreement, the Company hereby retains Consultant as a consultant and technical advisor to perform the consulting services specifically set out in Consultancy attached to this Agreement and made a part hereof (hereafter referred to as the “Services”), as said Consultancy Agreement may be amended in writing from time to time, and Consultant agrees, subject to the terms and conditions of this Agreement, render such Services during the term of this Agreement.  Such services shall be limited to the area of expertise described in Consultancy Agreement, as amended in writing from time to time.  Consultant shall render services hereunder at such times and places as shall be mutually agreed by Company and Consultant.  Consultant’s commitment hereunder shall exceed expectations. 

(b) It is understood that the purpose of the Consulting is to provide a strategy to create and deploy XR per Services, which will improve BGRS’s services, and that neither Consultant nor Company will benefit if Consultant provides inaccurate advice or commentary based on insufficient information.  To that end, Company shall provide Consultant, in advance of meetings, with accurate, unbiased and sufficient information for him to review the subject matter thereof, and shall promptly provide further information that Consultant reasonably deems relevant to forming any pertinent conclusions relevant to the matter for discussion.  It is expressly understood that Consultant has no fiduciary obligation to Company, but instead a contractual one described by the terms of this Agreement; that Consultant’s role is to provide independent advice uninfluenced by commercial concerns; and that service as a Consultant does not require him to be an advocate for Company or its products in any forum, public or private.  Company expressly agrees that under no circumstances will this role be compromised or inaccurately represented.

. 		.

(c)   Consultant shall, at Consultant’s expense, provide Company employees with the initial training an support services necessary and desirable to operate the Hardware and Software, as further described in the Consultancy Agreement sent with this agreement at times and locations parties agree to in writing.
(d) The Consultant to dedicate a minimum of 400 hours per month per Services for a minimum of three consecutive months, totally 1,200 hours over ninety days. 
(e) Unused hours will roll over as credits to the following month.  After six months the rolled-over hours depreciate to one half of their original value.  After twelve months of roll-over, the hours shall expire.   
(f) The Consultant to provide a weekly detailed report of billing hours to the client in PDF form over email and with the availability to discuss by tele-conference.  
(g)  Offer of Services to expire ____________________________.  Consultant reserves the right to terminate offer prior to _____________________ with out without cause.

*** 2. Compensation and Reimbursement

In consideration of three months and 1,200 hours of services the by the Consultant, Company hereunder shall pay to Consultant $60,000.    Services will begin upon receiving $40,000 to begin work, by executing on services outlined in Services.    The company to pay Consultant an additional $20,000 after 60 days from the initial payment to fulfill this agreement.

In addition, the Company shall reimburse Consultant for reasonable travel and other expenses Consultant incurs in connection with performing the Services. To obtain reimbursement, Consultant shall submit to BGRS’s designated contact or designee, an invoice describing services rendered and expenses incurred under this Agreement.  

Company shall provide any documentation requirements and any travel policy restrictions to consultant in writing in advance, or be foreclosed from relying on such requirements and restrictions to deny reimbursement.  

The Company shall pay to Consultant invoiced amounts within thirty (30) days after the date of invoice.  Company will accommodate Consultant’s request to arrange, at Company’s expense, for all of Consultant’s travel and accommodations in connection with such meetings if they occur outside the New York metropolitan area.

At the Consultant’s expense, Services include initial set up of hardware and software at location of Company’s choice.  Details outlined further in Services. 

Any hours spent by consultant over and above the contracted monthly number of hours shall be payable by company to consultant at a 20% discount.
Payment amounts under this agreement shall not include applicable taxes and other charges customarily due and payable by the Company. Same will be billed out dollar for dollar by Consultant and payment by Company shall be included and paid at the time of billing pursuant to the applicable terms and conditions of this Agreement.
Initial payment is due within thirty (30) days of this agreement, at which time consultancy will commence per Services.   

*** 3. Independent Contractor Status

The parties agree that this Agreement creates an independent contractor relationship, not an employment relationship as defined by State and Federal Statutes.  The Consultant acknowledges and agrees that the Company shall not provide the Consultant with any employee benefits, including without limitation any employee stock purchase plan, social security contributions, unemployment contributions, medical, or pension payments, and that income tax withholding shall be solely the responsibility of the Consultant.  In addition, the parties acknowledge and agree that neither party has, or shall be deemed to have, the authority to bind the other party to any agreement, responsibility, obligation not defined and provided for herein.

*** 4. Indemnification

Notwithstanding any other term of this Agreement, Company shall indemnify, defend and hold harmless Consultant, and Nova Media, its affiliates, current or future executives, trustees, officers, employees, partners, event guests, students, interns, apprentices, families, and agents and other independent contractors, and their respective successors, heirs and assigns (the “Indemnitees”), against any claim, liability, cost, damage, deficiency, loss, expense or obligation of any kind or nature (including without limitation reasonable attorneys’ fees and other costs and expenses of litigation) incurred by or imposed upon the Indemnitees or any one of them in connection with any claims,  suits, actions, demands or judgments arising out of this Agreement (including, but not limited to, actions in the form of tort, warranty, or strict liability).


*** 5. Intellectual Property

(a) This agreement assigns all inventions and intellectual property arising from Services or related academic research and development, to Consultant, in their entirety, indefinitely and exclusively.  

(b)  Consultant understands and acknowledges that Company will be providing access to proprietary and valuable information that Consultant might otherwise not receive.  In addition, those parties also understand that should Consultant, in the course of providing Services, invent or participate in inventing modifications or improvements to Company technology, Company reasonably seeks to secure such improvements for its own use and practice.  At the same time, Company understands and acknowledges that Consultant has pre-existing and on-going obligations to other companies, brands, individuals, government organizations, non-governmental organizations, and others whom engage Consultant. Company understands and acknowledges this without dispute or concern. 

(d) Ownership of any Inventions, and any patent rights related thereto, shall reside with Consultant. 

e) Consultant acknowledges that Company does not desire to acquire any trade secrets, know-how, confidential information, or other intellectual property that the Consultant may have acquired from or developed for any third party, including the Institution (“Third-Party IP”). Company agrees that in the course of providing the Services, the Consultant shall not be required to use or disclose any Third-Party IP, including without limitation any intellectual property of (i) any former or current employer, (ii) any person for whom the Consultant has performed or currently performs consulting services, or (iii) any other person to whom the Consultant has a legal obligation regarding the use or disclosure of such intellectual property.

*** 6.  Confidential Information 


(a)  The parties acknowledge that in connection with Consultant’s Services, the Company may disclose to Consultant confidential and proprietary information and trade secrets of the Company, and that Consultant may also create such information within the scope and in the course of performing the Services (hereinafter, subject to the exceptions below, “Company Confidential Information”).  Such information may that directly of Company or Company clients, associates, partners, executives, staff, employees, or other third parties, concerning discoveries, financial records and or predictions and forecasts, know-how; IT strategies and processes; relocation services, personal data of individuals, logistics models, business plans, marketing plans; or other data.    Notwithstanding the above, the Company acknowledges and agrees that none of the information described in this Paragraph 6 (except Confidential Information created by Consultant) will be considered Company Confidential Information for purposes of this Agreement, unless the information is disclosed to Consultant by the Company in writing and is clearly marked as confidential, or, where verbally disclosed to Consultant by the Company, is followed within fifteen (15) days of such verbal disclosure by a writing from the Company confirming such disclosure and indicating that such disclosure is confidential.  

(b)  Subject to the terms and conditions of this Agreement, Consultant hereby agrees that during the term of this Agreement and for a period of three (3) years thereafter: (i) Consultant shall not publicly divulge, disseminate, publish or otherwise disclose any Company Confidential Information without the Company’s prior written consent, which consent shall not be unreasonably withheld; and (ii) Consultant shall not use any such Company Confidential Information for any purposes other than consultation with the Company, except that Consultant’s use of such information for purely internal research or development, without disclosure outside The Consultant, shall not be a breach of this Agreement.  Notwithstanding the above, the Company and Consultant acknowledge and agree that the obligations set out in this Paragraph 6 shall not apply to any portion of Company Confidential Information which:   

(i)  was at the time of disclosure to Consultant part of the public domain by publication or otherwise; or

(ii)  became part of the public domain after disclosure to Consultant by publication or otherwise, except by breach of this Agreement; or 

(iii)  was already properly and lawfully in Consultant’s possession at the time it was received from the Company; or

(iv)  was or is lawfully received by Consultant from a third party who was under no obligation of confidentiality with respect thereto; or

(v)  was or is independently developed by Consultant without reference to Company Confidential Information; 

(vi)  is required to be disclosed by law, regulation or judicial or administrative process; or

(vii)  in the case of information prepared by Consultant, is encompassed within and derived from Consultant’s academic and professional commitments to The Consultant , and/or any other consulting or research engagement, provided that Confidential Information described in this clause (vii) which constitutes Inventions shall be subject to the intellectual property provisions of Section 5 of this Agreement

(viii) morally, as judged by Consultant, necessary to be disclosed for the good of society at large  

(c)  Notwithstanding any other term of this Agreement, the Company agrees that it shall not disclose to Consultant any information which is Company Confidential Information: (i) except to the extent necessary for Consultant to fulfill Consultant’s obligations to the Company under this Agreement; or (ii) unless Consultant has agreed in writing to accept such disclosure.  All other information and communications between the Company and Consultant shall be deemed to be provided to Consultant by the Company on a non-confidential basis.  The Company also agrees that Consultant may share the terms of this agreement on a confidential basis with its employers, legal and financial advisors, insurers and other third parties who have a legitimate need to know about them, and that Consultant may disclose the existence and general nature of his consulting arrangement with the Company with the University, his colleagues and co-workers, and his collaborators, as well as publishers and audience members at industry conferences and forums at which Consultant is speaking or presenting, whenever such disclosures are legally or ethically required or appropriate. The Company further agrees that Consultant shall not be liable to the Company or to any third party claiming by or through the Company for any unauthorized disclosure or use of Company Confidential Information which occurs despite Consultant’s compliance with Consultant’s obligations under this Agreement.

(d)  Upon termination of the Agreement, or any other termination of Consultant’s services for the Company, all records, drawings, notebooks and other documents pertaining to any Confidential Information of the Company, whether prepared by Consultant or others, and any material, specimens, equipment, tools or other devices owned by the Company then in Consultant’s possession, and all copies of any documents, shall be returned to the Company, except Consultant may keep one copy of all documents for his or her files (which copy shall be subject to the confidentiality and non-use requirements set out in this Agreement).

*** 7. Publication

Company agrees that Consultant shall be free to publish within the scope of its professional and academic duties with respect to Consultant’s participation as a Consultant, provided that Consultant does not reveal Confidential Information of Company.  Company therefore agrees that in the course business, Consultant may discuss such participation at conferences, with colleagues, and with students, residents and fellows as Consultant deems appropriate, without revealing such Confidential Information.  In either context, as well as in the scope of its duties under this Agreement, Consultant shall be free to conduct her- or himself without restraint or improper influence, in accordance with Nova Media and Institutional academic, ethical and publication standards.  Solely in order to permit Company an opportunity to determine if Confidential Information or Inventions are therein improperly disclosed, Consultant agrees to use reasonable efforts to (i) provide to Company at least thirty days in advance of submission to a journal any substantially complete manuscript that includes such Confidential Information; (ii) provide notice to Company no later than five working days before submission for publication or to a conference of any substantially final abstract referring to such Confidential Information; and (iii) notify Company thirty days in advance of any conference at which such Confidential Information can foreseeably be revealed.  If within that thirty-day period Company requests a delay in publication so that a patent may be filed on Inventions disclosed in the manuscript, Consultant will delay publication for up to an additional sixty days (not to exceed a total of ninety days from the initial submission of a manuscript to Company).  Company agrees to hold all such submissions and information in confidence pending publication.  Company agrees to notify Consultant promptly if any action is necessary to delete Confidential Information. Company has no other right to request alteration or deletion of any portion of the manuscript or abstract.

*** 8. Term

Per this agreement, Company is hiring Consultant per terms of Service for a minimum of ninety days at a rate of 400 hours per 4.3 weeks.   The agreement is to begin upon receiving first payment of $40,000 US dollars.



(a)  This Agreement shall remain in effect for a term of one calendar quarter commencing on the day initial payment of $40,000 is received, unless sooner terminated as hereinafter provided, or unless extended by agreement of the parties and the assent of The Consultant.  

(b)  Company may cancel the agreement anytime.  Company shall not receive any reimbursement, should Company cancel services.

(c) Company shall receive reimbursement for any Services unrendered proportionately one hour to $50, should Consultant cancel this agreement.  

(b)  This Agreement may be terminated by either party, with or without cause, upon thirty (30) days prior written notice to the other; provided that if Consultant terminates this Agreement, Consultant shall, in accordance with the terms and conditions hereof, nevertheless wind up in an orderly fashion assignments for the Company which Consultant began prior to the date of notice of termination hereunder.  

(c)  Upon termination of this Agreement for any reason, Consultant shall be entitled to receive such compensation and reimbursement, if any, accrued under the terms of this Agreement, but unpaid, as of the date Consultant ceases work under this Agreement.  In addition, Consultant shall be reimbursed for any noncancellable obligations, any cancellation penalties, and, unless Consultant terminates the agreement without cause, any expenditures reasonably made in order to perform the Services that were to occur had cancellation not occurred.

*** 9. Delivery

All deliverables are to be documented on or before the day due, as agreed upon per Services.   All deliverables are expected to have up to10-days delay without penalty, if due to unforeseen circumstances or a change in strategy as documented by Consultant or Company, for all deadlines. 

*** 10. Other Agreements

(a)  The Consultant shall use reasonable efforts not to use any facilities, funds, or equipment owned or administered by The Consultant in the performance of the Services, except with the prior written consent of the Company and in accordance with all applicable policies of the Institution.

(b)  Company shall not use Consultant’s name or depiction, or the name, logos, trademarks, or depictions of The Consultant, or any officer, director, employee, appointee, member of employee of either, or any adaptation thereof, in any promotional, advertising or marketing literature, or in any other way without the prior written consent of The Consultant, the individual, or The Consultant, as appropriate, provided however that in neutral circumstances that do not imply endorsement or advocacy, or otherwise misrepresent the terms of this Agreement or Consultant’s role, Company may accurately state that Consultant is a consultant to Company, and list his or her professional degrees, titles and, or, accomplishments

(c)  No alteration or modification of this Agreement, including Consultancy Agreement hereto, shall be valid unless made in writing and executed by Consultant and the Company.

(d)  The Consultant and Company mutually represent that to the best of their knowledge neither currently has any agreement with, or any other obligation to, any third party that conflicts with the terms of this Agreement.  The parties agree that they shall not intentionally and knowingly enter into any such agreement.

(e)  The laws of the United States Federal government shall govern this Agreement.

(f)  Any notice or other communication by one party to the other hereunder shall be in writing and signed; digitally via email, and, or other web, and, or software service in which are associated to the Company and, or, the Consultant, including but not limited to email, text message, or other messaging platforms, and, or, communication platforms of which are generally accepted and used by businesses and, or, individuals of modern society; by certified mail; and, or in person.


