* Infinite Gallery

***** Description
***** Production
***** Technology 
***** Monetization
***** Features 
***** Benefits
***** Evolution of Development

Showcase in the Infinite Gallery!

The Infinite Gallery is an original VR interface. As we usher in the Virtual age, we're creating innovative ways to interact with the virtual world - affording even the most inexperienced users agility inside VR.

The Infinite gallery is an interface through which businesses can display their content on the walls of an infinite virtual space. Whether it be the story of your company's history or images of your company's products, we'll use this interface to help you create your own linear VR experience for your customers. 

 Much like in the late 90's and early 2000's when Paypal and other online currency exchange programs created a means through which the user could buy products right from home, your guests will now be able to purchase your products from directly inside the Infinite Gallery.  

 At the beginning of the 20th century, F.W. Woolworth adjusted the way customers interacted with products in brick and mortar stores. Throughout the history of American drug stores, whether it was a can of soda or container of toothpaste, the customer had to request the product from the clerk. The clerk would then go and retrieve the product from the back of the store. Then, Woolworth turned this concept inside out with his "five and dime" stores. He brought the products out from behind the counter and displayed them on shelves, so customers could touch them, hold them, and develop a heightened connection with them. This little idea changed retail forever. Going forward - and to this day - this format is the default arrangement in retail stores around the world. 

In this sense, Virtual Reality is introducing to the internet the same principle that was adopted by the retail industry 100 years ago, taking all the products from behind the screen and putting them into our hands.
