* Learning

***** How
Actively participating in an experience increases learning retention.  We learn with our entire body. All the sights, sounds, sensations /together/ stregnthen our retention.  Imagine traffic on the street, sun in the sky, wind in your face.  Music, food, the people you break bread with.  We learn from it all.   

***** What
 Anything learned by from a video, you’ll soon learn in XR. Training videos, tutorials and learning modules is 40% more effective.  If you increased your staff's productivity.

 be far more effective. Pretty bland, huh? Well, XR will take you from behind that desk and place in you in the field to learn. Research sites, production plants, class rooms, space shuttles, and imaginably any place that would be a helpful environment to learn in, can be replicated and programmed for customized learning.

***** Who
As with most technologies, the military and science centers have been for decades developing these tools to better place people in simulated situations. Now, major brands and education institutions are further bringing XR into the hands of their employees and empowering entire teams of every-day folks to learn more, faster. May it be to practice a dangerous feat, to collaborate on research, or to familiarize new employees, XR is being adopted across the board. For more on industry applications, please visit our solutions Page.
