Pandora will be the first to usher in a truly high quality music listening experience in Virtual Reality. In the same way Pandora was the leader in radio-style listening online at the beginning of the century, technology has now taken the next step and brought it's users inside the digital world. Still in its nascent days, though, there are some crucial elements of the VR user experience that haven't yet been fully integrated into the technology - sound is foremost among them.  

Music is not only something we experience but it's also a place we go. Listening to our favorite classic rock band brings us into the car and back to that roadtrip right after college. The classics give us a peak into a previous time that we'll never be able to fully comprehend. Hip hop brings us to a place of supreme competition and recognition of our own inner resolve. Modern pop transports us to the city to an event in high demand with lights and nightime and drinks to match the smiles of the freshly-clad in attendance. 

Music is a place we go. 

And with the arrival of 2018, we've reached an era in which we don't need to close our eyes or visit our memory in order to travel there. We can go there in Virtual Reality. 

Let's bring people to the place of music, the planet of Pandora. 

As the virtual world continues to fill in and smooth out its own edges, Pandora will be there - a place to travel to in VR while the rest of the world falls in line behind. 

* Where VR stands: 
** VR is a developing technology. It is right now where computers were in the early '90s. The computing power needed to create truly life-like experiences in VR is not yet available to the masses. What a growing sector of the entertainment world is preparing for, though, is the eruption of Virtual Reality into a mass market, something akin to the .com boom. In a short time everyone is going to need to be VR literate.   
* The importance of being in position
** As VR continues to emerge and companies like Facebook remain committed to it's development with billion dollar investments, those in the industrial world who position themselves for this boom will be there to reap the financial reward when it arrives. 

* How to get started: 
** Lets keep it simple to start, allowing the user to travel to the Pandora planet where they can listen to music and experience the unique elements of Pandora, not just a as a music hub but as a physical destination. 

* Content Progression: 
** Phase 1: User puts on VR headset and travels to Pandora to listen to music 
** Phase 2: User discovers new music on Pandora 
** Phase 3: User sees music visuals - short video clips, music videos, movie segments that prominantly feature sound elements.  

* Distribution; 
** PR coverage/press kit
** Ads on VR websites (network buys on places where you know ppl have Vive)

* Fin Strat Research 
** Finding previous companies that had VR coverage covered in press
** For adding features: commercia-based, freemium, pay by the app
** once we know the price of all of these we'll know how much they need to break even
** Metric = how many ppl with headsets would use this app, highest performing/medium performing

* Strategy 
** push to gear VR first (more users)

