Objective: Explore how the gap between the early adopters and the early majority influences the development of the VR market.  

...

This is an introduction to Nova Media's multi-part examination of Virtual Reality's journey toward critical mass in the consumer market. 

VR has a long and fragmented history dating all the way back to Morton Heilig and the 1950s. Then there was a simulation of Aspen, Colorado that came out of MIT in the late 70's. A decade and a half later Sega announced the release of their first VR headset for an arcade game. 

All of these...breakthroughs that have led to predictions about how and when VR will make its significant impact on the consumer market. 

But as the years passed we heard just a faint noise from this new virtual world playing in the background, often drowned out by HD TVs, smartphones, and social media.

But the noise got louder in 2014 when Facebook acquired the Oculus headset for over $2 billion. And then - at the brand's annual conference last month - a louder noise from Mark Zuckerberg, who said, "I am more committed than ever to the future of VR."

So now, three years into Facebook's involvement with this emerging technology, we're still asking the question: when will VR reach critical mass?  

In 1989 Geoffrey Moore wrote the first version of "Crossing The Chasm", studying why, how, and at what rate new ideas and technologies spread through the market. 

As young technologies progress through the adoption life cycle, a gap forms between the early adopters and the early majority - causing the product or technology to stall before reaching the early majority (which makes up 1/3 of the consumer market).

This series will examine where VR stands in relation to this curve, what's prevented it from breaking through, and what will need to happen in order for it to cross the next divide.  

The reason: early adopters don't rely on external references. They try new technologies and make a purchasing decision based on what the they can imagine the new technology having. The early majority, on the other hand, seeks reliable points of reference before buying new tech. And that's the key 

The problem is that the early majority is about 1/3 of the market. Without reaching the early majority...

why doesn't early majority accept references from early adopters?

Where does VR stand in this progression? 

* Where is VR in relation to the chasm
** Who has VR?
** What businesses?
** What type of people are interacting with it?
** What characteristics make up an innovator/adopter? 
** What about business early adopters? 





