** Tag

Anywhere In The World 

* Description

Among the earliest yields of VR is Virtual teleportation. Wear the headset, click the button, and travel anywhere. We've crafted this limitlessness into a global New Year's celebration. Guests select from a globe of destinations and join the first ever Live New Year's in VR.

** The Experience 

Begin in your branded lobby, the Virtual globe at center. Click it, move it, rotate it, and select among marked locations. Travel stylishly and arrive among the people. Listen to the sounds; explore the town. Stay a while or return to the lobby to explore another celebration. 

** In Business 

Destinations, transportation, and clothing preferences are among the customizable elements of this live event. We arrange 360 cameras in cities around the world, stream the content, centralize it in a CG game engine, and publish it on VR app stores. Users can travel with friends, meet new people along the way, or go it alone.

** Effect

Destinations working to attract visitors may display their culture, infrastructure, and appearance - shedding light in a brand new way. 

** Introduce

Virtual Teleportation to show real people real destinations on the last night of the year. Make global use of VR's live potential.  

