*** New Year's Eve Live in VR (Right box scroll, Title, punchline)

**** Unify the world via live 360º VR this New Year’s Eve 

Live in stereoscopic 3D virtual reality we'll bring you to 10 iconic locations around the world. All you need is the internet to connect.  We will centralize live new year's eve 360 streams from aorund the globe into a computer graphic lobby developed in Unity.

/36 consecutive hours of New Year’s Eve festivities/

Visit with locals, explore new cities, and toast to the future of travel!

Promoted to 14 million, we will live stream 360º - 4k video for 36 straight hours, enabling anyone with the internet to join in the celebration!  People will be able to experience NYE from anywhere in the world through their web browser, including facebook and youtube or through their Samsung, HTC or Oculus VR headset.   

Pre-register now for exlsuive access and event announcements 
: sign up email button

The locations will be chosen by YOU, practical logistics and sponsorships, evenly broadcasting across most timezone.   Currently, the most favored destinations are: Melbourne, Taipei, Dubai, Istanbul, Kiev, Debruvnik, Rome, Paris, New York, Buenos Aires, San Francisco and Honolulu.   Tell us where you would like to go!
: text box to submit destination


Want to beome a sponsorship partner?  This production is ideal for travel destinations, services and products, or retail of anykind.  Through /Novapay/ we enable you to sell your products direct to consumers in virtual experiences.  to learn more, email AnnaIrene@novamedia
