\\* Aquarieum

** Objective:    

create a VR experience that crossing into phsyical world engagement for the entertainment of aquaerium goers.

** Budget:      

TBD est 100-200k.

Aquarium can upcharge for it,   5-8 dollars. How many people are we expecting to come through.
-- How many visitors does it have?
--  

Chris will rent the exhibit to the aquierium, monthyl  



Timing:

Experience to be ~4 minutes, 6 tops with set up break down.

Opens memorial day 2019.

set up at the exhibit - 18 month run.. building it for an equirium.  May 2019- january 2021.   Getting the exhibit back and then rent it to a new location.  up sell it on their part.  rent it to them on a monthly basis, and they can charge accordingly.

** Desicion Making Process:

 Chris is the sole desicion maker, it is his company and he is the artist.  We should also get Eric involved, it is his rfriend and we would want him for the 3d audio.  
** Notes:


** Creative:




Aquerium, habitats, theming, outside in the zoo itself, interpretive graphics..... do not have the ability to do anything too dynamic.  they are currently under contract.  an aquierem visit all around steeam punk , based on 19th century vicotrian life, highly over engineered. people get really creative, create their own character.   crazy goggles on, ghears everywhere. to do one mundane task, there are 19 different things that have to happen first. , polished metal steel and brass, and there is an aquaieruim on this type of art.

different types of aniimals.   mechanical animal.

great white shark diving experience in virtual reality.  users actually enter a physical shark cage.    they put the glasses on, maybe glove -- probably not, hold onto the shark cage bars.  experience lifted off the ship, over the ocea, and then into the ocean  banging into the cage, have it so it is actually activated.

Now what if we did weird, mechanical, robotic kind of sharks  -

8 users at a time.   imagine the shark cage, four in one direction, four in the other,  door on one side and door on the pther.   everyone else is hanging onto the cage, sharks are swimming on the outside    5 minutes from strart to finish.






turn over time 5-6 minutes (tops)  minute tos.


 clean with alcohol wipes.


speaker in the cage.


artists.
and the interactivety


clever not moving around/   (so it does not need)




lowered into the water.


